### PR TITLE
Add gold rating to Tripal HQ

### PR DESCRIPTION
**Pull request by bradfordcondon**
# Documentation

Issue N/A

## Description

I'm submitting Tripal HQ as a Gold-rated module.  Below is my rating checklist.  TripalFields and TripalImporters are not relevant for this module.  [Here is the repo](https://github.com/statonlab/tripal_hq).

With this PR I think we'll get a chance thinking about a) how to add the badge, b) how to determine if I've done a reasonable job self-reporting

## Bronze

- [x] Has a public release.
- [x] Should install on a Tripal site appropriate for the versions it supports.
- [x] Defines any custom tables or materialized views in the install file (if applicable).
- [x] Adds any needed controlled vocabulary terms in the install file (Tripal3).
- [x] Provides Installation and admin instructions README.md (or RTD).
- [x] Has a license (distributed with module).

## Silver
- [x] Follows basic Drupal Coding standards; specifically, code format and API documentation.
- [x] Uses Tripal API functions. Specifically, it should use the Chado Query API for querying chado (if using chado as the storage system)
- [x] Tripal Jobs API for long running processes
- [ ] ~~TripalField class to add data to pages (Tripal3).~~
- [x] Provides ways to customize the module (e.g. drush options, field/formatter settings, admin UI).
- [x] Latest releases should follow Drupal naming best practices. e.g. first release for Drupal 7 should be: 7.x-1.x.

Gold
- [x] Extensive documentation for the module (similar to Tripal User’s Guide).
- [x] Unit testing is implemented using PHPUnit with the TripalTestSuite or something similar.
- [x] Continuous integration is setup (e.g. such as with TravisCI).
- [ ] ~~Imports data via Tripal’s importer class (Tripal3).~~
- [ ] ~~Tripal 3 fields are (Tutorial) Fully compatible with web services.~~
- [ ] ~~The elementInfo function is fully implemented.~~
- [ ] ~~The query and queryOrder functions fully implemented.~~
- [ ] ~~Web Services uses Tripal’s Web Service Classes (Tripal3).~~
- [x] Code sniffing and testing coverage reports (optional but encouraged).
- [ ] Drupal.org vetted release (optional but encouraged).

### CODE REVIEW

**Comment by bradfordcondon** [comment]
I placed the badge under the module header, is that right?  I don't actually see instructions on where to place it: we should probably add it to [the RST template we provide](https://tripal.readthedocs.io/en/latest/extensions/instructions.html#instructions)
screen shot 2019-02-28 at 1 32 12 pm

**Comment by spficklin** [comment]
Looks great!  I like the checkboxes and would recommend we incorporate them into a pull request template to make it easier for others to justify their request.

**Review by spficklin — APPROVED** [review]

**Comment by spficklin** [comment]
For those elements that are not applicable, is it possible to use the README table markup to have, where it applies, two rows of checkboxes, one in a column with the header 'Meets Criteria' and another 'Does not Apply'?  That way we could distinguish between elements that are not applicable and those that are just not implemented.

**Comment by spficklin** [comment]
Well, I just tested a table it doesn't work with checkboxes... what about this:

**Confirm Gold-Level Rating**
Indicate if your module meets the following criteria:
1. - [x] Yes, extensive documentation for the module (similar to Tripal User’s Guide).
2. - [x] Yes, unit testing is implemented using PHPUnit with the TripalTestSuite or something similar.
3. - [x] Yes, continuous integration is setup (e.g. such as with TravisCI).
4. Imports data via Tripal’s importer class (Tripal3).
    - [ ] Yes
    - [x] Not Applicable
5. Tripal 3 fields are fully compatible with web services.
    - [ ] Yes
    - [x] Not Applicable
6. Tripal 3 field elementInfo function is fully implemented
    - [ ] Yes
    - [x] Not Applicable
7. Tripal 3 field query and queryOrder functions fully implemented.
    - [ ] Yes
    - [x] Not Applicable
8. Web services uses Tripal’s Web Service Classes (Tripal3).
    - [ ] Yes
    - [x] Not Applicable
9.  Optional:
    - [x] Code sniffing and testing coverage reports (optional but encouraged).
    - [ ] Drupal.org vetted release (optional but encouraged).

**Comment by bradfordcondon** [comment]
checkboxes do render in tables the formatting just needs some tinkering (you need to add the `<ul> <li>` html elements manually :


```md

| Task           | Time required | Assigned to   | Current Status | Finished | 
|----------------|---------------|---------------|----------------|-----------|
| Calendar Cache | > 5 hours  | @georgehrke | in progress | - [x] ok?
| Object Cache   | > 5 hours  | @georgehrke | in progress | [x] item1<br/>[ ] item2
| Object Cache   | > 5 hours  | @georgehrke | in progress | <ul><li>- [x] item1</li><li>- [ ] item2</li></ul>
| Object Cache   | > 5 hours  | @georgehrke | in progress | <ul><li>[x] item1</li><li>[ ] item2</li></ul>
```

[source this issue](https://stackoverflow.com/questions/47344571/how-to-draw-checkbox-or-tick-mark-in-github-markdown-table)


so do you propose we have a PR template JUST for module rating requests?  We can do that.  the alternative is to put it in a markdown codeblock in the module rating instruction in the docs.  although now that im typing it out, no one is going to do that hahah we probaby do need a separate template.

**Review by laceysanderson — APPROVED** [review]
My overly thorough Process for reviewing a module rating PR (only check those mentioned applicable by the applicant)

1. Check Repository for:
  - [x] License (BRONZE)
  - [x] Public Release (BRONZE)
  - [x] Latest releases should follow 7.x-version format (SILVER)
  - [n/a] an includes/TripalFields directory (SILVER)
  - [n/a] an includes/TripalImporter directory (GOLD)
  - [x] a tests directory (GOLD)
2. Check the README/docs for:
  - [x] Installation Instructions (BRONZE)
  - [x] Admin/Usage Instructions (BRONZE) 
  - [x] Link to Extensive Documentation (GOLD)
  - [x] Continuous integration badges (GOLD)
3. Check the install file for:
  - [n/a] chado_create_custom_table() (BRONZE)
  - [n/a] chado_add_mview() (BRONZE)
  - [n/a] tripal_add_cvterm() or equivalent (BRONZE)
4. Check random file for Drupal coding standards. Specifically, (SILVER)
  - [x] docblock headers for functions
  - [x] general style (if/else blocks, array definitions)
  - [x] in-line commenting
5. Search code-base for
  - [x] `chado_query`, `chado_select_record`, `chado_update_record` (SILVER)
  - [x] `tripal_add_job` (SILVER)
  - Perhaps it would be easy enough to ask the submitter to provide links to example usage in their module?
6. Check a random TripalField for:
  - [n/a] elementInfo (GOLD)
  - [n/a] query and queryOrder (GOLD)
7. Check for signs of an admin UI
  - [x] files with *admin* or *config* in the name
  - [n/a] settings in TripalFields
  - [n/a] drush options
  - Perhaps it would be easy enough to ask the submitter to provide links to example config in their module?

How to check:
- Should install on a Tripal site appropriate for the versions it supports. 
   - This is a checkmark if they have CI passing.

Perhaps it would be good to add a "Helpful Links" section at the top of a Module Rating PR template for:

```
## Helpful Links
Adding links below will provide greater strength to your self-evaluation and help us review your PR :-) Links to lines in specific files in your repository are particularly helpful (click on the line number in github to highlight it).
 - Repository:
 - Example Tripal Chado API Usage:
 - Example TripalField (if applicable):
 - TripalImporter (if applicable):
 - Example admin configuration:
```

**Pull request merged**
