### PR TITLE
TripalEntity form upgrades to match NodeForm

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task

## Description

This PR upgrades the TripalEntity add/edit form to match the Node add/edit form. More specifically, the node page has an "Advanced Sidebar" in both Claro and Gin admin themes that holds administrator-focused elements such as revisions, authorship, URL alias, etc. and this PR brings that sidebar to the TripalEntity form. It does this without using the TripalLayout module but also supports users adding to it using the TripalLayout module.

| TripalEntityForm | NodeForm |
| --- | --- |
| image | image |

### Tasks

- [x] Add the Advanced group to our TripalEntityForm and populate it with metadata for the page as is done in the NodeForm
- [x] Figure out why Claro/Gin weren't theming our Advanced group the same way they did on the NodeForm and forcing them to do so 😜 
- [x] Add an "Authoring Information" tab group to the Advanced group
- [x] Remove the ability to configure the title on the TripalEntityForm in order to reduce conxusion/repetition
- [x] Add for support for the created property so that it can be included in the authorship information as it is on the node form.
- [x] Add in missing getters for the changed property so that we could display how old the content is and when it was last updated.
- [x] Update the TripalEntity::label() method to support HTML as we had done in PR #1878 since the new add/edit forms changed the titles and broke the original page title fixes. As such, I also removed the old page title fix as this solution replaces it.
- [x] Updated the base field definitions to hide some repetitive fields by default in the view

## Testing?

1. Create a new docker on this branch
2. Go to Admin > Tripal > Content > "Add Tripal Content" and then pick to add whichever one you like most. I'm choosing organism in the screenshots.
    - Confirm the page loads as expected in the screenshot
    - Fill it out and confirm it saves without error
    - Edit the page and ensure it fills in all the default without error

| Add Organism | Edit Organism |
| --- | --- |
| image |  image |

3. Repeat step 2 for the other admin theme options to ensure we test Gin Light, Gin Dark, and Claro. Gin to Claro switch is done by going to "Appearance" changing the "Admin theme" drop down. Changing from Gin Light to Dark is done by going to Appearance > Settings.

| Gin Dark | Claro |
| --- | --- |
| image |  image |

4. Go to "Manage Form Display" for a Tripal Content Type and move the Author field into a field group. Confirm this pulls the author out of the sidebar.
5. Now add a new fieldgroup of type "Details Sidebar" and put some fields in it. Confirm this shows up in the advanced sidebar.

Screenshot 2024-11-02 at 2 43 54 PM

image

6. Now click the "Apply Tripal Layout" on the "Manage Form Display" and confirm it applies and that now when you Add/Edit content of that type, the Tripal Layout doesn't break the new changes to the form.
image

### CODE REVIEW

**Comment by dsenalik** [comment]
I'm starting some notes for things I am noticing.
The various dbxref fields could use some tweaking, the db name is squished, it needs a higher percent of the width
**Claro**
2024-11-02_claro
**Gin dark**
2024-11-02_gindark1
**Olivero**
2024-11-02_olivero2


The olivero add tripal content list displays the types twice.
2024-11-02_olivero1

For comparison here are the **Drupal Add Content Forms**
2024-11-02_DrupalContent

**Comment by dsenalik** [comment]
For the dbxref widget, I tried modifying `tripal_chado/src/Plugin/Field/FieldWidget/ChadoDbxrefWidgetDefault.css` as follows
```

.field--widget-chado-dbxref-widget-default .fieldset__wrapper {
  display: flex !important;
}
.field--widget-chado-dbxref-widget-default .fieldset__wrapper .form-item {
  margin: 0 var(--gin-spacing-xs);
  flex 1 1 0;
}
/** -- Database Name */
.field--widget-chado-dbxref-widget-default .fieldset__wrapper .form-item:first-of-type select {
}
/** -- Accession */
.field--widget-chado-dbxref-widget-default .fieldset__wrapper .form-item:last-of-type {
}
```
and now I see the database sized to the length of the longest database and the remainder allocated to accession, which seems ideal
newcss

**Comment by laceysanderson** [comment]
Updated the tripal log to match better with the gin aesthetic.
Also made the css rule which hides the duplicated title in the add content list less specific so it will apply to all themes not gin.
Screenshot 2024-11-03 at 2 01 42 PM
Screenshot 2024-11-03 at 2 02 00 PM

Screenshot 2024-11-03 at 2 02 20 PM

**Comment by laceysanderson** [comment]
Progress on the dbxref widget based on @dsenalik suggestions. Unfortunalty is is still janky because the primary dbxref has the field description within the fieldset...

Screenshot 2024-11-03 at 3 05 53 PM
Screenshot 2024-11-03 at 3 02 06 PM
Screenshot 2024-11-03 at 3 02 38 PM

**Comment by laceysanderson** [comment]
Got it! I gave the db name + dbxref accession their own wrapper, got rid of the weird fieldset and set the db name to grow in wide screen but still not shrink past the max content. See how the dbxref now fits in well with the contact linker field in the following screenshots 😃 

Screenshot 2024-11-03 at 3 29 31 PM
Screenshot 2024-11-03 at 3 30 04 PM
Screenshot 2024-11-03 at 3 30 36 PM

**Comment by dsenalik** [comment]
kermit-frog

**Comment by dsenalik** [comment]
I built a new docker. Default light gin theme to start.
I started to add a "Study" and when I tried to enter the dbxref this happened and I couldn't enter the accession.
PR2019 1104 1
Same thing happens in the other themes too...

**Comment by dsenalik** [comment]
I tried adding a new organism without a dbxref and see this
PR2019 1104 2

Fixed with commit https://github.com/tripal/tripal/pull/2019/commits/868b2055a76e641ed66fcaf0dcc025aa04354db6

**Review by dsenalik — APPROVED** [review]
I have now gone through the full testing one final time and find no remaining issues 🎉

**Comment by laceysanderson** [comment]
Thanks @dsenalik!

**Pull request merged**
