### PR TITLE
214 tripal version api

### PR DESCRIPTION
**Pull request by Ferrisx4**
# New Feature

Issue #214

## Description

As suggested in #214, this adds two methods for developers to retrieve the current Tripal version:
 - via the tripal_version() command
 - via the trp-version drush command

## Testing

From a module, or with `drush php-eval`, call tripal_version(). It should return (not print) the version string.
From the command line, call `drush trp-version`. It should print the version string.

## Additional Notes

In the usual place for API functions, i.e. tripal/api/, there did not seem to be an appropriate place to include this function, so I stuck it at the bottom of the tripal.module file among a number of other Tripal functions. This may not end up being the best place for it.

### CODE REVIEW

**Comment by spficklin** [comment]
Hey @Ferrisx4 I tested it and it works fine.  The only problem with it is related to what @bradfordcondon brought up in the issue, is that we keep forgetting to update the version of Tripal! Currently in the `.info` file it is set at `7.x-3.1` but we are already at `7.x-3.4`.  Since you posted the fix can you go through all of the .info files in the tripal core modules (e.g. tripal, tripal_chado, etc) and update them to say `7.x-3.5` since that is the next version we will release?

**Comment by Ferrisx4** [comment]
hi @spficklin, sure no problem. For legacy modules such as `/legacy/tripal_analysis/` are we also keeping those up to date with the latest version number? I am guessing _yes_.
While I'm at it, I can also update the docs unless it is too early for that.

**Comment by spficklin** [comment]
HI @Ferrisx4 yep, those legacy modules should have the same version as all of the core modules too.

**Comment by spficklin** [comment]
Great! Thanks @Ferrisx4

**Pull request merged**
