### PR TITLE
Improve Tripaldocker: support VSCode devcontainers + single dockerfile with args approach

### LINKED ISSUE #1950: Improve Tripaldocker: support VSCode devcontainers + explore single dockerfile with args approach
### Task Description

It would be good to improve the tripaldocker in a number of ways. This issue is currently specific to the following:

1. Have supervisord actually start postgresql on run of the docker container.
2. Add a .devcontainer VSCode configuration file to help people setup development environments configured with Drupal standards and helpful add-ons.
3. Explore using ARGs before the FROM clause to reduce our multiple dockerfiles into a single one for better devcontainer and windows support
4. Print out a helpful message on run with commands, branding and login information.

### Branch Name

tv4g8-issue1950-improveTripalDocker

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task

## Description

It would be good to improve the tripaldocker in a number of ways. This PR is currently specific to the following:

 - [x] Have supervisord actually start postgresql on run of the docker container.
 - [x] Add a .devcontainer VSCode configuration file to help people setup development environments configured with Drupal standards and helpful add-ons.
 - [x] Explore using ARGs before the FROM clause to reduce our multiple dockerfiles into a single one for better devcontainer and windows support
 - [x] Print out a helpful message on run with commands, branding and login information.
 - [x] Create a base tripaldocker-drupal image that handles the os and drupal install so that the tripaldocker is much faster to build
 - [x] Update the build docker workflows including scheduled updates

### Checking docker build and supervisord setup

1. Clone this repo and checkout this branch.
2. Build the docker image using the single Dockerfile :-) Try this with different versions of php (i.e. 8.1, 8.2, 8.3), Drupal (i.e. 10.2.x-dev, 10.3.x-dev, 10.3.2), and PostgreSQL (i.e. 13, 14, 15, 16). This should complete without error.
```
docker build --tag=tripaldocker:localdocker \
            --build-arg phpversion="8.3" \
            --build-arg drupalversion="10.3.x-dev" \
            --build-arg postgresqlversion="16" \
            --build-arg chadoschema='teapot' ./
```
3. Once you have an image, create a container and confirm that it (a) has the versions expected based on the parameters to the image, (b) that both apache and postgresql start on their own without having to run the service command!
```
docker run --publish=80:80 --name=tripaldocker -tid tripaldocker:localdocker
```

### Test out using the configured devcontainer with VSCode

1. Clone this repo and checkout this branch.
2. Open the directory in VSCode.
3. Ensure you have the Microsoft Dev Containers extension by going to Extensions in VSCode and searching for `ms-vscode-remote.remote-containers`.
4. Then click the DevContainers status icon in the bottom left corner. It will look like the green double arrow square in the following screenshot. This will pop open the command palette where you want to choose "Reopen in Container". This will build a docker image and start a container!

Screenshot 2024-08-10 at 5 00 55 PM
6. To view your tripal site, you need to click on ports in the terminal section and then on the globe symbol beside the forwarded address for Port 80. This will open it in a web browser and you will see that postgresql + apache are already started! You can also interact with the container directly (i.e. no need for `docker exec...` in the VSCode terminal.
Screenshot 2024-08-10 at 5 03 19 PM

You can see more about this in this PR https://github.com/tripal/tripal_doc/pull/92

### Motd / Help Text

You can see the login information by checking the logs of the container via the command-line or docker desktop.
Screenshot 2024-08-10 at 7 33 45 PM

### CODE REVIEW

**Comment by dsenalik** [comment]
Awesome. I know this is still a draft but everything worked for me as advertised!

**Comment by dsenalik** [comment]
If I build a docker the "usual" way, stop it, then restart it `docker start 1950` then both apache2 and postgresql are running.
```
root@99a24ae69440:/var/www/drupal/web# service postgresql status
15/main (port 5432): online
root@99a24ae69440:/var/www/drupal/web# service apache2 status
apache2 is running.
```

If I stop and start the docker built by vscode `docker start 91058caf588c` then neither apache2 nor postgresql are running. 
```
root@91058caf588c:/var/www/drupal/web# service postgresql status
16/main (port 5432): down
root@91058caf588c:/var/www/drupal/web# service apache2 status
apache2 is not running ... failed!
```
Any idea why this might be?

**Comment by laceysanderson** [comment]
Added documentation here: https://github.com/tripal/tripal_doc/pull/92

**Review by dsenalik — APPROVED** [review]
I re-tested everything and it looks good! Faster container builds 😍

I have one comment about starting a devcontainer
At the end of the process it looks like this
2024-08-stuck-on-configuring
with "Configuring Dev Container" apparently still doing something. This is because apache is running in the foreground. If you hit ^C you kill it and end your terminal session. I seem to remember that there is some reason for running it in the foreground, but am not sure.
Anyway, while this is the state, I can get a bash shell directly with e.g. `docker exec -it dd53de004e88 /bin/bash`

I ran several unit tests and it worked great!

**Comment by reynoldtan** [comment]
Tried the items described in the Test section and confirmed the following worked on my Windows computer.

I used the following command (omitted forward slashes, Win throws an error)
docker build --tag=tripaldocker:localdocker --build-arg phpversion="8.3" --build-arg drupalversion="10.3.x-dev" --build-arg postgresqlversion="16" --build-arg chadoschema='teapot' ./

1. Software stack versions were correctly set

image

image

image

2. Pertinent services are running without starting.

image

image

Second part of the Test worked as well and I got an offer to view the site in the dialog box window.
image
Alternatively, clicking the globe icon will launch my Tripal instance.

image

**Comment by carolyncaron** [comment]
Testing through VS Code worked perfectly!

I was also able to build the docker outside of VS code using different combinations of Drupal, php and postgresql. However, I ran into issues with building using Drupal 10.3.2 specifically (here I tried it with all versions of postgresql):

``` console
FVFJ509LQ6M0:tripaldocker ctc413$ docker build --tag=tripaldocker:localdocker --build-arg phpversion="8.2" --build-arg drupalversion="10.3.2" --build-arg postgresqlversion="13" --build-arg chadoschema='teapot' ./
[+] Building 0.3s (2/2) FINISHED                                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 1.36kB                                                                                             0.0s
 => ERROR [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql13                     0.3s
------
 > [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql13:
------
Dockerfile:4
--------------------
   2 |     ARG drupalversion='10.3.x-dev'
   3 |     ARG postgresqlversion='16'
   4 | >>> FROM tripalproject/tripaldocker-drupal:drupal${drupalversion}-php${phpversion}-pgsql${postgresqlversion}
   5 |     
   6 |     ARG modules='devel devel_php field_group field_group_table'
--------------------
ERROR: failed to solve: tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql13: docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql13: not found
FVFJ509LQ6M0:tripaldocker ctc413$ docker build --tag=tripaldocker:localdocker --build-arg phpversion="8.2" --build-arg drupalversion="10.3.2" --build-arg postgresqlversion="14" --build-arg chadoschema='teapot' ./
[+] Building 0.3s (2/2) FINISHED                                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 1.36kB                                                                                             0.0s
 => ERROR [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql14                     0.3s
------
 > [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql14:
------
Dockerfile:4
--------------------
   2 |     ARG drupalversion='10.3.x-dev'
   3 |     ARG postgresqlversion='16'
   4 | >>> FROM tripalproject/tripaldocker-drupal:drupal${drupalversion}-php${phpversion}-pgsql${postgresqlversion}
   5 |     
   6 |     ARG modules='devel devel_php field_group field_group_table'
--------------------
ERROR: failed to solve: tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql14: docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql14: not found
FVFJ509LQ6M0:tripaldocker ctc413$ docker build --tag=tripaldocker:localdocker --build-arg phpversion="8.2" --build-arg drupalversion="10.3.2" --build-arg postgresqlversion="15" --build-arg chadoschema='teapot' ./
[+] Building 0.3s (2/2) FINISHED                                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 1.36kB                                                                                             0.0s
 => ERROR [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15                     0.3s
------
 > [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15:
------
Dockerfile:4
--------------------
   2 |     ARG drupalversion='10.3.x-dev'
   3 |     ARG postgresqlversion='16'
   4 | >>> FROM tripalproject/tripaldocker-drupal:drupal${drupalversion}-php${phpversion}-pgsql${postgresqlversion}
   5 |     
   6 |     ARG modules='devel devel_php field_group field_group_table'
--------------------
ERROR: failed to solve: tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15: docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15: not found
FVFJ509LQ6M0:tripaldocker ctc413$ docker build --tag=tripaldocker:localdocker --build-arg phpversion="8.2" --build-arg drupalversion="10.3.2" --build-arg postgresqlversion="16" --build-arg chadoschema='teapot' ./
[+] Building 0.2s (2/2) FINISHED                                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 1.36kB                                                                                             0.0s
 => ERROR [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql16                     0.2s
------
 > [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql16:
------
Dockerfile:4
--------------------
   2 |     ARG drupalversion='10.3.x-dev'
   3 |     ARG postgresqlversion='16'
   4 | >>> FROM tripalproject/tripaldocker-drupal:drupal${drupalversion}-php${phpversion}-pgsql${postgresqlversion}
   5 |     
   6 |     ARG modules='devel devel_php field_group field_group_table'
--------------------
ERROR: failed to solve: tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql16: docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql16: not found

```

**Comment by dsenalik** [comment]
I just build a docker on drupal10.3.2 php8.2 pgsql16 with no problem.
I wonder if it is one of those temporary internet things, maybe docker.io was temporarily down?

My build script does this
```
drupalver=10.3
phpver=8.2
postgresqlversion=16
chadoschema=chado
docker build \
  --tag=tripaldocker:testing-$n \
  --build-arg drupalversion="${drupalver}.x-dev" \
  --build-arg postgresqlversion="${postgresqlver}" \
  --build-arg chadoschema="$chadoschema" \
  --progress=plain \
  ./ \
  2>&1 | tee /tmp/build-$n.log
```

**Comment by carolyncaron** [comment]
Thanks for confirming Doug 👍  To be clear, I am also able to successfully to build an image using the parameter for drupalversion `10.3.x-dev`, which was 10.3.2 as of this morning but now it seems to be updated to 10.3.3 😅. Here is the status report after running the container:
Screenshot 2024-08-13 at 1 00 45 PM

I think the issue might be that version "10.3.2" can't be explicitly provided as a Drupal version 🤔 I also just confirmed that specifying 10.3.3 also doesn't work:
```
docker build --tag=tripaldocker:localdocker --build-arg phpversion="8.2" --build-arg drupalversion="10.3.3" --build-arg postgresqlversion="16" --build-arg chadoschema='teapot' ./
[+] Building 0.6s (2/2) FINISHED                                                                                             docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 1.36kB                                                                                                       0.0s
 => ERROR [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.3-php8.2-pgsql16                               0.5s
------
 > [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.3-php8.2-pgsql16:
------
Dockerfile:4
--------------------
   2 |     ARG drupalversion='10.3.x-dev'
   3 |     ARG postgresqlversion='16'
   4 | >>> FROM tripalproject/tripaldocker-drupal:drupal${drupalversion}-php${phpversion}-pgsql${postgresqlversion}
   5 |     
   6 |     ARG modules='devel devel_php field_group field_group_table'
--------------------
ERROR: failed to solve: tripalproject/tripaldocker-drupal:drupal10.3.3-php8.2-pgsql16: docker.io/tripalproject/tripaldocker-drupal:drupal10.3.3-php8.2-pgsql16: not found
```

**Comment by dsenalik** [comment]
I tried your exact command and got the error
```
$ docker build --tag=tripaldocker:localdocker --build-arg phpversion="8.2" --build-arg drupalversion="10.3.2" --build-arg postgresqlversion="15" --build-arg chadoschema='teapot' ./
[+] Building 0.7s (2/2) FINISHED                                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                                   0.1s
 => => transferring dockerfile: 1.36kB                                                                                                 0.0s
 => ERROR [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15                         0.4s
------
 > [internal] load metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15:
------
Dockerfile:4
--------------------
   2 |     ARG drupalversion='10.3.x-dev'
   3 |     ARG postgresqlversion='16'
   4 | >>> FROM tripalproject/tripaldocker-drupal:drupal${drupalversion}-php${phpversion}-pgsql${postgresqlversion}
   5 |     
   6 |     ARG modules='devel devel_php field_group field_group_table'
--------------------
ERROR: failed to solve: tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15: failed to resolve source metadata for docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15: docker.io/tripalproject/tripaldocker-drupal:drupal10.3.2-php8.2-pgsql15: not found
```
but if I change 
`--build-arg drupalversion="10.3.2"`
to
`--build-arg drupalversion="10.3.x-dev"`
then it builds

**Comment by laceysanderson** [comment]
@dsenalik and @carolyncaron:
The downside of the faster build time is that we have to explicitly build the base drupal image in order to be able to build that combo for Tripal.
I have it scheduled in [this workflow](https://github.com/tripal/tripal/pull/1951/files#diff-7a316ca08b3c98752a70a5ddd4bf8f4584288b5540d733fff152b9dce4886a6aR21-R36) to build specific version combinations and it doesn't include the stable releases of Drupal unfortunately. I did expand it to include all supported versions of PostgrSQL now but it might take too much effort to keep up with the stable Drupal versions 🤔 What do you think?

**Comment by dsenalik** [comment]
That's a lot of combinations as it is, I think as long as the docs mention this it is fine 😼.

**Comment by laceysanderson** [comment]
Ok, all the tests are passing and it looks like things are working great we just need a bit more info in the docs to let ppl know it's restricted to a set of drupal versions. With this in mind I'm going to merge! Thanks for all the reviews!!!

**Pull request merged**
