### PR TITLE
Postgresql version settable for building a docker

### LINKED ISSUE #1820: Postgres version in the docker files is hardcoded, make it settable
### Task Description

Allow passing the Postgres version when building a Docker. Right now it is hardcoded. _i.e._
`  && DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-13 postgresql-client-13 postgresql-contrib-13`

### Branch Name

tv4g0-issue1820-psql-docker-version-settable

### PR DESCRIPTION
**Pull request by dsenalik**
# Tripal 4 Core Dev Task

## Description
This changes the docker files to allow passing the Postgresql version and building a docker on a version newer than 13. Versions 14, 15, and 16 can now be specified.

To do this for any version >13 we need to first fetch the PostgreSQL Package Source, but I have a conditional so this will be skipped for version 13.

Note that I have renamed the docker files to remove the hardcoded Postgresql version from the file name. I will need a PR for the tripaldoc repository to update instructions!

## Testing?
You can try to build a docker on Postgresql version 16 with
```
export drupalver=10.2
export phpver=8.3
export chadoschema=earlgrey
export postgresqlver=16
docker build \
  --tag=tripaldocker:testing-1820 \
  --build-arg drupalversion="${drupalver}.x-dev" \
  --build-arg postgresqlversion="${postgresqlver}" \
  --build-arg chadoschema="$chadoschema" \
  --file tripaldocker/Dockerfile-php${phpver} \
  --progress=plain \
  ./
```
```
...
#9 [ 5/27] RUN if [ "16" != "13" ] ; then   apt-get install -y curl apt-transport-https gpg --yes -qq 1>> ~/aptget.extras.log   && curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg   && echo "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" > /etc/apt/sources.list.d/postgresql.list   && apt-get update 1>> ~/aptget.update.log ;   fi
#9 1.019 debconf: delaying package configuration, since apt-utils is not installed
#9 DONE 3.2s
...
```

### CODE REVIEW

**Comment by pdtouch** [comment]
While testing the new build command,

$ docker build \
>   --tag=tripaldocker:testing-1820 \
>   --build-arg drupalversion="${drupalver}.x-dev" \
>   --build-arg postgresqlversion="${postgresqlver}" \
>   --build-arg chadoschema="$chadoschema" \
>   --file tripaldocker/Dockerfile-php${phpver} \
>   --progress=plain \
>   ./
#1 [internal] load build definition from Dockerfile-php8.3
#1 transferring dockerfile: 2B done
#1 DONE 0.0s

`ERROR: failed to solve: failed to read dockerfile: open Dockerfile-php8.3: no such file or directory
`

**Comment by pdtouch** [comment]
This PR was tested for PostgreSQL v16.2 on Tripal 4 based on description above and the steps in : 
https://tripaldoc.readthedocs.io/en/latest/contributing/docker-for-testing.html

The status report under the Tripal 4 GUI showed the installed version of PostgreSQL to be 

`16.2 (Debian 16.2-1.pgdg110+2) `

Other steps followed to verify PostGres upgrade from 13 to 16.2:

Checks thru PGSQL command line:

```
sitedb=# SELECT version() ;
PostgreSQL 16.2 (Debian 16.2-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 
64-bit
(1 row)

```

- Organism entered via GUI was visible in the database:

`sitedb=# select * from chado.organism;`

- Taxonomy for species association update went  thru ok

```
select a.organism_id, a.common_name, b.organism_id, c.accession 
 FROM chado.organism a, chado.organism_dbxref b, chado.dbxref c 
 where b.dbxref_id = c.dbxref_id
 AND a.organism_id=b.organism_id; 

 organism_id | common_name  | organism_id | accession 
-------------+--------------+-------------+-----------
           2 | Sweet orange |           2 | 2711

```

- Genes and sequences were imported via GFF3 and FASTA importers

`Import phylotree summary: <em class="placeholder">1</em> nodes were successfully associated to content, `

Chado GFF3 (gene) File Loader' importer - last line

```
Step 27 of 27: Adding sequences data (Skipped: none available)   - Done.
Chado FASTA (scaffold) File Loader' importer
```

Step 2: Importing sequences... Found 1 sequence(s).

Chado FASTA (mRNA) File Loader' importer

Step 2: Importing sequences. Found 9 sequence(s).

The Gene was published using :
**Content -> Tripal Content -> +Publish Tripal Content**

It was visible in the GUI from the Tripal Contents list.
 
Thanks @dsenalik  very much.

**Comment by laceysanderson** [comment]
This is looking really good! I've tested it manually with all default and requesting Drupal 10.0.x-dev, PHP 8.2 and PostgreSQL 16 and it works beautifully. 

Notes:
- in the docker build workflow, you removed the `installChado=FALSE` built argument for the image specific that should not include chado 🤪 so I added that back.
- I also took this opportunity to fix a small mistake in the labels for the docker images.
- I added in the various versions of postgresql to our regular testing and am waiting to see the result 🙈 I don't think we want to try to expand our grid for this but it would be good to test on multiple postgresql versions just in case 🤔 I may change it back to just testing on 12 and 16 but thought I would run it at least once with the full spectrum.

**Comment by dsenalik** [comment]
Oops, sorry about putting chado in the nochado 😬
If you keep in testing on Postgres 12 then maybe we should change the lines that check version
`RUN if [ "$postgresqlversion" != "13" ] ; then \`
to
`RUN if [ "$postgresqlversion" > "13" ] ; then \`

**Comment by laceysanderson** [comment]
Do you think we should switch the default PostgreSQL version to 16 instead?

**Comment by dsenalik** [comment]
Yes I do. I think we should start out Tripal 4 with the most current versions.

**Comment by dsenalik** [comment]
Because, remember that @pdtouch said "Our IT had raised a point about Postgres version 13 for Tripal 4."

**Comment by pdtouch** [comment]
I agree, it will certainly help our Tripal 4 installation to keep Postgres
16.  I think using a stack composed of more recent/current software will
make it easier to maintain them in the long run too. Our IT is worried
about software whose EOL is not too far away.

Thank you.

**Review by laceysanderson — APPROVED** [review]
Looks perfect -Thank you @dsenalik for your work on this!

**Pull request merged**
