### PR TITLE
Warnings, typos, small cleanup

### PR DESCRIPTION
**Pull request by abretaud**
Some fixes for warnings I found in the logs. A few typos too. And a progress % more correct.

### CODE REVIEW

**Comment by abretaud** [comment]
@spficklin by the way, I just made this online, I think it will interest you: https://github.com/abretaud/docker-tripal-demo
I'll send the link to the mailing list when the 2 last PRs are merged

**Comment by spficklin** [comment]
Thanks for the fixes.   The Docker instance is great.  There is also one that was created by @erasche as well that we link to from our Tripal home page:  https://github.com/erasche/docker-tripal.   

Any interested in combining efforts?

**Comment by hexylena** [comment]
@spficklin they are combined efforts, no worries, @abretaud and I are working together :) @abretaud is leveraging my containers for a demo site, something out of scope of my repo.

**Comment by abretaud** [comment]
We do combine efforts, I'm a contributor of this image :smile:
In fact the new github repo does not contain a specific dockerfile, nor specific code, it's just a docker-compose file (that uses this https://github.com/erasche/docker-tripal image with a specific set of tripal modules) + a script to load the tutorial data from tripal.info
So it's really just a quick way to get (almost) the same result as following the tripal tutorial step by step. And seeing the latest version of all the modules I touched the last weeks

**Comment by abretaud** [comment]
oh, comment collision :smile:

**Comment by hexylena** [comment]
@abretaud lol, good timing ;)

**Comment by spficklin** [comment]
Okay.  That's good to hear!  I mentioned in a previous Tripal User's meeting we should have a page in the User's Guide for setting up the Docker Instance rather than just linking to it to help folks get it setup.  If I get that page started on the Tripal.info site would you guys mind updating it?

**Comment by hexylena** [comment]
Yeah, absolutely

**Comment by abretaud** [comment]
Sure, no problem!

**Comment by abretaud** [comment]
@spficklin Would it be possible de synchronize the [drupal git repo](http://cgit.drupalcode.org/tripal) with github?
The docker image installs tripal with `drush pm-download tripal-7.x-2.x-dev` = commits made after October 7th on github are not included
Or maybe we should just get the tripal code from github directly instead of using pm-download?

**Comment by spficklin** [comment]
Yes, we need to make sure these stayed as synced as possible.  Sorry it wasn't done.  I just pushed to drupal.org.

**Comment by abretaud** [comment]
Cool, thanks!

**Pull request merged**
