### PR TITLE
Customizable Transcripts on Gene Pages

### PR DESCRIPTION
**Pull request by spficklin**
# New Feature

Issue #100 

## Description

This PR adds new functionality that has been  requested for quite some time: supporting dynamic and customizable gene pages.  In particular the issue of how to display nested data about transcripts is addressed.  The solution is to allow the site admin to customize the `so__transcripts` field. The site admin can edit the field on the gene page and select fields from an mRNA content type that should be shown.  They can also reorder the fields as needed.  This will allow the site admin to show as much or as little information as desired about a transcript and allow different Tripal sites to customize this.  

Despite that the display is changed for transcripts, the web services data is not changed.  But rather in web services the list of transcripts is provided and the end-user can obtain all the information about a transcript by following the link for the transcript.

This PR also includes an update to the User's Guide instructing site admins how to customize the transcripts.  

## Testing?

 Below are screenshots of the updated User documentation.  Just follow those instructions.

image
image
image
image
image

### CODE REVIEW

**Comment by Ferrisx4** [comment]
Initial manual testing is positive so far. Question - is it/would it be possible to hide fields within the Transcripts fieldset that do not have values such as for Product: 
Transcript Product No Value

@mpoelchau Also is wondering if it is possible to make it recognize other custom transcript types such as lnc_RNA.

**Comment by spficklin** [comment]
HI @Ferrisx4 . Yes, if you go to `Admin > Structure > Tripal Content Types` then click on the 'edit' link for mRNA there is a checkbox to hide fields with missing values.  Check that, save the mRNA content type then reload the gene page.  Those empty fields should be gone.

**Comment by Ferrisx4** [comment]
ok thanks @spficklin. I had been testing this on a Gene page so I had checked that box for Gene pages. Now I see it makes sense that this setting has to be enabled for mRNA since the Transcript is of that type.

**Review by chunhuaicheng — APPROVED** [review]
Tested and worked as described. A nice new function for the transcripts field.

**Comment by spficklin** [comment]
Thanks @chunhuaicheng for the review!

**Review by Ferrisx4 — APPROVED** [review]
Other than the five empty PNG files, this all looks good and also functions as advertised.

**Comment by spficklin** [comment]
Thanks @Ferrisx4 for the review as well.  Those empty files are showing up now. I'm not sure why there were empty before but now are there.  I'm going to merge.  Thanks.

**Pull request merged**
