### PR TITLE
Update TPPS Extension Module Rating

### PR DESCRIPTION
**Pull request by par12005**
# Documentation

## Description

Added Bronze badge to the TPPS Extension Module description in docs.

## Testing?

Test that docs still build correctly

## Additional Notes:
This is my first time contributing to Tripal, so please let me know if I'm doing anything wrong!

### CODE REVIEW

**Comment by spficklin** [comment]
Hi @par12005. Thanks for submitting your module for a badge!   This is great.  Could you help us out a bit and just confirm with a "Yes" that the module meets the Bronze requirements?  An example is here:  https://github.com/tripal/tripal/pull/944.   You don't need to format as a nice table, just confirm that you acknowledge that the module meets each of the requirements, or if a requirement doesn't apply.

**Comment by par12005** [comment]
Thanks @spficklin, I'm not familiar with releasing software, so please let me know if there is any problem with the way I did that. I have provided links to all of the Bronze requirements:

Has a public release: [Yes](https://github.com/par12005/TPPS/releases)
Should install on a Tripal site appropriate for the versions it supports: [Yes](https://treegenesdb.org/tpps)
Defines any custom tables or materialized views in the install file (if applicable): [Yes](https://github.com/par12005/TPPS/blob/master/tpps.install#L59)
Adds any needed controlled vocabulary terms in the install file (Tripal3): [Yes](https://github.com/par12005/TPPS/blob/8fea747e1c24358b59396beb33ca29715d4624a6/tpps.install#L231)
Provides Installation and admin instructions README.md (or RTD): [Yes](https://tpps.readthedocs.io/en/latest/install.html)
Has a license (distributed with module): [Yes](https://github.com/par12005/TPPS/blob/master/LICENSE)

**Comment by bradfordcondon** [comment]
after enabling the module and visiting /admin/config/content/tpps, i get the following database error

```
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "cartogratree_groups" does not exist LINE 3: cartogratree_groups g ^: SELECT g.group_name AS group_name, g.group_id AS group_id FROM {cartogratree_groups} g; Array ( ) in tpps_admin_settings() (line 39 of /Users/bc/tripal/sites/all/modules/custom/TGDR/admin/config.php).

```

I dont see a `cartogratree_groups` table definition anywhere in the module, is it perhaps defined in a dependency module?   Modules should define, or declare as dependencies modules that do define, all tables and fields they query for a bronze rating.

**Comment by par12005** [comment]
Thanks @bradfordcondon! TPPS is supposed to be able to use the cartogratree_groups table from the CartograTree module if that module is enabled. I forgot to put a check for that in the administrative configuration form. TPPS does not depend on CartograTree, but it does have more features if the CartograTree module is enabled. Should TPPS still define that table in the install file?

**Comment by bradfordcondon** [comment]
I think your solution of checking if the table exists is the correct one if it's not a "true" dependency of the module (users might be interested in TPPS without CartograTree, right?).
What's essential is that your module doesn't accidentally crash without CartograTree installed, as that's really what we want to achieve by "Defines any custom tables or materialized views in the install file".

So, I'd add the check to your admin area (really all places where you touch a Cartogratree table or field) and I'll look again.  If your module is looking for Cartogratree in many places and thats a pain, then I'd instead declare it as a dependency in the `.info` file.

**Comment by par12005** [comment]
I've updated TPPS with the CartograTree checks, if you would like to take another look.

**Comment by bradfordcondon** [comment]
Better, good job.  I'd say you're all clear for bronze.

 You might want to put a guard on the completed submissions table, as it crashes if there are no submissions (presumably)

```
Notice: Undefined index: id in tpps_completed_display() (line 21 of /Users/bc/tripal/sites/all/modules/custom/TPPS/includes/completed_display.inc).
TypeError: Argument 1 passed to tpps_table_display() must be of the type array, null given, called in /Users/bc/tripal/sites/all/modules/custom/TPPS/includes/completed_display.inc on line 39 in tpps_table_display() (line 17 of /Users/bc/tripal/sites/all/modules/custom/TPPS/includes/table_display.inc).
```

**Comment by par12005** [comment]
Thanks! I added a check to the completed submission page which redirects the user to the main TPPS form if there is not an accession provided.

**Comment by spficklin** [comment]
Thanks @par12005. I'm merging into the docs!

**Pull request merged**
