### PR TITLE
Issue 1298 multiple parent and other fixes

### PR DESCRIPTION
**Pull request by dsenalik**
# Bug Fix

Issues #1298 and #1299

## Description
Since starting line number is required, set as required on form and set default value.
For features with multiple parents, wrap processing in an explode() loop.
Error checking for cv term.

### CODE REVIEW

**Comment by risharde** [comment]
Thanks @dsenalik - working on testing this one, will confirm soon!

**Comment by risharde** [comment]
@dsenalik a response on testing. I received the following output/error when I tested the PR on my environment (clean install of Drupal 7 and latest Tripal 3 from cloning the master branch then switching to this PR's branch). 

`Step 24 of 27: Insert 'derives_from' relationships...
Removing temporary cache file: /tmp/TripalGFF3Import_znc0LU
SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
`

I will try to provide any other details I have if I can get to the SQL output

**Comment by risharde** [comment]
SQL log error
`2022-09-30 06:55:46.868 EDT [9756] ERROR:  null value in column "object_id" violates not-null constraint
2022-09-30 06:55:46.868 EDT [9756] DETAIL:  Failing row contains (592231, 3469, null, 327, null, 0).
2022-09-30 06:55:46.868 EDT [9756] STATEMENT:  INSERT INTO chado.feature_relationship (subject_id, object_id, type_id, rank) VALUES ('3424', '3423', '327', 0), ('3449', '3448', '327', 0), ('3454', '3453', '327', 0), ('3469', NULL, '327', 0), ('3474', '3473', '327', 0), ('3490', '3489', '327', 0), ('3505', '3504', '327', 0)`

**Comment by dsenalik** [comment]
I finally did something about this. I added code to skip insert when object_id is NULL, I am assuming because the object for the "derives from" is not defined in the gff3. 

The first example of this in the file you linked to in issue #1298 is line 3463:
```Chr1    TAIR10  transposable_element_gene       433031  433819  .       -       .       ID=AT1G02228;Note=transposable_element_gene;Name=AT1G02228;Derives_from=AT1TE01405```
where ```AT1TE01405``` is not defined in this gff3 file.

**Comment by risharde** [comment]
Wonderful @dsenalik ! Your code change and the regular expression instructions seemed to work on my side!

`Opening /var/www/html/drupal7/sites/default/files/tripal/users/1/TAIR10_GFF3_genes.gff
Opening temporary cache file: /tmp/TripalGFF3Import_PmGvL6
Step  1 of 27: Caching GFF3 file...                             
Step  2 of 27: Find existing landmarks...                         
Step  3 of 27: Insert new landmarks (if needed)...                
Step  4 of 27: Find missing proteins...                           
Step  5 of 27: Add missing proteins to list of features...        
Step  6 of 27: Find existing features...                          
Step  7 of 27: Clear attributes of existing features...            
Step  8 of 27: Processing 625,650 features...               
Step  9 of 27: Processing 0 feature Names to update...               
Step 10 of 27: Get new feature IDs...                            
Step 11 of 27: Insert locations...                               
Step 12 of 27: Associate parents and children...                 
Step 13 of 27: Calculate child ranks...                          
Step 14 of 27: Add child-parent relationships...                 
Step 15 of 27: Insert properties...                               
Step 16 of 27: Find synonyms (aliases)...                         
Step 17 of 27: Insert new synonyms (aliases)...                  
Step 18 of 27: Insert feature synonyms (aliases)...              
Step 19 of 27: Find cross references...                          
Step 20 of 27: Insert new cross references...                    
Step 21 of 27: Get new cross references IDs...                   
Step 22 of 27: Insert feature cross references...                
Step 23 of 27: Insert feature ontology terms...                  
Step 24 of 27: Insert 'derives_from' relationships...            
Step 25 of 27: Insert Targets...                                 
Step 26 of 27: Associate features with analysis....              
Step 27 of 27: Adding sequences data (Skipped: none available)...

Done.`

Tagging @spficklin as well

**Review by laceysanderson — APPROVED** [review]
Looks like a good clean fix to me :-)
✅  Code Review

Since Rish did a functional review and all looks good there as well, I think this is ready to merge!

**Pull request merged**
