### PR TITLE
Auto search on default views.

### PR DESCRIPTION
**Pull request by spficklin**
Issue #578 

## Type(s) of Change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

Default search views for each Tripal content type were searching automatically.  This is not what the searches did in Tv2.  They should not search unless the user pushes the 'Search' button.  

## Testing?

Pull the branch, clear the cache and navigate to any of the default Tripal content type search views.  They should come up relatively quickly and with no search results.  The button should say 'Search' rather than 'Apply.  

If you have already customized any of these views then the PR won't fix it. It only works for non customized views.

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by spficklin** [comment]
This change is only a few lines... only 1 review needed.

**Comment by almasaeed2010** [comment]
Hello @spficklin 

First of all, the PR works as expected. However, I feel like we've come to expect the behavior of listing a first set of results before searching for those views and we are using that functionality to list some of our content on our tripal sites. It is not hard to create custom views and migrate to them to maintain this functionality, but I wanted to note that this may affect others as well.

Note that this PR does make initial loading of the pages much faster!

@spficklin  @laceysanderson @bradfordcondon any thoughts?

Thanks!

**Comment by spficklin** [comment]
Backwards compatibility for Tv2 was that views did not show results. If we keep this fix and if you want to go back to having the search results listed automatically, it's easy to do by editing the view in the web GUI and changing one parameter.

I can see the value in both ways.  @laceysanderson can you weigh in?

**Comment by laceysanderson** [comment]
As the size of your chado tables increase, the sort on these views will slow them down drastically. We originally changed the views to require input before showing results after some tripal sites began experiencing timeouts loading the searches. It was so bad that Tripal sites with large datasets couldn't even load the searches in order to filter them.

With this in mind, **I think we should keep backwards compatibility with T2 and ensure the default searches require input**. While I prefer a subset of the results being shown, I also want to ensure no Tripal sites experience timeouts on their searches and am unwilling to remove the sort criteria.

**Comment by almasaeed2010** [comment]
I agree. The default Tripal behavior shouldn't cause sites to slow down. 👍 

Thanks!

**Comment by spficklin** [comment]
Thanks @almasaeed2010 and @laceysanderson .  I'm merging.

**Pull request merged**
