### PR TITLE
Fix data leak between publish calls

### LINKED ISSUE #1716: Trying to publish 2+ content types in the same call to the Tripal job launcher fails
### Tripal Version

4.x

### Drupal Version

10.1.x-dev

### PostgreSQL Version

13

### PHP Version

8.2

### General Description

**This one is hard to describe generally so look at the steps to reproduce to get a better idea.**

I'm seeing confusing but repeatable errors when publishing content BUT ONLY if I get impatient and submit 2+ publishing jobs before running them.

## Single publish job per call to job launcher works
1. Run tripal jobs to see that the queue is empty.
2. Go to Admin > Tripal > Content > Publish and choose a random content type with unpublished data.
3. Immediately run the tripal job to complete the publishing and then confirm.
4. Repeat above steps exactly and confirm all general content types publish perfectly.

## When multiple publish jobs are in the queue, the second one fails.
**From a fresh install of Tripal or a fresh docker container**
1. Run tripal jobs to see that the queue is empty.
2. Go to Admin > Tripal > Content > Publish and choose a random content type with unpublished data.
3. WITHOUT RUNNING THE JOB LAUNCHER, repeat step 2 for another content type.
4. Now run the tripal jobs and confirm you see a big error and the second content type, regardless of what you chose, failed because it tried to publish data from fields for the first content type.

### Error messages

The following error message was obtained following the steps to reproduce **when multiple publish jobs are in the queue, the second one fails.**

Content types chosen: 1) contact, 2) project.

```
tripal-4x on  4.x via 🐳 desktop-linux via 🐘 v8.1.6 
❯ docker exec -it $containerName drush tripal:trp-run-jobs --username=drupaladmin

2023-12-18 18:21:31
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2023-12-18 18:21:31: Job ID 3.
2023-12-18 18:21:31: Calling: tripal_publish(contact, chado_storage, Array)
Step  1 of 6: Find matching records... 
 [notice] Step  1 of 6: Find matching records... 
Step  2 of 6: Generate page titles...
 [notice] Step  2 of 6: Generate page titles...
Step  3 of 6: Find existing published entities...
 [notice] Step  3 of 6: Find existing published entities...
Step  4 of 6: Publishing 7 new entities...
 [notice] Step  4 of 6: Publishing 7 new entities...
Step  5 of 6: Find IDs of entities...
 [notice] Step  5 of 6: Find IDs of entities...
Step  6 of 6: Add field items to published entities...
 [notice] Step  6 of 6: Add field items to published entities...
  Checking for published items for the field: contact_description...
 [notice]   Checking for published items for the field: contact_description...
  Publishing items 7 for field: contact_description...
 [notice]   Publishing items 7 for field: contact_description...
  Checking for published items for the field: contact_name...
 [notice]   Checking for published items for the field: contact_name...
  Publishing items 7 for field: contact_name...
 [notice]   Publishing items 7 for field: contact_name...
  Checking for published items for the field: contact_type...
 [notice]   Checking for published items for the field: contact_type...
  Publishing items 7 for field: contact_type...
 [notice]   Publishing items 7 for field: contact_type...
Published 7 new entities, and 21 field values.
 [notice] Published 7 new entities, and 21 field values.
Done
 [notice] Done
2023-12-18 18:21:32: Job ID 4.
2023-12-18 18:21:32: Calling: tripal_publish(project, chado_storage, Array)
Step  1 of 6: Find matching records... 
 [notice] Step  1 of 6: Find matching records... 
Step  2 of 6: Generate page titles...
 [notice] Step  2 of 6: Generate page titles...
Step  3 of 6: Find existing published entities...
 [notice] Step  3 of 6: Find existing published entities...
Step  4 of 6: Publishing 2 new entities...
 [notice] Step  4 of 6: Publishing 2 new entities...
Step  5 of 6: Find IDs of entities...
 [notice] Step  5 of 6: Find IDs of entities...
Step  6 of 6: Add field items to published entities...
 [notice] Step  6 of 6: Add field items to published entities...
WARNING:   The following fields are not supported by publish at this time: project_analysis, project_contact
 [warning] WARNING:   The following fields are not supported by publish at this time: project_analysis, project_contact
[site http://default] [TRIPAL] WARNING:   The following fields are not supported by publish at this time: project_analysis, project_contact
  Checking for published items for the field: contact_description...
 [notice]   Checking for published items for the field: contact_description...
  Publishing items 2 for field: contact_description...
 [notice]   Publishing items 2 for field: contact_description...
 [warning] Undefined array key "contact_description" TripalPublish.php:702
 [error]  TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in array_keys() (line 702 of /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php) #0 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php(702): array_keys(NULL)
#1 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php(869): Drupal\tripal\Services\TripalPublish->insertFieldItems('contact_descrip...', Array, Array, Array, Array)
#2 /var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.publish.api.php(35): Drupal\tripal\Services\TripalPublish->publish()
#3 [internal function]: tripal_publish('project', 'chado_storage', Array, Object(Drupal\tripal\Services\TripalJob))
#4 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalJob.php(366): call_user_func_array('tripal_publish', Array)
#5 /var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.jobs.api.php(443): Drupal\tripal\Services\TripalJob->run()
#6 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Commands/TripalCommands.php(77): tripal_launch_job(0, '4', -1, 0)
#7 [internal function]: Drupal\tripal\Commands\TripalCommands->runJobs(Array)
#8 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array(Array, Array)
#9 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /var/www/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /var/www/drupal/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/drupal/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/drupal/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/drupal/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#19 /var/www/drupal/vendor/drush/drush/drush(4): require('/var/www/drupal...')
#20 {main}. 
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php on line 702 #0 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php(702): array_keys(NULL)
#1 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php(869): Drupal\tripal\Services\TripalPublish->insertFieldItems('contact_descrip...', Array, Array, Array, Array)
#2 /var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.publish.api.php(35): Drupal\tripal\Services\TripalPublish->publish()
#3 [internal function]: tripal_publish('project', 'chado_storage', Array, Object(Drupal\tripal\Services\TripalJob))
#4 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalJob.php(366): call_user_func_array('tripal_publish', Array)
#5 /var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.jobs.api.php(443): Drupal\tripal\Services\TripalJob->run()
#6 /var/www/drupal/web/modules/contrib/tripal/tripal/src/Commands/TripalCommands.php(77): tripal_launch_job(0, '4', -1, 0)
#7 [internal function]: Drupal\tripal\Commands\TripalCommands->runJobs(Array)
#8 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array(Array, Array)
#9 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /var/www/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /var/www/drupal/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/drupal/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/drupal/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/drupal/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#19 /var/www/drupal/vendor/drush/drush/drush(4): require('/var/www/drupal...')
#20 {main}
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in array_keys() (line 702 of /var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalPublish.php).
 [warning] Drush command terminated abnormally.
```

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task

## Description

This PR fixes issues when you run two publish jobs in the same tripal job. Specifically, when you publish two content types in the same Tripal job, the values from the first publish are leaked into the second publish.

I believe this is happening due to some unwritten Drupal rule in how the TripalPublish service is written. I think it's related to the fact that this service uses an init() method to setup everything rather then typical dependency injection with a constructor... but I originally got so caught up in writing a test to demonstrate the problem that I couldn't get my brain to move on to finding the fix.

Luckily, after posting this as a draft PR and asking for help, @dsenalik realized that we could just reset the leaked values in the init() 😅 which is a really clean solution. It may not be ideal and we may run into other issues with this service in the future... but based on my understanding of what is happening, I do think it is a good, reliable fix :-) And I don't know what the ideal fix is so I say we go with this! 🤪 

### What exactly does this PR do?

1. Updates the TripalPublish::init() and other variables to ensure they are reset on subsequent runs of this service.
2. Creates two simple tests that actually run the publish: these were failing before fix no. 1 and are now working. They are not ideal and do not have as many assertions as I would like but they will help us catch situations where the publish job straight up fails so they are worth keeping.
3. Creates a new testing helper method to help setup content types with fields based on the YAML. This replaces the current process where you have to first setup the content type and then attach the fields in the test. Plus it ensures the content type you are testing has all the default fields.
 
## Testing?

**Setup Testing environment**
1. Create a fresh site/docker
2. Use Drush php:cli or devel php code to add records to Chado. The following is how I do this for Organism + Contacts. Alternatively you could load a GFF3 file.
```php
$connection = \Drupal::service('tripal_chado.database');
for ($i=1; $i <= 10; $i++) {
  $species = 'databasica' . uniqid();
  $infra_name = 'postgresquelus' . $i; 
  $connection->insert('1:organism')
    ->fields([
      'genus' => 'Tripalus', 
      'species' => $species, 
      'infraspecific_name' => $infra_name, 
      'type_id' => 500
    ])->execute();
}
for ($i=1; $i <= 5; $i++) {
  $name = 'Tripal' . uniqid() . ' collaborator #' . $i;
  $description = md5(mt_rand()).' '.md5(mt_rand());
  $connection->insert('1:contact')
    ->fields([
      'name' => $name, 
      'description' => $description, 
      'type_id' => 500
    ])->execute();
}
for ($i=1; $i <= 15; $i++) {
  $name = 'Project TestingPublish' . uniqid() . ' interation #' . $i;
  $description = md5(mt_rand()).' '.md5(mt_rand());
  $connection->insert('1:project')
    ->fields([
      'name' => $name, 
      'description' => $description, 
    ])->execute();
}
```

**Single publish job per call to job launcher works**

1. Run tripal jobs to see that the queue is empty.
4. Go to Admin > Tripal > Content > Publish and choose a random content type with unpublished data. If you setup as I did above then you can use "contact".
5. Immediately run the tripal job to complete the publishing and then confirm.
6. Repeat above steps exactly and confirm all general content types publish perfectly.

**When multiple publish jobs are in the queue, the second one fails.**

From a fresh install of Tripal or a fresh docker container

1. Run tripal jobs to see that the queue is empty.
3. Go to Admin > Tripal > Content > Publish and choose a random content type with unpublished data. If you setup as I did above, then you can use "organism".
4. WITHOUT RUNNING THE JOB LAUNCHER, repeat step 2 for another content type. If you setup as I did above then you can use "project".
5. Now run the tripal jobs and confirm you see a big error and the second content type, regardless of what you chose, failed because it tried to publish data from fields for the first content type.

### CODE REVIEW

**Comment by dsenalik** [comment]
I think what is happening is that some class variables retain their values from one job to the next.
I don't understand why, but a simple fix is to just reinitialize them all in the init() function.
`tripal/src/api/tripal.publish.api.php` calls this like so:
```
    $publish = \Drupal::service('tripal.publish');
...
    $publish->init($bundle, $datastore, $options, $job);
    $publish->publish();
```

So commit https://github.com/tripal/tripal/pull/1841/commits/256956ce16a889b3b04c94bde936a1c91cbfc931 fixes this, you can run two consecutive publish jobs now.

To be decided is if we want to be idealistic and work on and finish the tests, or accept this change and work on other stuff.

**Comment by laceysanderson** [comment]
I just ran through a manual test again and this is working beautifully! As such, I'm opening it up for review. Thanks for the help @dsenalik ❤️

**Comment by pdtouch** [comment]
I tested both Single and Multiple publish with both the Main Tripal 4 and the tv4g1-issue1716-dataLeakBetweenPublishCalls branches and I notice there is no error message with the tv4g1-issue1716-dataLeakBetweenPublishCalls branch when using Single or Multiple content publications. There is no data leak between publish calls in the tv4g1-issue1716-dataLeakBetweenPublishCalls branch while the error is visible with current Tripal 4 main branch.

**Comment by laceysanderson** [comment]
Thanks @pdtouch for the review! That means this is ready to merge!

**Pull request merged**
