### PR TITLE
Update workflow to automatically build docker

### LINKED ISSUE #1420: Docker is not being automatically built since we moved back to this repo.
# Core Tripal 4 Development Task

## Branch Name: tv4g0-issue1420-fixDockerBuild

As mentioned in the title, our docker is no longer being automatically built when we merge to 4.x. This is due to the name change of the branch and may be affecting other workflows.

Also, we will want to add more docker tags to help extension modules develop good testing grids.

### PR DESCRIPTION
**Pull request by laceysanderson**
# Bug Fix

Issue #1420 

## Description
This PR fixes two things:

1. When we switched back to tripal/tripal the main branch name changed from 9.x-4.x to just 4.x. This change needed to be reflected in the workflow
2. When I started adding automated testing to extension modules, not enough images were being build to test php / drupal versions effectively. This PR adds additional labels + tags to allow extension modules to pull images.

## Testing?
You only need to check that the workflows completed successfully and that [docker hub](https://hub.docker.com/r/tripalproject/tripaldocker/tags) has been updated.

image

### CODE REVIEW

**Comment by dsenalik** [comment]
I confirm that the tests have passed (except drupal 10 of course), I even did ```docker pull tripalproject/tripaldocker:drupal9.4.x-dev-php8.1-pgsql13``` and confirm that the image downloaded successfully.

But what about the "This branch is out-of-date with the base branch"?

edit: I also confirm that the container I downloaded has changes incorporated from this pull request.

**Review by dsenalik — APPROVED** [review]
Seems good to me, docker image was created

**Comment by spficklin** [comment]
Thanks @dsenalik .  Thanks @laceysanderson I'll merge!

**Comment by laceysanderson** [comment]
Thank you for the review and merge! <3

**Pull request merged**
