### PR TITLE
756 consolidate docs

### PR DESCRIPTION
**Pull request by bradfordcondon**
# Documentation

Issue #756

## Description

Markdown documentation was rolled into the Readthedocs.  Those files (testing , contributing, rtd build, governance guidelines) now just like to the contributing section of the docs.  This keeps the docs DRYer and all in one place.

Docs are all currently in a "contributing" section in the dev's guide. I also played having it as an ew root alongside user/dev guide, so interested in feedback on that.

Note also that I've made general updates and typo fixes to the contributing guide, which i think was sort of a rough draft anyway.  Maybe we can more thoroughly revisit it at PAG.

## Screenshots (if appropriate):

screen shot 2018-11-20 at 11 03 59 am

### CODE REVIEW

**Comment by spficklin** [comment]
Looks good! I have some suggestions:

1. Rename the section "Contributing to Tripal" to "Contributing to Tripal Core Code" so folks know it's clear we are talking about the core code and not just being a contributing member of the Tripal community.
2. Can we split the Unit Test page into two different pages? One for general Unit Testing development and another for rules specific to Tripal core contributions?  The former could go into a separate section outside of the "Contributing to Tripal"
3. I think the "General Project Management" might confuse people as it's really the rules the PMC follows, right?  Users who want to contribute can't tag issues.

**Comment by spficklin** [comment]
Oops. I accidentally made a commit when I meant to make it as a suggestion for you to review @bradfordcondon

**Comment by spficklin** [comment]
@bradfordcondon you'll have to show me how to add suggested commits inline to the PR.  I made some changes that I committed to the branch in line with my suggestions if you want to take a look.

**Comment by bradfordcondon** [comment]
i dont mind, you can commit.


to suggest, click the "plus file" button in the middle (see screenshot).


its also just simple markdown: put the new line fro the line you will replace in

````suggestion` (hard to demonstrate markdown in markdown...)

screen shot 2018-11-20 at 9 10 22 pm

**Review by laceysanderson — APPROVED** [review]
Just made a few fixes to bullet indents and fixed some broken links.

Other then that, looks good 👍

**Comment by bradfordcondon** [comment]
thank you!

@spficklin did you make all the changes you wanted to?

**Comment by bradfordcondon** [comment]
@spficklin did you make all the changes you want or do you have further suggestions?

You asked me to split the unit testing page.  I removed the more "instructive" parts of it, buti n general I don't want it to be too barebones of a guideline page, since then people will be left wondering "you want me to test quietly.  how do i do that?"

I'm open to further work on it, but im hesitant to fully split the guide.

**Comment by spficklin** [comment]
@bradfordcondon I have no further suggestions for edits so I merged.  Thanks.

**Comment by bradfordcondon** [comment]
great, thank you both for the reviews!

**Pull request merged**
