### PR TITLE
Added both modules: TCP and CD to list

### PR DESCRIPTION
**Pull request by risharde**
Hi Lacey, this is an updated version again
Please let me know how you would like me to submit the list concerning the badge requirements. Can I just send that over email?

#

Issue #

### CODE REVIEW

**Comment by laceysanderson** [comment]
@risharde the updated descriptions look 👌 Ideally the badge requirements list would be as a comment in this issue (one per module). Thanks!

**Comment by risharde** [comment]
TCP

Bronze:
Has a public release. |  Yes
Should install on a Tripal site appropriate for the versions it supports. |  Yes
Defines any custom tables or materialized views in the install file (if applicable). |  Not applicable
Adds any needed controlled vocabulary terms in the install file (Tripal3). |  Yes in spirit
Provides Installation and admin instructions README.md (or RTD). |  Yes
Has a license (distributed with module). | Yes

Silver:
Follows basic Drupal Coding standards; specifically, code format and API documentation. |  Yes
Uses Tripal API functions. Specifically, it should use the Chado Query API for querying chado (if using chado as the storage system). |  Yes
Tripal Jobs API for long running processes. |  Not applicable
TripalField class to add data to pages (Tripal3). |  Not applicable
Provides ways to customize the module (e.g. drush options, field/formatter settings, admin UI). |  Yes
Latest releases should follow Drupal naming best practices. e.g. first release for Drupal 7 should be: 7.x-1.x. | Yes

**Comment by risharde** [comment]
Colleagues Directory (CD)

Bronze:
Has a public release. |  Yes
Should install on a Tripal site appropriate for the versions it supports. |  Yes
Defines any custom tables or materialized views in the install file (if applicable). |  Not applicable
Adds any needed controlled vocabulary terms in the install file (Tripal3). |  Not applicable
Provides Installation and admin instructions README.md (or RTD). |  Yes
Has a license (distributed with module). | Yes

Silver:
Follows basic Drupal Coding standards; specifically, code format and API documentation. |  Yes
Uses Tripal API functions. Specifically, it should use the Chado Query API for querying chado (if using chado as the storage system). |  Yes
Tripal Jobs API for long running processes. |  Not applicable
TripalField class to add data to pages (Tripal3). |  Not applicable
Provides ways to customize the module (e.g. drush options, field/formatter settings, admin UI). |  Yes
Latest releases should follow Drupal naming best practices. e.g. first release for Drupal 7 should be: 7.x-1.x. | Yes

**Comment by bradfordcondon** [comment]
I might suggest separating each addition into its own PR?  this would make it easier for us to review.

for Tripal Contact Profile:
Looks like you meet the silver criteria to me.  I would suggest getting rid of your `tripalFields` and `fields.inc` files (https://gitlab.com/TreeGenes/tripal_contact_profile/blob/master/includes/tripal_contact_profile.fields.inc)  as I dont think these are ever used (or at least those fields would never attach in that file).

**Comment by spficklin** [comment]
Hi all if there are no other suggestions specific to meeting requirements I'm going to merge this in.

**Comment by laceysanderson** [comment]
Hi @spficklin, we still haven't verified the Colleagues Directory (CD) module, although it looks like the Tripal Contact Profile module is a go. I believe we should hold off on merging...

**Comment by spficklin** [comment]
Okay @risharde if you want to do as @bradfordcondon suggests and issue a separate PR for the Tripal Contact Profile then we can merge that one in while we wait on the other.

**Comment by spficklin** [comment]
Hi @risharde this PR is getting quite old and we are waiting on input from you for questions asked by @laceysanderson.  Should we keep this open for you?  If not, it's been here a bit too long and we should close it out and let you resubmit again later when things are ready.

**Comment by spficklin** [comment]
Hi @risharde I'm going to close this out just because it's sat here so long. Please resubmit when you are ready.

**Pull request closed without merging**
