### PR TITLE
Support drupal fields by adding a DrupalSQLStorage implementation

### PR DESCRIPTION
**Pull request by laceysanderson**
Issue #1611 
Previous PR #1612 

# Tripal Version: 4

# Description

This PR adds an implementation of TripalStorage called DrupalSqlStorage which is focused on providing support for Tripal fields using the Drupal storage backend. Tbh DrupalSqlStorage doesn't actually do anything but rather stands in as a placeholder in case we need more specialized functionality at a later date. It's presence does allow us to create Tripal fields and specify the storage as drupal_sql_storage and then TripalStorage will be happy :-) and the referenced bug is solved!

I also added in a lot of automated testing for Tripal Storage as it seemed as good a time as any and wasn't too much work :-)

### Small Bugs found during testing and fixed

- PropertyStorageBase did not check that required values were actually provided.
- TripalStorageBase::addFieldDefinition() needlessly assigned an array the first time a field was added and then promptly overrode it with the definition
- TripalStorageUpdateException was never used so I removed it.
- VarCharStoragePropertyType did not ensure the max size was an int. This allowed people to accidentally pass in the storage settings instead 🙈 
- add/get/remove Types functionality should have been in TripalStorageBase.
- An error should be thrown if a field type is added without storage indicated.

## Testing?

1. Create a fresh docker image + container based on this branch ([see these instructions if needed](https://tripaldoc.readthedocs.io/en/latest/contributing/docker-for-testing.html#testing-an-unmerged-pull-request)).
2. Copy the following field class files into the tripal/src/Plugin/Field/FieldType, FieldWidget and FieldFormatter folders and replace `.txt` with `.php`: 
[TripalExampleSimpleStringTypeItem.txt](https://github.com/tripal/tripal/files/12528965/TripalExampleSimpleStringTypeItem.txt), [TripalExampleSimpleStringWidget.txt](https://github.com/tripal/tripal/files/12388874/TripalExampleSimpleStringWidget.txt),  [TripalExampleSimpleStringFormatter.txt](https://github.com/tripal/tripal/files/12388875/TripalExampleSimpleStringFormatter.txt)
3. Rebuild cache `drush cr`
4. Go to Tripal > Page Structure > Organism > Manage Fields and click on "+ Create a new field"
5. Select "Tripal Example Simple String Field Type" from the "Add a new field" drop-down. Enter a label for the field and click "Save and Continue".
6. Use the default field settings and click Save. Set a Term and click Save.
7. Now create an organism by going to Admin > Tripal > Content and clicking "Add Tripal Content". This branch should show you a form element for the new field you added with no errors. Fill out this field and all required fields and click save.
8. The view page should show the value of the field just as you entered it.
9. Edit the page and change the field value then click save. It should be updated as expected with no errors.

### CODE REVIEW

**Comment by dsenalik** [comment]
I built a docker with drupal 10.1 and PHP 8.2
`n=1611`
`docker build --tag=tripaldocker:testing-$n --build-arg drupalversion="10.1.x-dev" --build-arg chadoschema='testchado' --file tripaldocker/Dockerfile-php8.2-pgsql13 ./`

I added `drush cr` to your testing procedure as it is necessary to see the new field

### Unfortunately so far nothing is showing up, it appears to not save what I enter
Example1-form

Output is empty
Example1-formatter

### The entered value did not get stored in the db table
```
sitedb=> select * from public.tripal_entity__field_example1;
  bundle  | deleted | entity_id | revision_id | langcode | delta | field_example1_value 
----------+---------+-----------+-------------+----------+-------+----------------------
 organism |       0 |         1 |           1 | und      |     0 | 
(1 row)
```
I will update if I figure out why...

### Similar results with cardinality unlimited:
```
sitedb=> select * from public.tripal_entity__field_exampleunlimited ;
  bundle  | deleted | entity_id | revision_id | langcode | delta | field_exampleunlimited_value 
----------+---------+-----------+-------------+----------+-------+------------------------------
 organism |       0 |         1 |           1 | und      |     0 | 
 organism |       0 |         1 |           1 | und      |     1 | 
(2 rows)
```

### Running tests locally shows no errors
`docker exec --workdir=/var/www/drupal9/web/modules/contrib/tripal $n phpunit --group 'TripalStorage' --debug &> /tmp/1611.log &`
...
no errors
`OK (8 tests, 285 assertions)`

###  updateValues() is getting the data
In `tripal/src/Plugin/TripalStorage/DrupalSqlStorage.php` the `updateValues()` function is indeed receiving the data from the form. Where does it go...
updateValues

### Just to test that load works
```
sitedb=> update public.tripal_entity__field_example1 set field_example1_value = 'Load works okay' where entity_id=1;
UPDATE 1
sitedb=> select * from public.tripal_entity__field_example1;
  bundle  | deleted | entity_id | revision_id | langcode | delta | field_example1_value 
----------+---------+-----------+-------------+----------+-------+----------------------
 organism |       0 |         1 |           1 | und      |     0 | Load works okay
(1 row)
```
...
`drush cr`
loadworksokay
if I edit and save, the value disappears again

### Cardinality unlimited is adding a row after every edit and save
unlimited-growing

**Comment by laceysanderson** [comment]
Works now! @dsenalik it's ready for re-testing. 

FYI. The problem was that Tripal assumes that all properties of a field will have a drupal_store storage setting. This is field controlled and if not set the default is FALSE...

Now Drupal SQL Storage jumps in when property types are added to the storage backend and sets drupal_store for all properties of fields using this storage backend.

**Review by dsenalik — APPROVED** [review]
Tested with a new docker Drupal 10.1 PHP 8.2
Works perfectly now 🎉
Tested with cardinality 1 and with unlimited.
drupal_storage

```
sitedb=> select * from public.tripal_entity__field_example_simple_string;
  bundle  | deleted | entity_id | revision_id | langcode | delta |    field_example_simple_string_value    
----------+---------+-----------+-------------+----------+-------+-----------------------------------------
 organism |       0 |         1 |           1 | und      |     0 | Test Cardinality Unlimited Record One
 organism |       0 |         1 |           1 | und      |     1 | Test Cardinality Unlimited Record Two
 organism |       0 |         1 |           1 | und      |     2 | Test Cardinality Unlimited Record Three
(3 rows)

sitedb=> select * from public.tripal_entity__field_cardinality_1;        
  bundle  | deleted | entity_id | revision_id | langcode | delta | field_cardinality_1_value 
----------+---------+-----------+-------------+----------+-------+---------------------------
 organism |       0 |         1 |           1 | und      |     0 | Test Cardinality 1
(1 row)
```

Then edit and clear the second unlimited record and the cardinality 1 record. They are removed from the db tables and no longer displayed (as expected).
drupal_storage_2
```
sitedb=> select * from public.tripal_entity__field_example_simple_string;
  bundle  | deleted | entity_id | revision_id | langcode | delta |    field_example_simple_string_value    
----------+---------+-----------+-------------+----------+-------+-----------------------------------------
 organism |       0 |         1 |           1 | und      |     0 | Test Cardinality Unlimited Record One
 organism |       0 |         1 |           1 | und      |     1 | Test Cardinality Unlimited Record Three
(2 rows)

sitedb=> select * from public.tripal_entity__field_cardinality_1;
 bundle | deleted | entity_id | revision_id | langcode | delta | field_cardinality_1_value 
--------+---------+-----------+-------------+----------+-------+---------------------------
(0 rows)
```

**Comment by spficklin** [comment]
Yeah!

**Pull request merged**
