### PR TITLE
changed chado_bundle.type_id to a bigint

### PR DESCRIPTION
**Pull request by spficklin**
Issue #371 

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

The chado_bundle.type_id field is of type varchar. It should be of type bigint because it's housing cvterm_ids from the Chado cvterm table.  See issue #371 .

## Testing?

Just take a look at the code, then pull the branch and run the following command:

```
drush php-eval 'module_load_include("install", "tripal_chado", "tripal_chado"); tripal_chado_update_7329()
```
The command above is used instead of a "drush updatedb" because you probably don't want to run all of the updates except on the 7.x-3.x branch because there are several in different PRs and you might get them out of order.

After you run the update, examine the chado_bundle table.  The type_id field should be a bigint.  Also, you should still be able to create new content types and loading pages, etc should continue to work just fine.

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
hi @spficklin it looks like this PR breaks the tripal_chado install: see the below error from the travis build

```

The command "drush en -y tripal tripal_chado tripal_chado_views tripal_ds tripal_ws" exited with 1.
1.26s$ drush eval "module_load_include('inc', 'tripal_chado', 'includes/tripal_chado.install'); tripal_chado_load_drush_submit('Install Chado v1.3');"
WD menu: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:    [error]
relation "tripal_custom_tables" does not exist
LINE 1: SELECT table_name FROM tripal_custom_tables
                               ^: SELECT table_name FROM
{tripal_custom_tables}; Array
(
)
 in chado_get_table_names() (line 495 of
/home/travis/build/tripal/drupal/sites/all/modules/tripal/tripal_chado/api/tripal_chado.schema.api.inc).
Job 'Install Chado v1.3' submitted.                                  [status]
```


edit: after looking at the logs more carefully and comparing your PR, no, i dont think its your pR's fault.  Looks like tripal 2 didn't create the `tripal_custom_tables` table?

I'm goign to rerun just to check.

**Comment by spficklin** [comment]
Okay, the failing CI is now fixed!  It's ready for review again.

**Comment by chunhuaicheng** [comment]
I tested this PR and it worked fine for me. 'type_id' changed to bigint and it did not create any problem on my site.

**Comment by spficklin** [comment]
Awesome! thanks @chunhuaicheng

**Pull request merged**
