### PR TITLE
Tripal 4 port of tripal 3 chado_get_organism_id_from_scientific_name()

### LINKED ISSUE #1536: Port pull #1328 to Tripal 4
# Core Tripal 4 Development Task

## Branch Name: tv4g0-issue1536-chado_get_organism_id_from_scientific_name

Merge the new API function `chado_get_organism_id_from_scientific_name()` from Tripal 3 pull request #1328

### PR DESCRIPTION
**Pull request by dsenalik**
# Tripal 4 Core Dev Task

## Description
Merge the new API function `chado_get_organism_id_from_scientific_name()` from Tripal 3 pull request #1328

Add automated testing for this new function.

I noted while I was in here that the function `chado_autocomplete_organism()` is currently nonfunctional because for Drupal 8+ `drupal_json_output()` is removed in favor of `Symfony\Component\HttpFoundation\JsonResponse`. And also that it does not support infraspecific nomenclature.

Replaced deprecated `tripal_report_error()`, see issue #1545

## Testing?
Nothing in Tripal 4 uses this yet. Unit tests have been added, or for manual testing you can test pretty much everything added in the devel module php window with:
```
$s = 'Tripalus domesticus subsp. chadoii';  // Try both fake and real organism names here.
$o = chado_get_organism(['scientific_name' => $s], []);
var_dump($o);  // Returns NULL if it doesn't exist, organism object if it does.
```

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
I just built an D10.0, PHP 8.1 image with only `testchado` chado schema and tested using drush php-cli and it looks like it's having trouble with schema name 😬 

```
docker build --tag=tripaldocker:tripal1537 --build-arg drupalversion="10.0.x-dev" --build-arg chadoschema=testchado --file tripaldocker/Dockerfile-php8.1-pgsql13 ./
docker run --publish=80:80 --name=tripal1537 -tid --volume=`pwd`:/var/www/drupal9/web/modules/contrib/tripal tripaldocker:tripal1537
docker exec -it tripal1537 service postgresql restart
```

Created 3 organisms for testing through the UI:

- Tripalus databasica subsp. postgresqlulus
- Tripalus databasica subsp. chadoii
- Tripalus domesticus

```php
docker exec -it tripal1537 drush php:cli
Psy Shell v0.11.18 (PHP 8.1.19 — cli) by Justin Hileman
Tripal 4 on Drupal 9 DEVELOPMENT (Drupal 10.0.10-dev)
> chado_get_organism(['scientific_name' => 'Tripalus databasica subsp. chadoii']);
 [error]  Schema must already exist and be in the same database as your
        Drupal installation. 
 [error]  Schema must already exist and be in the same database as your
        Drupal installation. 

   Drupal\Core\Database\DatabaseExceptionWrapper  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "organism" does not exist
LINE 1: ...n_name, infraspecific_name, type_id, comment FROM "organism"...
                                                             ^: SELECT organism_id, abbreviation, genus, species, common_name, infraspecific_name, type_id, comment FROM "organism" WHERE organism_id = :organism_id0; Array
(
    [:organism_id0] => 2
).

> chado_get_organism(['scientific_name' => 'Tripalus databasica subsp. chadoii']);

   Drupal\Core\Database\DatabaseExceptionWrapper  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "chado.organism" does not exist
LINE 1: SELECT organism_id FROM "chado"."organism" WHERE LOWER(genus...
                                ^: SELECT organism_id FROM "chado"."organism" WHERE LOWER(genus) = :genus AND LOWER(species) = :species AND ( type_id = (SELECT cvterm_id FROM "chado"."cvterm" WHERE LOWER(name) = :infraspecific_type AND cv_id = (SELECT cv_id FROM "chado"."cv" WHERE name = :taxonomic_rank))) AND LOWER(infraspecific_name) = :infraspecific_name; Array
(
    [:genus] => tripalus
    [:species] => databasica
    [:infraspecific_type] => subspecies
    [:taxonomic_rank] => taxonomic_rank
    [:infraspecific_name] => chadoii
).

> chado_get_organism(['scientific_name' => 'Tripalus databasica']);

   Drupal\Core\Database\DatabaseExceptionWrapper  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "chado.organism" does not exist
LINE 1: SELECT organism_id FROM "chado"."organism" WHERE LOWER(genus...
                                ^: SELECT organism_id FROM "chado"."organism" WHERE LOWER(genus) = :genus AND LOWER(species) = :species AND ( type_id = (SELECT cvterm_id FROM "chado"."cvterm" WHERE LOWER(name) = :infraspecific_type AND cv_id = (SELECT cv_id FROM "chado"."cv" WHERE name = :taxonomic_rank)) OR type_id IS NULL) AND ( infraspecific_name = '' ) IS NOT FALSE; Array
(
    [:genus] => tripalus
    [:species] => databasica
    [:infraspecific_type] => no_rank
    [:taxonomic_rank] => taxonomic_rank
).
```

**Comment by dsenalik** [comment]
I wonder if this is the same thing as one of the errors we are seeing in the automated tests for 10.1
`1) Drupal\Tests\tripal_chado\Functional\ChadoStorageTest::testChadoStorage
Drupal\tripal\TripalDBX\Exceptions\SchemaException: Invalid or unsupported Chado schema version ''.`

Oh, but you are on 10.0, hmm...

**Comment by dsenalik** [comment]
So in the case of a different chado name, can you see if this works?

`chado_get_organism(['scientific_name' => 'Tripalus databasica subsp. chadoii'], [], 'testchado');`

And if it does, I wonder if there is a better way of setting the default schema for these api functions rather than hard-coding in a default `, $schema_name = 'chado'`. Is there a way to retrieve the name of the "first" schema, the `1:` schema? We could then make the default NULL, and if NULL substitute this schema name.

Would this work to get the default schema name?
```
$connection = \Drupal::service('tripal_chado.database');
$schema = $connection->getSchemaName();
```

**Comment by laceysanderson** [comment]
Yes, confirmed it does work if I provide the correct schema name:
```
docker exec -it tripal1537 drush php:cli
Psy Shell v0.11.18 (PHP 8.1.19 — cli) by Justin Hileman
Tripal 4 on Drupal 9 DEVELOPMENT (Drupal 10.0.10-dev)
> chado_get_organism(['scientific_name' => 'Tripalus databasica subsp. chadoii'], [], 'testchado');
= {#7363
    +"organism_id": "2",
    +"abbreviation": "",
    +"genus": "Tripalus",
    +"species": "databasica",
    +"common_name": "",
    +"infraspecific_name": "chadoii",
    +"type_id": "2866",
    +"comment": "",
    +"expandable_fields": [],
    +"expandable_foreign_keys": [
      "organism.type_id => cvterm",
    ],
    +"expandable_tables": [
      "biomaterial",
      "cell_line",
      "feature",
      "featuremap_organism",
      "library",
      "organism_cvterm",
      "organism_dbxref",
      "organism_pub",
      "organism_relationship",
      "organismprop",
      "phenotype_comparison",
      "phylonode_organism",
      "stock",
    ],
    +"tablename": "organism",
  }
```

For getting the default schema, this is official (albeit undocumented 🙈) way:

```
$schema_name = \Drupal::config('tripal_chado.settings')->get('default_schema');
```

Another things to consider is that chado_get_organism still uses chado_generate_var() 😬 As a community we need to decide if we want to upgrade that? The performance is quite bad for not a lot of gain IMO 🙈  Likely a though for another issue/PR though 🙃

**Comment by dsenalik** [comment]
I am building my own docker like yours for testing, with 'testchado' schema name, so I can work on this properly.

And I agree about the chado_generate_var() being a resource hog. In early May you said that we should be moving away from a function based API and into services for things like this, so maybe that is the time to change how it works.

**Comment by laceysanderson** [comment]
As far as functioning beyond the schema issue:
✅ Able to retrieve the correct organism when there are two differing only by infraspecific name. (i.e. asked for `Tripalus databasica subsp. postgresqlulus` in my tests)
✅ Receive error when trying to retrieve an organism who has an infraspecific name but you didn't specify it. (i.e. asked for `Tripalus databasica` in my tests)
✅ Able to retrieve an organism who doesn't have an infraspecific name (i.e. `Tripalus domesticus` in my tests).

Two interesting points:
- You can add "Tripalus domesticus" and then "Tripalus domesticus subsp. chadoii" with no validation error.
- You cannot add "Tripalus domesticus subsp. chadoii" and then "Tripalus domesticus" as you will get a validation error that an organism with that genus/species already exists.

Also, those functions are still using tripal_report_error() which is deprecated so I see:
```
chado_get_organism(['scientific_name' => 'Tripalus databasica'], [], 'testchado');
 [warning] WARNING: DEPRECATED: the 'tripal_report_error' function will be removed from the API in a future release. Please use the TripalLogger service for logging.
[site http://default] [TRIPAL] WARNING: DEPRECATED: the 'tripal_report_error' function will be removed from the API in a future release. Please use the TripalLogger service for logging.
 [warning] WARNING: DEPRECATED: the 'tripal_log' function will be removed from the API in a future release. Please use the TripalLogger service for logging.
[site http://default] [TRIPAL] WARNING: DEPRECATED: the 'tripal_log' function will be removed from the API in a future release. Please use the TripalLogger service for logging.
[site http://default] [TRIPAL ERROR] [TRIPAL_ORGANISM_API] chado_get_organism: The specified scientific name did not uniquely identify an organism.          You passed in Tripalus databasica.
= null
```
For the second test case above.

**Comment by dsenalik** [comment]
I have created new issues for the two "interesting points"
#1544 Tripal 4 validation error with infraspecific nomenclature
#1545 Tripal 4 tripal_report_error() is deprecated

**Comment by dsenalik** [comment]
There are cases elsewhere with hardcoded chado defaults, _e.g._
`function chado_insert_dbxref($values, $options = [], $schema_name = 'chado')`
so for completeness I will update them all in this pull request.

I also included a new test which detected the original error @laceysanderson reported.

**Review by laceysanderson — APPROVED** [review]
✅ Code review
✅ Automated testing
✅ Manual testing

Thanks @dsenalik ❤️

**Pull request merged**
