### PR TITLE
Fix php notice when creating an entity

### PR DESCRIPTION
**Pull request by almasaeed2010**
Issue #605 

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

This PR removes the undefined `$created_date` variable and replaces it with `time();`

## Testing?

1. once the branch is checked-out, you shouldn't see the errors described in issue #605

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by spficklin — COMMENTED** [review]
I think the fix should be this:

```
$entity->created = create_date;
```
Note the code above this line that initializes the $create_date variable and then does some checks to make changes if need be.

**Comment by almasaeed2010** [comment]
Thanks @spficklin I didn't notice the variable. I updated accordingly.

**Comment by spficklin** [comment]
This is just a one liner and it looks good so only 1 review needed. I'll merge.

**Comment by spficklin** [comment]
Thanks @almasaeed2010

**Pull request merged**
