### PR TITLE
7.x 3.x api docs

### PR DESCRIPTION
**Pull request by shawnawsu**
This update is very large but I've tested to make sure all the basic functions are up and running. It still needs to be reviewed closely though.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
hi all,

i made a PR so that this brnach passes tests:  https://github.com/tripal/tripal/pull/369

However, it sounds like the tests should have passed without this PR after talking with @spficklin.  The test called the old API methods.  for exmaple `tripal_chado_publish_records` should have called `chado_publish_records`.

**Comment by spficklin** [comment]
@bradfordcondon I merged in your PR as those changes needed to happen anyway.

**Comment by spficklin** [comment]
Hi @shawnawsu this looks good to me.  I think you have one more fix that we discussed related to the cvtermpath function naming so I'll wait to merge until you get that in.

**Review by shawnawsu — COMMENTED** [review]
@bradfordcondon I've formatted my code to PSR-2 standards since I couldn't recall drupal coding standards for multiline method arguments. Can you point me towards the standards that caused you to change the formatting of my multiline method arguments so I can bookmark it?

**Comment by bradfordcondon** [comment]
i think you mean @spficklin i only renamed the methods in the tests.

That said: my formatter is A-OK with your multi-line method calls.

Thanks for pinging me though because i see i left my debugging code in my test 🐑

**Comment by shawnawsu** [comment]
You're right, I saw the changes under your pull request and thought it was you, sorry about that. 

Same question to @spficklin then.

**Comment by spficklin** [comment]
Sorry @shawnawsu after looking at the coding standards (link below) my changes appear to just be personal preference.  I will try to stick to making formatting changes from this doc in the future. https://www.drupal.org/docs/develop/standards/coding-standards

**Comment by spficklin** [comment]
But if I make a mistake I will continue to let @bradfordcondon take the blame.

**Comment by spficklin** [comment]
Thanks Shawna for the fixes.

**Pull request merged**
