### PR TITLE
add the cv defaults table that was in the legacy tripal cv

### PR DESCRIPTION
**Pull request by bradfordcondon**
This PR resolves issue #200

### CODE REVIEW

**Comment by shawnawsu** [comment]
Hi Bradford, 

Since this is for a specific module I think the table creation should go in the module's install file. But I'm relatively knew to tripal so @spficklin  please correct me if I am wrong. 

Thanks,
Shawna

**Comment by bradfordcondon** [comment]
if that is the case then you should deprecate `tripal_set_default_cv`  which is in tripal 3 and requires this table.

**Comment by shawnawsu** [comment]
I agree, especially because it's an unused function, but let me confirm with Stephen what his preference is.

**Comment by spficklin** [comment]
We don't want to bring back the CV defaults table for Tripal v3 as we no longer need it.  Can you give an example for why you want it?

**Comment by bradfordcondon** [comment]
I don't even know why you would want to set a default CV, i was just fixing install errors and it looked like this method was still invoked.  If its no longer necessary I'll remove the calls in my modules instead.

**Comment by bradfordcondon** [comment]
I'm closing this PR.  Sounds like the correct fix is to remove `tripal_set_default_cv` instead.

**Pull request closed without merging**
