### PR TITLE
tv3g9 issue1424 Automated testing with newer php versions

### PR DESCRIPTION
**Pull request by dsenalik**
# Bug Fix

## Description
Let's add some newer PHP versions to automated testing, and see how many problems this reveals. I will add 8.0 and 8.1 to match tripal4 current testing versions.

### CODE REVIEW

**Comment by dsenalik** [comment]
There are two problems
```
  Problem 1
    - Root composer.json requires doctrine/instantiator 2.0.* -> satisfiable by doctrine/instantiator[2.0.0].
    - doctrine/instantiator 2.0.0 requires php ^8.1 -> your php version (8.0.28) does not satisfy that requirement.
```
```doctrine/instantiator``` was just updated to 2.0.0 at the end of last year, the first version that will run under PHP8. However it doesn't seem it will run on php 8.0, only  on 8.1. So because of this we could test only under 8.1

```
  Problem 2
    - fzaninotto/faker[v1.7.0, ..., v1.9.2] require php ^5.3.3 || ^7.0 -> your php version (8.0.28) does not satisfy that requirement.
    - statonlab/tripal-test-suite[1.0.0, ..., 1.6.1] require fzaninotto/faker ^1.7 -> satisfiable by fzaninotto/faker[v1.7.0, ..., v1.9.2].
    - Root composer.json requires statonlab/tripal-test-suite 1.* -> satisfiable by statonlab/tripal-test-suite[1.0.0, ..., 1.6.1].
```
```fzaninotto/faker``` hasn't been updated since Dec 2020, but there was a change merged that should let it run with PHP8, but that's not in the latest release. If I grab directly from github it will work.

**Comment by dsenalik** [comment]
I "fixed" ```doctrine/instantiator``` and ```fzaninotto/faker```, I pushed that just so it is documented, but now there are worse dependency problems when I run ```composer update```:
```
  Problem 1
    - phpunit/phpunit-mock-objects[3.0.0, ..., 3.1.3] require doctrine/instantiator ^1.0.2 -> found doctrine/instantiator[1.0.2, ..., 1.5.0] but it conflicts with your root composer.json require (2.0.*).
    - phpunit/phpunit-mock-objects[3.2.1, ..., 3.4.4] require php ^5.6 || ^7.0 -> your php version (8.1.16) does not satisfy that requirement.
    - phpunit/phpunit[5.2.8, ..., 5.7.27] require php ^5.6 || ^7.0 -> your php version (8.1.16) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects[4.0.0, ..., 4.0.4, 5.0.0, ..., 5.0.10] require php ^7.0 -> your php version (8.1.16) does not satisfy that requirement.
    - phpunit/phpunit[6.0.0, ..., 6.5.14] require php ^7.0 -> your php version (8.1.16) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects[6.0.0, ..., 6.1.2] require php ^7.1 -> your php version (8.1.16) does not satisfy that requirement.
    - phpunit/phpunit[7.0.0, ..., 7.5.20] require php ^7.1 -> your php version (8.1.16) does not satisfy that requirement.
    - statonlab/tripal-test-suite[1.0.0, ..., 1.6.1] require phpunit/phpunit ^5 || ^6 || ^7.0 -> satisfiable by phpunit/phpunit[5.0.0, ..., 5.7.27, 6.0.0, ..., 6.5.14, 7.0.0, ..., 7.5.20].
    - phpunit/phpunit[5.1.3, ..., 5.2.7] require phpunit/phpunit-mock-objects >=3.0.5 -> satisfiable by phpunit/phpunit-mock-objects[3.0.5, ..., 3.4.4, 4.0.0, ..., 4.0.4, 5.0.0, ..., 5.0.10, 6.0.0, ..., 6.1.2].
    - phpunit/phpunit[5.0.0, ..., 5.1.2] require phpunit/phpunit-mock-objects >=3.0 -> satisfiable by phpunit/phpunit-mock-objects[3.0.0, ..., 3.4.4, 4.0.0, ..., 4.0.4, 5.0.0, ..., 5.0.10, 6.0.0, ..., 6.1.2].
    - Root composer.json requires statonlab/tripal-test-suite 1.* -> satisfiable by statonlab/tripal-test-suite[1.0.0, ..., 1.6.1].
```

Note that in current automated testing, this is displayed
```
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by dsenalik** [comment]
No tests were ever written for: tripal_bulk_loader, tripal_chado_views, tripal_daemon, or tripal_ds
Not having a directory for these causes an error in newer versions of phpunit, _e.g._
```
PHPUnit 10.0.11 by Sebastian Bergmann and contributors.

Test directory "/var/www/prova/drupal-7.92/sites/all/modules/tripal/tests/tripal_bulk_loader/" not found
```
So delete references to these in ```phpunit.xml```

**Comment by dsenalik** [comment]
Today's notes, will edit with more:
**1.** ```Warning: assertObjectHasAttribute() is deprecated and will be removed in PHPUnit 10.```
replace with ```get_object_vars()``` + ```assertArrayHasKey()``` https://github.com/tripal/tripal/pull/1425/commits/52543a041e31a3b984ee7542992bc7f815e94213 + https://github.com/tripal/tripal/pull/1425/commits/71f98288fec93451eb6ec4faaa13a03786bb85ec
**2.** ```Error: TypeError: Cannot access offset of type string on string``` There is an actual bug in ```tripal_chado/fields/ChadoFieldGetValuesListTest.php``` in ```function generateFakeData()``` looking up ```$column_type``` from ```$schema```., 
need to add ```["fields"]``` https://github.com/tripal/tripal/pull/1425/commits/fbe9993232efc1e7141c917e9deed6b1bf8baa1b
**3.** ```Error: Error: Undefined constant "Tests/Exception"``` + ```Error: Error: Undefined constant "Tests/EXCEPTION"``` 
Change ```EXCEPTION``` or ```Exception``` to ```\Exception::class``` https://github.com/tripal/tripal/pull/1425/commits/e5c3b450fde463bddc32998a52928c7edf0f0b45
**4.** ```The following array should but does not contain our fake value ('5202'): '5202.```
Since phpunit 8 ```assertContains()``` uses strict checking, we are comparing a number to a string so this fails. Use ```(string)``` to fix this. https://github.com/tripal/tripal/pull/1425/commits/b9e97612ddeeceff7b1bb929c120aa69ac79c3d1
**5.** ```Error: Failed asserting that '0' matches expected 99.``` This is from ```tests/tripal_chado/api/TripalChadoPropertyAPITest.php```, same problem as **4** https://github.com/tripal/tripal/pull/1425/commits/309850b7515114532a506d35cbb16216c41c1e26

**Review by laceysanderson — APPROVED** [review]
Thank you for this update @dsenalik! A code review looks great so we are just waiting now for the tests to pass and then this can be merged! 🎉

**Pull request merged**
