### PR TITLE
Issue253

### PR DESCRIPTION
**Pull request by shawnawsu**
The changed in this pull request address issues:

- https://github.com/tripal/tripal/issues/253
- https://github.com/tripal/tripal/issues/188
- https://github.com/tripal/tripal/issues/186

This contains:

- 1 small change to a drush_tripal_trp_set_permissions(), which can be tested by running drush trp-set-permissions and should set all tripal content types to be editable (edit, create, view, delete) by administrators.

- The creation and integration of an EBI lookup function during the OBOImporter run to catch files that do not have default-namespaces and to catch terms referencing other ontologies that are not loaded in chado at time of run. 
        - To test try running the Plana ontology: https://raw.githubusercontent.com/obophenotype/planaria-ontology/master/src/ontology/plana.obo

- An update to the cvtermpathupdate functions when checking for duplicate records. The original db_query was written just like the chado stored procedure which uses cv_id as a testing parameter for dups. However, the cvtermpath_c1  constraint (UNIQUE (subject_id, object_id, type_id, pathdistance)) on the cvtermpath table does not include cv_id so a unique violation was being thrown when two (or more) cv's would try to load the same subject_id, child_id, type_id, pathdistance into cvtermpath. Removing this also results in significantly more rows being added to the cvtermpath table, specifically rows with a pathdistance of zero (http://gmod.org/wiki/Chado_Tables#Table:_cvtermpath). I also cleaned up some formatting.
        -To test load goslim (http://www.geneontology.org/ontology/subsets/goslim_plant.obo) or the full gene ontology on a fresh site.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
i'm testing Plana loading but will probably take 48 hours plus if my past experience is any indication.


Looking at the code itself everything looks good to me.


Note that changes like `-  $tree_path = array();` -> `$tree_path = [];` clutter up the diffs and make it less fun to review.  This is why I advocated for a standardized coding convention in #310 .  I recognize that this array issue is a [special case](https://www.drupal.org/project/coding_standards/issues/2135291): I'll propose we make a singel commit to change all the arrays over in the style issue.

**Review by bradfordcondon — APPROVED** [review]
I was able to load Planaria no problem!  looks good!

**Comment by spficklin** [comment]
@bradfordcondon did you check all items for this pull request?

**Comment by bradfordcondon** [comment]
Just item 2, not 1 or 3 unfortunately.

**Comment by bradfordcondon** [comment]
Hi, I tried loading the Goslim plant ontology linked and got this error (very unhelpful i know :|):

```
drush trp-run-jobs --username=admin --root=/Users/chet/UTK/tripal


2018-03-23 18:07:13
Tripal Job Launcher
Running as user 'admin'
-------------------
2018-03-23 18:07:13: There are 1 jobs queued.
2018-03-23 18:07:13: Calling: tripal_run_importer(15)

Running 'OBO Vocabulary Loader' importer
NOTE: Loading of file is performed using a database transaction.
If it fails or is terminated prematurely then all insertions and
updates are rolled back and will not be found in the database

Downloading URL http://www.geneontology.org/ontology/subsets/goslim_plant.obo, saving to /private/var/folders/p2/25r02fld33qdr02n_gp25_pm0000gn/T/obo_QdVM80
Step 1: Preloading File /private/var/folders/p2/25r02fld33qdr02n_gp25_pm0000gn/T/obo_QdVM80...
This OBO is missing the 'default-namespace' header. It is not possible to determine which vocabulary terms without a 'namespace' key should go.  Instead, those terms will be placed in the 'GO/SUBSETS/GOSLIM_PLANT' vocabulary.
Step 2: Loading type defs...
Step 3: Loading terms...%. Memory: 33,162,128 bytes.
Percent complete: 100.00%. Memory: 33,166,752 bytes.
Done.

Updating the cv_root_mview materialized view...
Done.
Updating the db2cv_mview materialized view...
Done.
Updating cvtermpath table.  This may take a while...
- Loading paths for GO/SUBSETS/GOSLIM_PLANT
- Loading paths for external
- Loading paths for biological_process
- Loading paths for molecular_function
SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
WD tripal_job: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end [error]
of transaction block
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

**Comment by spficklin** [comment]
@bradfordcondon  I just loaded GO Plant Slim and all worked fine, so I merged.  Were you testing on the right branch?  Although now you can test on the 7.x-3.x branch since I merged.

**Comment by bradfordcondon** [comment]
fair enough.  i have nothing to go on with that error...

**Comment by bradfordcondon** [comment]
update_cvtermpath executes with no error, so I think it's fine.

I forgot i changed branches when i retested.  really sorry for hte  confusion.

**Pull request merged**
