### PR TITLE
Creation of content types times out

### PR DESCRIPTION
**Pull request by spficklin**
Issue #533 

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

Sometimes you can get a WSOD when creating new content types. This is because in some cases it must look through all of the properties in a table to create the prop tables.   This PR makes content type creation (via the Drupal interface) a job submission.

One Note, I changed the tripal_create_bundle() function.  It had an $error argument that was meant to be passed in by reference and was set to the error message. Apparently that was an older argument and is no longer used.   We don't normally change API functions but this is so new and I'd rather not lock in an argument that is not used so I thought it was okay to remove that.

## Testing?

1).  Pull the PR
2)  Create a new content type. It should submit a job.
3)  Run the job,
4).  Return to the Content Types page and see that your new content type is available.

## Additional Notes (if any):

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
functionality verified 👍 submitted and run a content creation job.

**Review by bradfordcondon — APPROVED** [review]
looks good to me, thanks @spficklin

**Comment by laceysanderson** [comment]
I hesitate on this one as it feels like it degrades the user experience. I would expect this to be quick and not need a job. Is there any way we can optimize the process rather then put it in a Tripal Job? Or separate the content type creation and the field addition process? The type could be created immediately and the prop fields added via a tripal job?

**Comment by spficklin** [comment]
I get your complaint. I wasn't too thrilled to move it to a job either but I couldn't see another way around it.  I think separating content type creation from field creation would complicate the setup too.  So, either way we're adding an extra step.... :-(

**Comment by laceysanderson** [comment]
My idea wasn't to make the user initiate the field creation step... I figured they would go to `Add Tripal Content Type`, fill out the form, click create. At this point the user would be redirected to their new content type which would have a message at the top saying "Tripal Job submitted to automatically create appropriate fields for this content type based on the data in your site. It is recommended you wait until the job completes before configuring this content type. Check on the progress of this job here." This way they get immediate gratification and we don't risk a WSOD. There's no extra step for them, especially if they setup the daemon. It just causes a hopefully short delay for configuring the content type. Thoughts?

**Comment by spficklin** [comment]
I think in either case the user ends up waiting and the experience is the same... they can't use the content type until a job runs.   I'm not opposed to the suggestion. I'm just not sure the experience is any better.

**Comment by laceysanderson** [comment]
I still really hesitate here. I would like to take a stab at optimizing this process before separating it out into a job but I doubt I would have the time before Friday as I have KnowPulse deadlines to meet this week :-( 

How many properties do you need to have before this becomes a problem? Could it be put off until the next point release? If we move it into a tripal job for 3.0, and I find a way to optimize it later, can we move it back?

**Comment by spficklin** [comment]
So how about this... As part of a stable release I don't think we should have WSOD if we know about it.  So, how about we leave it as a job submission and merge this in.  In the end, if we are able to improve performance we can move it back to not requiring a job and that ends up being an improvement for the end-user.  If we leave as is, and we determine we must use a job, then a future update would have this fix and it would seem to the end-user as a step-down.

**Review by almasaeed2010 — APPROVED** [review]
Confirmed. A job is submitted and succeeds.

Thanks @spficklin

**Comment by bradfordcondon** [comment]
we have 2 approvals (thanks @almasaeed2010 ) and it sounds like @laceysanderson is fine with this approach with improvement down the road.

Merging, thanks @spficklin

**Comment by spficklin** [comment]
Thanks @almasaeed2010 @bradfordcondon and @laceysanderson !

**Pull request merged**
