### PR TITLE
Tripal 4 ChadoContactDefault field

### PR DESCRIPTION
**Pull request by dsenalik**
# Tripal 4 Core Dev Task

## Description

This is the initial implementation of the ChadoContactDefault field.

There are only two tables with a `contact_id` column that will be able to use this field:
  * `stockcollection` (but is not a default content type)
  * `study`

and in addition the `arraydesign` table has a `manufacturer_id` which maps to the contact table

Note that before this PR, we can't create a study because `contact_id` has a NOT NULL constraint in the study table. This PR includes an update to the YAML as described in issue #1550 so that it is easy to test.

## Dependency
As of https://github.com/tripal/tripal/pull/1599/commits/591868140958fe6776e885856bd8cf979956e629, this PR is dependent on pull #1604. ~It cannot be merged until that one is merged.~ it has been merged

## Testing?
I will test on both the Study and Array Design content types. Currently you can't create a study because the `contact_id` is NOT NULL. This new field will fix that! Similar problem for Array Design.

1. Create two contact records, one a `Person (TCONTACT:0000003)` and one a `Company (NCIT:C54131)` (though types do not really matter)
contacts

2. Now create a study, and specify the person contact.
study1

3. It should appear similar to this
study2

4. Create an array design, and specify the company contact as the "Manufacturer". "Platform Type" is also a required field, just enter any random CV term there, I used "DNA".
ad1

5. Content should be saved and appear something like this
ad2

If you happen to notice that that "Platform Type" is blank, that is actually issue #1398 but not relevant to this PR

### CODE REVIEW

**Comment by dsenalik** [comment]
I am hoping this field is done.
* the field is added to the two content types in the YAML with https://github.com/tripal/tripal/pull/1599/commits/f823b9ded70518f7489870b82c8941eac89813e5 , manufacturer is put at the top of the form to match Tripal 3
* I have added an ugly special case handling with https://github.com/tripal/tripal/pull/1599/commits/9d2c9683b24abaf4877591b507a5f7c73116a313 because the `manufacturer_id` column in the `arraydesign` table is the column that corresponds to the `contact_id`. I don't know if there is a more elegant way to do this.
_Update_ one special case removed with https://github.com/tripal/tripal/pull/1599/commits/2ff984f3581e2e1d6ad66380fd4de6dfc22c22dc
* I have added testing following @laceysanderson 's tests for the ChadoAnalysisDefault field. I have started to genericize it just a bit so there is less work using this as a base for creating tests for another field, I am using `base` and `linked` in the sql instead of `study` and `contact`, just one fewer thing to change.
* I added an additional assertion in `tripal_chado/tests/src/Traits/ChadoStorageTestTrait.php` with https://github.com/tripal/tripal/pull/1599/commits/e91cf2a9abbda069c54af19b3e0687c5490f5557 to catch my own stupid mistakes.
* typo `intstrument`

**Comment by dsenalik** [comment]
After discussion with @laceysanderson we decided to make the `null` contact more user friendly with https://github.com/tripal/tripal/pull/1599/commits/2b0f3d8330769d4b77ee83fcebb7cb9d4054415e
This is the contact with name `null` which is defined by chado, which will have `contact_id==1`
For the user-facing select list presented by this field, and in the formatter, it will be changed to `Unknown`.
The same can be done for the publications, where there is a null publication defined (future project).
Ideally this would be a configurable setting, but we will not implement that now.

**Comment by dsenalik** [comment]
Example of select list now, the Unknown should sort to the top
Select
And sort is now case insensitive, before all contacts starting with upper case would come before those with lower case.

**Review by laceysanderson — APPROVED** [review]
Code review looks perfect including the tests!
Functional review also works perfect after a bit of back and forth during cofest!

I tested on both study and array_design:
- Can set it to the null contact
- Can set it to an existing contact
- If I leave it at select it won't let me submit as it's required
- updating works great to both another existing contact and the null contact
- validation for required works on update as well as create

**Pull request merged**
