### PR TITLE
Overhaul of content creation for prop-based types.

### PR DESCRIPTION
**Pull request by spficklin**
Issue #427 

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

This PR was initiated because of a major problem with content type creation.  If a user created a content type that was specified using a property it would work fine for publishing those content types, but not for inserting new records via the GUI.  For example, if you wanted to create a 'genome_assembly' content type where the type of assembly is defined in the analysisprop table you could publish existing records but not add new ones.   There were two problems 1)  the code for adding new entities never added the appropriate prop record.  2) For tables such as the feature table that already have a type_id, but that type_id is not used to differentiate the content type, the insertion would fail (e.g. feature table entities). This is because the type_id would not be inserted.  We still need a type_id.    Consider the example of a 'SNP' page where the feature.type_id = 'genetic_marker', the featureprop.type_id = 'type' and the featureprop.value = 'SNP'.  You could define this content type, but if you wanted to manually add a new record you could not because the type_id would not be set to 'genetic_marker' and the prop record would not get inserted.   This PR fixes both of these problems.

This PR also includes a major overhaul of the content type creation form.   To make this PR work I needed to add some new form elements and that made the form overwhelming to look at.  The form is now a multi-step form (see screenshots below).  This should make it easier for end-users.

This PR also includes an update to the user_guide documents reflecting the changes made by this PR.

Note: This PR also includes tripal_chado_update_7331() to add a new column to the chado_bundle table for storing the type_id for the base table if need be.

## Testing?

1)  First, pull the PR branch.
2)  Run the update function using this command rather than updatedb (that way you can run updatedb on the 7.x-3.x branch once all update hooks have been merged in ... there are two other update hooks in two different open PRs).
  ```
  drush php-eval 'module_load_include("install", "tripal_chado", "tripal_chado"); 
tripal_chado_update_7331()'
  ```
3)  Rebuild the documentation:
  ```
  cd docs
  make html
  ```
4) Follow the two examples in the updated documentation to create two new content types.  One using a traditional method and the other using the prop table.  This will also give you a chance to review the updated docs.
5)  Try to create new content for both the new genetic_marker and SNP content types. You should be able to do so using the web interface and all should be inserted with no issues.  
6)  If you run this query you should see in the database that for this new feature added you will also have a property record added and the featureprop.type_id should resolve to the 'rdfs:type' term and the value should be 'SNP'.  The feature.type_id should be 'genetic_marker:
  ``` sql
  SELECT F.name, F.uniquename, CVT.name, CVP.name, CVTP.name, FP.value
  FROM featureprop FP
    INNER JOIN feature F on F.feature_id = FP.feature_id
    INNER JOIN cvterm CVT on F.type_id = CVT.cvterm_id
    INNER JOIN cvterm CVTP on FP.type_id = CVTP.cvterm_id
    INNER JOIN cv CVP on CVTP.cv_id = CVP.cv_id
  WHERE CVT.name = 'genetic_marker'
  ```
7) Please feel free to create other content types using different combinations of settings.  All should work, and all new content types should allow you to add new entities via the web interface without problems.

## Screenshots (if appropriate):
Sequence of form steps for creating a 'genetic_marker' content type:

image
image
image
image
image

Creating a SNP page:
image

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
This is really interesting.  HWG makes use of prop-based content types (analysis subtypes) and i was not experiencing problems.  I'll be sure to test this out thanks stephen.

edit: I see: on further inspection, the type prop was not getting set for new content!

**Comment by bradfordcondon** [comment]
I get the following, very unhelpful, error manually creating a SNP following the guide:

```
Could not save the entity: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block
Cannot save entity
```

**Comment by spficklin** [comment]
Hmmmm.... so nothing in the recent logs either?

**Comment by bradfordcondon** [comment]
watchdog- nothing in tripal_chado, tripal_entities, tripal_field, tripal_fields

i have this in `tripal`

```
504  30/Aug 15:47  tripal    error     PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is
 64                                     aborted, commands ignored until end of transaction block: SET search_path TO public; Array
                                        (
                                        )
                                         i
 504  30/Aug 15:46  tripal    error     PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is
 62                                     aborted, commands ignored until end of transaction block: SET search_path TO public; Array
                                        (
                                        )
                                         i
```


anywhere else i should be checking?

**Comment by spficklin** [comment]
I have pushed some changes to error reporting. They may not yet help but it's a work in progress. Can you pull and try again and repost the error message?

**Comment by almasaeed2010** [comment]
Hello @spficklin 

The branch worked great for me. I was able to create new content type following the docs and insert and edit a few entities as well without any issues.

screen shot 2018-08-31 at 8 11 18 am


Thanks!

**Review by almasaeed2010 — APPROVED** [review]

**Comment by spficklin** [comment]
Awesome! Thanks @almasaeed2010 

@bradfordcondon  there is a dpm commented out on line 48 of the tripal_chado/includes/tripal_chado.field_storage.inc that contains tripal_chado_field_storage_write() function.    Can you uncomment, run it and try again?

**Comment by spficklin** [comment]
Also, @bradfordcondon  you might want to pull this PR's branch again. I just fixed a bunch of merge  conflicts with 7.x-3.x branch.

**Comment by bradfordcondon** [comment]
@spficklin there is no dpm there on the current version of this branch, see
https://github.com/tripal/tripal/blob/40559c69cc35b92708cdb30605f5fd23173c9c9f/tripal_chado/includes/tripal_chado.field_storage.inc#L37-L56

what variable should i dpm?

**Comment by spficklin** [comment]
Looks like the commented-out dpm got removed... sorry.  can you add a dpm on line 54 like this:
```
dpm($values)
```

**Comment by bradfordcondon** [comment]
```
uniquename (String, 7 characters ) waffles
is_analysis (Integer) 0
is_obsolete (Integer) 0
timeaccessioned (String, 19 characters ) 2018-08-31 16:22:00
timelastmodified (String, 19 characters ) 2018-08-31 16:22:00
organism_id (String, 1 characters ) 3
name (String, 9 characters ) dfjalksfj
```
looks reasonable to me

**Comment by spficklin** [comment]
Okay, can you add it to line 84 now?  Just after the end of the elseif statement?

https://github.com/tripal/tripal/blob/40559c69cc35b92708cdb30605f5fd23173c9c9f/tripal_chado/includes/tripal_chado.field_storage.inc#L82-L86

And can you add another after line 120?  Just after the end of the else statement

https://github.com/tripal/tripal/blob/40559c69cc35b92708cdb30605f5fd23173c9c9f/tripal_chado/includes/tripal_chado.field_storage.inc#L118-L122

**Comment by bradfordcondon** [comment]
now we're geting somewhere: dpms dont fire at line 120.

so 
```  
// Insert the record into the base table and get the record ID.
  $base_record_id = tripal_chado_field_storage_write_table($base_table, $values, $base_table);
  if (!$base_record_id) {
    throw new Exception('Unable to write fields to Chado: ' . print_r($field_items, TRUE));
  }
```

 is failing

ill look into it more...

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/blob/40559c69cc35b92708cdb30605f5fd23173c9c9f/tripal_chado/includes/tripal_chado.field_storage.inc#L236

this record insert is failing.  the values its inserting are:

table_name (String, 7 characters ) feature
new_vals (Array, 7 elements)
uniquename (String, 8 characters ) marklark
is_analysis (Integer) 0
is_obsolete (Integer) 0
timeaccessioned (String, 19 characters ) 2018-08-31 17:12:00
timelastmodified (String, 19 characters ) 2018-08-31 17:12:00
organism_id (String, 1 characters ) 3
name (String, 8 characters ) marklark

**Comment by spficklin** [comment]
It seems the problem that leads to the Exception being thrown is not being logged, because you don't see it in the watchdog.  The exact SQL error would be nice to know.  

https://github.com/tripal/tripal/blob/40559c69cc35b92708cdb30605f5fd23173c9c9f/tripal_chado/includes/tripal_chado.field_storage.inc#L236-L239

I'm guessing it is getting logged to watchdog in the chado_insert_record() but it's done in a transaction and when the transaction rolls back the log is lost.

edit:  this may be one example for why we need a better unified approach to exceptions and loggings: issue #588

**Comment by bradfordcondon** [comment]
why is there no type_id?

**Comment by spficklin** [comment]
The type_id should be set in these lines of code:
https://github.com/tripal/tripal/blob/40559c69cc35b92708cdb30605f5fd23173c9c9f/tripal_chado/includes/tripal_chado.field_storage.inc#L66-L83

**Comment by spficklin** [comment]
What does the row in your chado_bundle table look like for this content type?

**Comment by bradfordcondon** [comment]
```
select * from public.chado_bundle wHERE type_value = 'SNP';
chado_bundle_id	bundle_id	data_table	type_linker_table	type_column	type_id	type_value	base_type_id
15	15	feature	featureprop	type_id	2939	SNP
```

**Comment by spficklin** [comment]
You seem to be missing the base_type_id value....

**Comment by spficklin** [comment]
That would explain why the type_id is missing when it tries to insert the record.

**Comment by bradfordcondon** [comment]
I recreated my content type and was able to insert a record with it.

Most likely explanation is that I made a mistake creating the content type as theres no base type_id entry in `chado_bundle`

edit the form prevents mistaking this mistake, so i must have updated my db after creating the content?

**Comment by spficklin** [comment]
Thanks @bradfordcondon and @almasaeed2010 .  This PR fixed a problem that was really bugging me. I'm happy to see it merged!

**Pull request merged**
