### PR TITLE
Organism/Contact widgets on Biomaterial content type

### PR DESCRIPTION
**Pull request by spficklin**
Issue #222

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

As per the description on issue #222 the organism and contact foreign keys on the biomaterial table are allowed to be NULL.  The field widgets for the organism and contact weren't properly supporting NULL values for these fields.  This PR fixes this problem.

## Testing?

To test this do the following:
1)  Create a new biomaterial content type that resolves to the biomaterial Chado table.  If you don't have a biomaterial CV term it really doesn't matter, just use anything.  The important thing is that you have a content type that resolves to the biomaterial table.
2) Manually add a new biomaterial entity.  Be sure to set the Organism and the Contact.  Save the entity.
3)  Now edit the entity and remove both the contact and the organism.  If you are using the 7.x-3.x branch you will get an SQL error.  With this branch the content is saved and the entity updates correctly.

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
Thanks!  Tested and confirmed both organism and contact are now nullable.

**Review by bradfordcondon — APPROVED** [review]
looks good, thanks!  I love that `biomaterial` always needs its own hardcoded exception

**Comment by shawnawsu** [comment]
I can also save the biomaterial content type with a null organism and contact field.

**Review by shawnawsu — APPROVED** [review]

**Comment by spficklin** [comment]
Thanks @shawnawsu and @bradfordcondon

**Pull request merged**
