### PR TITLE
Add reload entity button to Remove empty fields when using ajax

### PR DESCRIPTION
**Pull request by almasaeed2010**
This PR adds the functionality that Stephen wanted to refresh the field.

Only @spficklin and @bradfordcondon need to review this since it affects the messed up branch.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
i renamed PR since its confusing with all these reverts i made :'(

looks good to me 👍 you want us both to approve?

screen shot 2018-09-20 at 3 08 58 pm

**Comment by laceysanderson** [comment]
I think the permission should be for admin role only! My content managers are going to so confused by this :-( See my previous comment to this effect here: https://github.com/tripal/tripal/pull/628#issuecomment-421803327

**Comment by almasaeed2010** [comment]
Would a `administer tripal` permission be better @laceysanderson ?

**Comment by almasaeed2010** [comment]
@laceysanderson the code now uses `administer tripal` :)

**Comment by laceysanderson** [comment]
I think this is ready to merge. @almasaeed2010 do you still want to wait on @spficklin ?

**Comment by spficklin** [comment]
I tested and it works.  Thanks for submitting this.

**Pull request merged**
