### PR TITLE
Provide validation for already-used field terms

### LINKED ISSUE #1932: Enforce that two different fields cannot have the same cv term
### Task Description

We should probably make sure that we never have a situation where two fields on an entity share the same cv term.

We probably can add this to validation (`tripal/src/TripalField/TripalFieldItemBase.php`) when manually adding a field to a content type - hopefully this is easy, but you never know...

### Branch Name

tv4g1-issue1932-enforce-fields-unique-cvterm

### Idea
To look up all currently used CV terms for fields on a content type:
```
$bundle = 'project';
/** @var \Drupal\Core\Field\FieldTypePluginManager $field_type_manager **/
$field_type_manager = \Drupal::service('plugin.manager.field.field_type');
/** @var \Drupal\Core\Entity\EntityFieldManager $entity_field_manager **/
$entity_field_manager = \Drupal::service('entity_field.manager');

$all_field_defs = $field_type_manager->getDefinitions();
$entity_field_defs = $entity_field_manager->getFieldDefinitions('tripal_entity', $bundle);
foreach ($entity_field_defs as $id => $field_config) {
  if (is_object($field_config) and ($field_config instanceof Drupal\field\Entity\FieldConfig)) {
    $settings = $field_config->getSettings();
    $term_id_space = $settings['termIdSpace'] ?? '';
    $term_accession = $settings['termAccession'] ?? '';
    print "$id = $term_id_space:$term_accession\n";
  }
}
```
About 10 milliseconds

### PR DESCRIPTION
**Pull request by dsenalik**
# New Feature

## Description
Currently there is no mechanism to prevent you from adding a field to a content type, and using a CV term that happens to already be in use by another field. This PR adds a check to the validation when adding a field.

## Testing?
~~We would like to include non-chado fields in the test, but currently issue #1966 prevents that. We will make a small change to allow us to test with a generic tripal field.~~ Fixed with PR #1958
~~1. edit `tripal/src/Plugin/Field/FieldType/TripalIntegerTypeItem.php` and after line number 34 add this line
    `if (!$termIdSpace) { return; }`
    i.e.~~
```
     $termIdSpace = $storage_settings['termIdSpace'];
     $termAccession = $storage_settings['termAccession'];
+    if (!$termIdSpace) { return; }
```
2. Go to Tripal -> Page Structure -> Contact -> Manage fields
3. +Create a new field
4. Tripal Fields -> Continue
5. For Label enter "tripal integer" -> select "Tripal Integer Field Type" -> Continue
6. For the Controlled Vocabulary Term, enter any term you like, I used 'Sequence length (data:1249)' -> Save Settings
7. Now we test! Click "+Create a new field"
8. Chado Fields -> Continue
9. Enter a Label, like "test" or something more interesting.
10. Select something we can add to contact, I used "Chado Integer Field Type" -> Continue
11. For "Table Column" I used `contact_id`
12. Enter a Controlled Vocabulary Term that is already in use, try the one you created at step 6
13. Observe a validation error.
issue1932-1
issue1932-2
14. Try the other existing terms on the contact content type, all of these should fail validation: 
```
Communication Contact (NCIT:C47954)
description (schema:description)
name (schema:name)
Project (NCIT:C47885)
```
15. Try any other term, e.g. `DNA (SO:0000352)`, validation should pass, and the field should be added successfully.
issue1932-3
16. To test the other validation that I fixed, add another field (I added another project field) and enter something not of the correct format as a term, e.g. `xxx`. The validation should not allow this and should correctly highlight the field in red. You can test this part on 4.x and see that the validation catches this, but does not highlight the field in red.
issue1932-4
issue1932-5

This is the appearance on 4.x:
issue1932-6

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
I confirmed that this works when creating a new Tripal String field and when creating a new chado field. I ensured that it was specific to terms being used on the same content type and not terms on another content type. I checked the validation of an incorrectly entered term.

I did find one issue though... you now trigger a validation error when trying to edit any field. For example,
1. Go to manage fields for the organism content type.
2. Click edit beside the organism common name field.
3. Then click save (the error is triggered whether you make a change or not)
4. Observe the "term already being used" validation error... even though the field using the term is this exact field 🙈 
Screenshot 2024-09-21 at 3 35 15 PM

**Comment by dsenalik** [comment]
Oops, sorry I didn't test that 😬! Should be fixed now.

**Comment by Ferrisx4** [comment]
I just tested this as well, I have not encountered any issues. I also confirmed that the issue @laceysanderson when editing fields has also been fixed as of https://github.com/tripal/tripal/pull/1967/commits/78121d829efb974f2fab426d03d5e7d1379908b3

**Review by laceysanderson — APPROVED** [review]
Switching to approved based on a code review of the change in https://github.com/tripal/tripal/commit/78121d829efb974f2fab426d03d5e7d1379908b3 and @Ferrisx4 updated testing.

**Pull request merged**
