### PR TITLE
Expanding ChadoStorage to better support linker tables

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task 

Issue #1449 

## Description
This PR was started when working with @srobb1 and @dsenalik on Tripal 4 Fields for linking tables. It was becoming clear that the current ChadoStorage implementation was not meeting the needs here. Most notably these were a few of the core restrictions:

1. store_id made assumptions that it would only be used for the base table of the field.
2. we were not able to make a "double hop" query with two joins through a linker table (e.g. feature > feature_synonym > synonym)
3. we were having trouble only inserting if the record didn't already exist (i.e. select or insert functionality)
4. records added to chado independently of the fields were not being added to the field display (e.g. adding properties via an importer then refreshing a Tripal content page wasn't displaying these properties, described within #1398)

## Design Discussion

Originally we thought we needed to fix these problems in order to support this functionality:

 - store_id assumes base table
 - store_link doesn't join
 - not able to detect new records added to chado outside of the UI
 - store_link doesn't support double-hops including insert or select of base record at the right side of the relationship.

We have since realized a couple of things:

1. detecting records added outside the UI is the job of publishing, not chadostorage.
2. using joins here might incur a performance hit and is not needed once we have good publishing
3. handling of the base record at the right side of a double-hop relationship may incur more complexity to chadostorage than it's worth... instead we should let the widget handle insert/select of this record and chado storage handle the linking table.

This PR embodies these new design ideas. Specifically, the changes are:

 - remove the assumption of there being a single base table that is the same across fields.
 - introduce left/right table notation to the store_link for better describing of the relationship
 - backwards compatible check for store_link to support old style properties with this action as much as possible.
 - extra documentation in chadostorage to separate out and explain the actions.
 - fixes to ensure the record_id for core tables is set for secondary tables as early as possible.
 - Kernel tests focused on property-style fields and linker-style fields.
 
## Testing?

There is automated testing in this PR to test the specific use cases. This PR does not have specific fields yet so you cannot test manually.

Tests:
  - ChadoLinkerPropertyDefaultTest: Tests the new and old style of store_link for property-style fields
  - ChadoLinkerTableTest: Tests the new style of store_link for double-hop style linker tables (e.g. feature_synonym). Currently only tests insert as this test is not yet complete.

### CODE REVIEW

**Comment by dsenalik** [comment]
Excellent! 🎉 It sounds like this will fix the problem I noted in this comment https://github.com/tripal/tripal/issues/1398#issuecomment-1452279615 of not detecting records entered directly into the db.

**Comment by dsenalik** [comment]
Testing with the `chado_linker__prop` field, it looks to me like the `store_link` property for this field should become
before
```
       new ChadoIntStoragePropertyType($entity_type_id, self::$id, 'linker_id',  $link_term, [
         'action' => 'store_link',
         'chado_table' => $prop_table,
         'chado_column' => $prop_fk_col,
       ]),
```
after
```
      new ChadoIntStoragePropertyType($entity_type_id, self::$id, 'linker_id',  $link_term, [
        'action' => 'store_link',
        'left_table' => $base_table,
        'left_table_id' => $base_pkey_col,
        'right_table' => $prop_table,
        'right_table_id' => $prop_fk_col,
      ]),
```
@laceysanderson If this seems correct (I tested, before there were errors, now it works) I could add this change to this branch. We will have to update `schema__additional_type` also!

**Comment by dsenalik** [comment]
A minor news update, with the test procedure described in issue #1398, I still see that error on this branch at step 13
Then at step 14 I get an error
The item cannot be saved because the following values are missing. Name.

**Comment by spficklin** [comment]
The changes to `store_link` in the current state of this PR break creation of content types that use the prop tables to store the types.  I figured it would be better to fix it here rather than try to fix it on the publish issue #1515 .  I think we just need to fix the problems with the ChadoStorage than I can go back to publishing. I'm going to take a stab at it.

**Comment by spficklin** [comment]
First comment on one of the issues mentioned above.  The issue is this:  

- You add a Chado Property field to the gene content type for comments
- You create a gene and you add two comments "Note1" and "Note2".
- You then add a comment, "Note 3",  outside of Tripal (e.g. via an SQL statement)
- The page doesn't pick up the new "Note 3" comment that was added outside of Tripal.

The fact the "Note 3" doesn't load is not a bug in ChadoStorage that needs fixing.  That's because when the values are added to the field, a corresponding record is added to the field table in Drupal (e.g. `tripal_entity__field_comment` table).  So "Note 1" and "Note  2" both get a record in the Drupal field table.   Publishing in Tripal 4 is different from Tripal 3 because entities aren't tied to a back-end, the field data is actually getting published, not the entity.    So, if the ChadoStorage class returns values that are not published (e.g. "Note 3") then it's doing more than it should.  It should only return what is instructed by the $values array that gets passed into the `findValues()` function and that $values array gets created by what is present in the Drupal field table--and that table only knows about two records: "Note 1" and "Note 2".  If we want "Note 3" to be loaded then we need to add  new record to the Drupal field table for that new value.  Then it will show up on the page.  That's "publishing" of the field values.   

I think the correct solution for this is not to adjust the ChadoStorage class but do one of the following:

1.  Make the site admin publish new field data anytime data is loaded.  Perhaps this could be part of the TripalImporter class.
2. Add a tab at the top of each page, like we had in Tripal v3 that let the site admin reset the cache.  We could have a similar tab that would let the site admin republish (or find new values) for the fields on the page.  
3. Add a cron job that runs a "publish" for existing entities to pick up new data values.

**Comment by spficklin** [comment]
Another item to consider.... I'm not sure we need to update the `store_link` action when there are linker tables like `feature` <-> `feature_synonym` <-> `synonym`.   I started to try and work on the ChadoStorage to support this and I realized I can make the synonym field work without making changes to ChadoStorage.  

The issue is that the synonym must exist first in the synonym table.  So if it doesn't, we want to create it.  This creates some real complexity for the ChadoStorage class because it needs to figure out that if a user is adding a new synonym that doesnt exist yet, that it needs to first add that synonym before it can add the linker code.  

We can easily get around this if the field widget does the insert of the synonym first and then set the ID for it in the property that represents the linker.  I have made a working version of tje field in #1447 that does not require any changes to ChadoStorage to work.  I think given the complexity of making ChadoStorage smart enough to do this, that it's really not to hard to make the field do a little housekeeping before an insert/udate.   My suggestion is to leave ChadoStorage as is.   

I haven't yet made a PR for the synonym field because I have one bug with multiple instances. Once I fix that, then I'll make a push to PR #1447 and then you can review it and see how I got around the problem.

**Comment by laceysanderson** [comment]
🤯 I feel like an important missing piece just dropping into place! <3

**Comment by laceysanderson** [comment]
After discussing with @spficklin today, we have decided that Chado Storage is becoming too complicated and more importantly -more complicated then it needs to be.

The plan moving forward is:
- ChadoStorage will support the following cases
    - insert/update columns in the base table (e.g. stock)
    - insert/update columns accessed through a single-hop (e.g. stockprop)
    - select across multiple hops for read-only access
    - read-only access for the base-table (e.g. stock)
- ChadoStorage will NOT:
    - find unpublished records from Chado. For example, if data is imported or pre-existing in chado, then you need to publish first. This will not be done by ChadoStorage.
    - insert/update records in a table accessed through a linker table (e.g. feature => feature_synonym => synonym). In this case the widget will be expected to add/select the synonym record and then add the id to the property. ChadoStorage will manage the feature => feature_synonym part through.

I will be updating this PR to match this new design.

**Review by spficklin — APPROVED** [review]

**Pull request merged**
