### PR TITLE
Fixed publication terms error

### PR DESCRIPTION
**Pull request by spficklin**
# Bug Fix

## Description

When installing the "General Content Types", you would see the following errors:

```
 [error]  ERROR: The term accession is not known in the Term Id Space. Check the "termIdSpace" and "termAccession" elements. 
[site http://default] [TRIPAL] ERROR: The term accession is not known in the Term Id Space. Check the "termIdSpace" and "termAccession" elements.
 [error]  ERROR: The term accession is not known in the Term Id Space. Check the "termIdSpace" and "termAccession" elements. 
[site http://default] [TRIPAL] ERROR: The term accession is not known in the Term Id Space. Check the "termIdSpace" and "termAccession" elements.
 [notice] Added field, "publication_title", to content type: "pub".
 [error]  ERROR: The term accession is not known in the Term Id Space. Check the "termIdSpace" and "termAccession" elements. 
[site http://default] [TRIPAL] ERROR: The term accession is not known in the Term Id Space. Check the "termIdSpace" and "termAccession" elements.
```
This PR fixes that probem by adding in the missing terms, improving the error message to make it more clear which field may be the problem (as the error message above isn't too descriptive).

## Testing?

Simply install the site with and without this PR's fix and you'll see that the error messagse are gone.  

Also, you can go to the  Admin > Structure > Tripal Content Type  and select "Manage Fields" under publication and you'll see all four fields that are currently part of the Publication content type.

### CODE REVIEW

**Comment by dsenalik** [comment]
I am trying to duplicate the error with docker on the 4.x branch

First, prevent general content types from being automatically installed by editing
`tripaldocker/Dockerfile-php8.2-pgsql13`

```
diff --git a/tripaldocker/Dockerfile-php8.2-pgsql13 b/tripaldocker/Dockerfile-php8.2-pgsql13
index 7119d6261..124853b01 100644
--- a/tripaldocker/Dockerfile-php8.2-pgsql13
+++ b/tripaldocker/Dockerfile-php8.2-pgsql13
@@ -193,8 +193,7 @@ RUN service apache2 start \
   && vendor/bin/drush en tripal tripal_biodb tripal_chado ${modules} -y \
   && if [ "$installchado" = "TRUE" ]; then \
     vendor/bin/drush trp-install-chado --schema-name=${chadoschema} \
-    && vendor/bin/drush trp-prep-chado --schema-name=${chadoschema} \
-    && vendor/bin/drush trp-import-types --collection_id=general_chado --username=drupaladmin; \
+    && vendor/bin/drush trp-prep-chado --schema-name=${chadoschema}; \
     fi \
   && service apache2 stop \
   && service postgresql stop
```

Then build a docker and once running, import the "general" content types.
```
# trj

2023-12-28 21:28:55
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2023-12-28 21:28:55: Job ID 1.
2023-12-28 21:28:55: Calling: import_tripalentitytype_collection(Array)
 [notice] Creating Tripal Content Types from: General Content Types (Chado)
 [notice] Content type, "Organism", created.
 [notice] Content type, "Analysis", created.
 [notice] Content type, "Project", created.
 [notice] Content type, "Study", created.
 [notice] Content type, "Contact", created.
 [notice] Content type, "Publication", created.
 [notice] Content type, "Protocol", created.
 [notice] Attaching fields to Tripal content types from: Default Chado Fields
 [notice] Added field, "organism_abbreviation", to content type: "organism".
 [notice] Added field, "organism_genus", to content type: "organism".
 [notice] Added field, "organism_species", to content type: "organism".
 [notice] Added field, "organism_common_name", to content type: "organism".
 [notice] Added field, "organism_infraspecific_name", to content type: "organism".
 [notice] Added field, "organism_infraspecific_type", to content type: "organism".
 [notice] Added field, "organism_comment", to content type: "organism".
 [notice] Added field, "analysis_name", to content type: "analysis".
 [notice] Added field, "analysis_description", to content type: "analysis".
 [notice] Added field, "analysis_software", to content type: "analysis".
 [notice] Added field, "analysis_program_version", to content type: "analysis".
 [notice] Added field, "analysis_algorithm", to content type: "analysis".
 [notice] Added field, "analysis_source", to content type: "analysis".
 [notice] Added field, "analysis_source_version", to content type: "analysis".
 [notice] Added field, "analysis_source_uri", to content type: "analysis".
 [notice] Added field, "project_name", to content type: "project".
 [notice] Added field, "project_description", to content type: "project".
 [notice] Added field, "project_contact", to content type: "project".
 [notice] Added field, "project_analysis", to content type: "project".
 [notice] Added field, "study_name", to content type: "study".
 [notice] Added field, "study_description", to content type: "study".
 [notice] Added field, "study_contact", to content type: "study".
 [notice] Added field, "study_dbxref_id", to content type: "study".
 [notice] Added field, "study_pub_id", to content type: "study".
 [notice] Added field, "contact_name", to content type: "contact".
 [notice] Added field, "contact_description", to content type: "contact".
 [notice] Added field, "contact_type", to content type: "contact".
 [notice] Added field, "protocol_name", to content type: "protocol".
 [notice] Added field, "protocol_uri", to content type: "protocol".
 [notice] Added field, "protocol_description", to content type: "protocol".
 [notice] Added field, "protocol_instrument", to content type: "protocol".
 [notice] Added field, "protocol_software", to content type: "protocol".
 [notice] Added field, "protocol_type", to content type: "protocol".
 [notice] Added field, "protocol_dbxref_id", to content type: "protocol".
 [notice] Added field, "protocol_pub_id", to content type: "protocol".
 [notice] Added field, "publication_uniquename", to content type: "pub".
 [notice] Added field, "publication_type", to content type: "pub".
 [notice] Added field, "publication_title", to content type: "pub".
 [notice] Added field, "publication_volumetitle", to content type: "pub".
```
However I don't see any errors. 

Investigation must continue tomorrow...

**Review by dsenalik — APPROVED** [review]
The reason you don't see this with the docker is because the docker build process loads `tpub.obo`, which provides these terms.
```
...
#27 215.7  [notice] Importing Tripal Publication Ontology. A temporary ontology until a more formal appropriate ontology an be identified.
#27 215.8  [notice] Importing into schema: chado
#27 215.8  [notice] Step 1: Preloading File //var/www/drupal/web/modules/contrib/tripal/tripal_chado/files/tpub.obo...
...
```
Since these are essential terms, this fix is the way to make sure they are always present, so I hereby approve.

**Comment by dsenalik** [comment]
I realize that for PR #1704 more terms will be needed. That made me notice the missing description for `Citation`, so I just added it here https://github.com/tripal/tripal/pull/1718/commits/09f031fe6aac554f2faaa0e24cd7b790925fe042. None of the other pub terms here have definitions in the obo file.

**Comment by dsenalik** [comment]
Okay @spficklin I have a question, it seems that tpub.obo is loaded when chado is prepared:
`vendor/bin/drush trp-prep-chado  --schema-name=${chadoschema}`
I didn't manually install tripal because I was lazy. Did you run the chado prepare step?

**Comment by dsenalik** [comment]
So I just built a Tripal site from scratch on the 4.x branch to try and replicate this error.
If I get to just before the chado prepare step, and try to add the general content type, it blows up.
```
2023-12-29 08:39:18
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2023-12-29 08:39:18: Job ID 3.
2023-12-29 08:39:18: Calling: import_tripalentitytype_collection(Array)
Error: Call to a member function getTerm() on null in /var/www/tripal4/web/modules/tripal/tripal/src/Services/TripalEntityTypeCollection.php on line 109 #0 /var/www/tripal4/web/modules/tripal/tripal/tripal.module(595): Drupal\tripal\Services\TripalEntityTypeCollection->install()
#1 [internal function]: import_tripalentitytype_collection()
#2 /var/www/tripal4/web/modules/tripal/tripal/src/Services/TripalJob.php(366): call_user_func_array()
#3 /var/www/tripal4/web/modules/tripal/tripal/src/api/tripal.jobs.api.php(443): Drupal\tripal\Services\TripalJob->run()
#4 /var/www/tripal4/web/modules/tripal/tripal/src/Commands/TripalCommands.php(77): tripal_launch_job()
#5 [internal function]: Drupal\tripal\Commands\TripalCommands->runJobs()
#6 /var/www/tripal4/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#7 /var/www/tripal4/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#8 /var/www/tripal4/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#9 /var/www/tripal4/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#10 /var/www/tripal4/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#11 /var/www/tripal4/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#12 /var/www/tripal4/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#13 /var/www/tripal4/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#14 /var/www/tripal4/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#15 /var/www/tripal4/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#16 /var/www/tripal4/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#17 /var/www/tripal4/vendor/drush/drush/drush(4): require('...')
#18 /var/www/tripal4/vendor/bin/drush(117): include('...')
#19 {main}
Error: Call to a member function getTerm() on null in Drupal\tripal\Services\TripalEntityTypeCollection->install() (line 109 of /var/www/tripal4/web/modules/tripal/tripal/src/Services/TripalEntityTypeCollection.php).
 [warning] Drush command terminated abnormally.
```

However, if I do the chado prepare step, then add general content types, I get no errors.

**Review by laceysanderson — APPROVED** [review]
Ok, I can confirm the same thing @dsenalik is seeing. When I run the prepare before importing the general content types on 4.x there are no errors 😕 

That said, having the terms in the content type terms list is an extra precaution and doesn't cause any issues so I'm going to approve this anyway 🤷‍♀️

**Comment by spficklin** [comment]
Thanks for all your testing and checking. I did run the prepare prior to installing the content types.  It's odd you don't see the same errors I do. I consistently saw those each time I reinstalled.  Thanks for the review.

**Pull request merged**
