### PR TITLE
issue1530 update node.js from 12 to 16

### LINKED ISSUE #1530: Update node.js from version 12 to 16
# Core Tripal 4 Development Task

## Branch Name: tv4g0-issue1530-update-node.js-from-12-to-16

The motivation for this issue is to fix the warnings emitted during the docker build process, for example, the first of eight warnings at https://github.com/tripal/tripal/actions/runs/5122451673 is:

Docker Build (drupal9.4.x-dev)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

### PR DESCRIPTION
**Pull request by dsenalik**
# Tripal 4 Core Dev Task

## Description
Node.js 12 actions are deprecated
I think this might be resolved with two 1-byte changes of `actions/checkout@v2` to `actions/checkout@v3`

## Testing?
Automated testing should be sufficient, as it is currently just a deprecation warning 🤷

### CODE REVIEW

**Comment by laceysanderson** [comment]
Yes, this is the fix 😁 We need to do it in every single one of our workflows though 🙈

**Comment by dsenalik** [comment]
Yes I missed one of them. Checked with a recursive grep, this should do it.

**Comment by laceysanderson** [comment]
Awesome! Thanks @dsenalik ! (I forced the merge without updating the branch since there was no chance of interaction between this and the dependency injection PR that was just merged)

**Comment by dsenalik** [comment]
This is just to confirm that the deprecation notices are no longer present after merging this pull request ✅

**Pull request merged**
