### PR TITLE
Issue #1202 updates to sio__references type determination

### PR DESCRIPTION
**Pull request by dsenalik**
# Bug Fix

#

Issue #1202 

## Description
I am submitting some changes to better handle a few entity types for the sio__references field, specifically for featuremap, analysis, and project.

This goes in the code just after 
```
          // We want to add a 'type' and 'name' element to the values (at a
          // minimum) for each of the records.  Unfortunately, every base table
          // is different and there may not be an easy to identify name,
          // so... we'll do the best we can.
```
and I am trying to do it a little better! Unfortunately this involves special cases for some content types. I also added a default so it won't be possible any more to have "**(s)**" labels for unhandled content types.

Also a couple of spelling corrections.

Before
before

After
after

## Testing?
You need a publication page with references to a featuremap, analysis, or project to see these changes.

### CODE REVIEW

**Comment by spficklin** [comment]
Hi @dsenalik. This looks like a good fix.  The only  weirdness is the word "Analysis(s)".   Which, I feel odd complaining about considering before it was just "(s)" on some items. I think maybe we should just take the "(s)" out and leave the singular form? What do you think?

**Comment by dsenalik** [comment]
That would be my preference also!

**Comment by dsenalik** [comment]
I added a commit to remove the "(s)" and appearance is now:
No-S

**Comment by spficklin** [comment]
Thanks for the fix! it's merged.

**Pull request merged**
