### PR TITLE
Bump testsuite version, use silent method and ad more tests for jobs

### PR DESCRIPTION
**Pull request by almasaeed2010**
## Type(s) of Change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [x] Updates documentation (inline or markdown files)

## Description

This PR provides a test for the method that was failing in issue #524 amongst other new tripal_job tests.

It also upgrades tripal-test-suite and adds an example of how to use the `silent` method in tests.

## Testing?

1. Checkout the branch and run phpunit (or see the log in travis ci).

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by spficklin** [comment]
@almasaeed2010 if I run phpunit on my site will it mess it up?

**Comment by almasaeed2010** [comment]
I would not run tests on a production site just in case but everything is wrapped in DB transactions so no side effects should happen when running PHPUnit.

**Comment by bradfordcondon** [comment]
* The linked issue was deleted: perhaps duplicate with #539 according to abdullah
* I request that we add documentation that says developers should run composer update. Where?  the testing repo?  I feel like thats kind of burying it and its important that people do it.

that said: CI checks pass on travis, and on my dev machine.  @spficklin i would never run tests on a production site in any circumstance: if someone didnt have a transaction in their test class it would add fake data which would be bad.


```
phpunit
PHPUnit 6.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.16
Configuration: /Users/chet/UTK/tripal/sites/all/modules/tripal/phpunit.xml

.......................                                           23 / 23 (100%)

Time: 1.86 minutes, Memory: 48.00MB

OK (23 tests, 47 assertions)
```

Considering this is essentially just updating Test Suite, this is a 1-person approval

**Comment by almasaeed2010** [comment]
Apparently for pull requests that come from a fork you can run 
`git fetch upstream pull/<id>/head:<branch>` where id is pull request # that shows up after the title at the top of the page. Should we add that somewhere to help people test?

**Comment by almasaeed2010** [comment]
This branch got messed up a bit by mistake so I am gonna recreate and submit another PR.

**Pull request closed without merging**
