### PR TITLE
Drupal Search API Support for Tripal Collections

### PR DESCRIPTION
**Pull request by laceysanderson**
I think this is ready to go but it might be good for others to test it first.

This PR
- uses the existing Tripal Collection Views Handler
- when Tripal Collections fieldset is added to a view, the form shown depends on the base of the view
- adds all fields available per bundle to collection (no ability to control which at this point)
- successfully creates the collection and adds bundles based on the search results

### CODE REVIEW

**Comment by spficklin** [comment]
@laceysanderson I found a bug in that I couldn't create the files after the collection was created. I traced it down to the code in the handler where the bundle was being added to the collection.  The full entity was being provided for the 'id' rather than just a list of entity IDs.  I fixed the issue, tested, it's now working for me.  But you might want to check it yourself one more time.  I've committed my fix to the branch.

**Comment by laceysanderson** [comment]
Weird. I was seeing my entities in the tab file before your change and now my file is empty except for the header. I need to look into this more but don't have time today.

When you say you "couldn't create the files after the collection was created", did you get an error? WSOD? hanging forever?

**Comment by spficklin** [comment]
No, I did not get an error, but the PHP serialized array saved in the tripal_collection_bundle table for the entity ids was mangled up.  I don't know why it was.  But it did not like saving the entire entity.  That field is meant just for the entity IDs.   That's very odd that it is failing for you.

**Comment by laceysanderson** [comment]
I tried a fresh install and am still unable to generate files for my collection. This seems to be related to the array of entities saved.

Transcript of job for generating files:
```
2018-05-09 22:11:18: Calling: tripal_create_collection_files(2)
Writing tab delimeted file.
Writing comma separated file.
Getting entities for ids 0 to 1 of 1
array_flip(): Can only flip STRING and INTEGER values! TripalEntityController.inc:465                         [warning]
Got 0 entities.
```

I confirmed this functionality does work for the same entities through a typical Tripal Content View using the original Tripal Collection handler.

Comparison of array entries:
 - Search Api Collection: `a:5:{i:0;N;i:1;N;i:2;N;i:3;N;i:4;N;}`
 - Tripal Content Collection: `a:200:{i:0;s:2:"54";i:1;s:2:"46";i:2;s:2:"64";i:3;s:3:"164";i:4;s:2:"65";i:5;s:1:"3";i:6;s:2:"80";i:7;s:1:"4";i:8;s:3:"134";i:9;s:2:"44";i:10;s:3:"180";i:11;s:2:"24";i:12;s:1:"1";i:13;s:3:"200";i:14;s:3:"115";i:15;s:2:"76";i:16;s:2:"95";i:17;s:2:"97";i:18;s:3:"162";i:19;s:2:"22";i:20;s:2:"43";i:21;s:2:"74";i:22;s:2:"13";i:23;s:2:"84";i:24;s:3:"189";i:25;s:3:"101";i:26;s:3:"171";i:27;s:3:"168";i:28;s:3:"194";i:29;s:2:"17";i:30;s:2:"92";i:31;s:3:"103";i:32;s:3:"126";i:33;s:2:"82";i:34;s:3:"129";i:35;s:3:"119";i:36;s:2:"60";i:37;s:3:"146";i:38;s:2:"70";i:39;s:3:"104";i:40;s:2:"38";i:41;s:2:"45";i:42;s:3:"179";i:43;s:2:"85";i:44;s:3:"195";i:45;s:3:"165";i:46;s:3:"127";i:47;s:1:"8";i:48;s:3:"193";i:49;s:3:"102";i:50;s:2:"40";i:51;s:2:"73";i:52;s:2:"78";i:53;s:3:"170";i:54;s:3:"199";i:55;s:3:"120";i:56;s:2:"57";i:57;s:2:"27";i:58;s:3:"116";i:59;s:2:"15";i:60;s:3:"166";i:61;s:3:"141";i:62;s:2:"62";i:63;s:3:"187";i:64;s:3:"142";i:65;s:2:"49";i:66;s:3:"107";i:67;s:3:"123";i:68;s:1:"5";i:69;s:3:"145";i:70;s:3:"182";i:71;s:2:"14";i:72;s:3:"157";i:73;s:3:"188";i:74;s:3:"144";i:75;s:2:"26";i:76;s:3:"183";i:77;s:2:"66";i:78;s:2:"32";i:79;s:2:"91";i:80;s:2:"29";i:81;s:3:"111";i:82;s:2:"56";i:83;s:2:"77";i:84;s:3:"124";i:85;s:3:"153";i:86;s:3:"105";i:87;s:3:"135";i:88;s:2:"20";i:89;s:3:"109";i:90;s:2:"37";i:91;s:3:"148";i:92;s:2:"47";i:93;s:2:"99";i:94;s:3:"154";i:95;s:3:"136";i:96;s:3:"143";i:97;s:2:"30";i:98;s:2:"83";i:99;s:2:"90";i:100;s:1:"7";i:101;s:2:"34";i:102;s:2:"51";i:103;s:3:"149";i:104;s:3:"159";i:105;s:3:"147";i:106;s:3:"172";i:107;s:3:"176";i:108;s:3:"137";i:109;s:3:"128";i:110;s:1:"9";i:111;s:3:"198";i:112;s:2:"35";i:113;s:3:"150";i:114;s:3:"156";i:115;s:3:"177";i:116;s:2:"58";i:117;s:2:"68";i:118;s:3:"140";i:119;s:2:"67";i:120;s:2:"63";i:121;s:3:"184";i:122;s:2:"11";i:123;s:3:"122";i:124;s:3:"178";i:125;s:2:"59";i:126;s:3:"197";i:127;s:3:"167";i:128;s:3:"139";i:129;s:3:"151";i:130;s:3:"117";i:131;s:3:"174";i:132;s:3:"181";i:133;s:2:"39";i:134;s:2:"61";i:135;s:3:"158";i:136;s:2:"98";i:137;s:3:"190";i:138;s:3:"191";i:139;s:2:"19";i:140;s:2:"81";i:141;s:2:"12";i:142;s:2:"88";i:143;s:2:"96";i:144;s:3:"173";i:145;s:3:"175";i:146;s:2:"93";i:147;s:2:"87";i:148;s:3:"121";i:149;s:2:"52";i:150;s:3:"106";i:151;s:2:"50";i:152;s:2:"48";i:153;s:3:"130";i:154;s:3:"160";i:155;s:2:"36";i:156;s:3:"100";i:157;s:3:"169";i:158;s:2:"25";i:159;s:2:"53";i:160;s:3:"113";i:161;s:2:"55";i:162;s:3:"192";i:163;s:2:"31";i:164;s:2:"28";i:165;s:2:"33";i:166;s:3:"125";i:167;s:2:"75";i:168;s:1:"2";i:169;s:2:"10";i:170;s:2:"94";i:171;s:3:"108";i:172;s:3:"114";i:173;s:3:"110";i:174;s:3:"132";i:175;s:3:"196";i:176;s:3:"138";i:177;s:3:"155";i:178;s:3:"163";i:179;s:3:"112";i:180;s:3:"131";i:181;s:2:"72";i:182;s:3:"185";i:183;s:3:"133";i:184;s:3:"118";i:185;s:2:"21";i:186;s:2:"89";i:187;s:3:"161";i:188;s:2:"69";i:189;s:1:"6";i:190;s:3:"186";i:191;s:2:"18";i:192;s:2:"79";i:193;s:3:"152";i:194;s:2:"41";i:195;s:2:"23";i:196;s:2:"71";i:197;s:2:"16";i:198;s:2:"42";i:199;s:2:"86";}`

Looks like the ids are not being saved for the Search API collection ;-) However, I don't have time to look into this right now. Additionally the handler times out on large datasets.

@isumoc how urgent is your need for this integration?

**Comment by spficklin** [comment]
This is really bizarre that it works on my site but not on yours.  Something has to be different, but unfortunately I can't duplicate it the same way as you experience it.

**Comment by laceysanderson** [comment]
Not sure why it's not repeatable :-(
My system information (cloud9):

* Tripal Version: most recent dev
* Drupal Version: 7.59
* PostgreSQL Version: 9.3.15
* PHP Version: 5.5.9-1ubuntu4.21

Anyway, I'll try to get back to this early next week.

**Comment by spficklin** [comment]
@laceysanderson any chance to get back to this one?

**Comment by laceysanderson** [comment]
Sorry, no :-( I got completely swamped...

**Comment by laceysanderson** [comment]
I finally got back to testing this. I pulled in all the recent changes in 7.x-3.x and tested on KnowPulse this time instead of cloud9. I still get the following error when generating files:
```
2018-06-10 11:12:34: Calling: tripal_create_collection_files(2)
Writing tab delimeted file.
Writing comma separated file.
Getting entities for ids 0 to 1 of 1
array_flip(): Can only flip STRING and INTEGER values! TripalEntityController.inc:465                                       [warning]
Got 0 entities.
Getting entities for ids 0 to 1 of 1240,800 bytes.
array_flip(): Can only flip STRING and INTEGER values! TripalEntityController.inc:465                                       [warning]
Got 0 entities.
```

KnowPulse Dev Environment:
- Drupal 7.59
- Tripal e8ee2bb8d6a7ed1b3deab94143d22730eea8f138
- PostgreSQL 9.4.10
- PHP 5.6.7-1

**Comment by laceysanderson** [comment]
So it turns out my search api view saves its results as follows:
screen shot 2018-06-10 at 12 03 56 pm

This caused @spficklin's commit to break export for me since `$r-entity->id` is obviously not set as `$r->entity` is my entity id. I'm not sure why or how this is different for @spficklin but this is what I get on a completely fresh Tripal site (cloud9) and my KnowPulse clone (see environment details above).

To solve the problem I added a check that supports both our cases just in case different backends cause the Search API to expose the results differently.

**Anyway, this PR is ready for testing again**

**Comment by laceysanderson** [comment]
## How To Test
1. Set up the Drupal Search API as indicated in this tutorial: http://tripal.info/tutorials/v3.x/searching/search-api
2. Edit the search view created in the tutorial to add `Global: Tripal Content Data Collections` to the footer.
3. On the search page, create a tripal collection, generate it's files and download them.

**Comment by bradfordcondon** [comment]
working on this/ getting prerequs set up... this is going to take a while.  sorry.

**Comment by spficklin** [comment]
I'm setting up again for testing as well.

**Comment by spficklin** [comment]
The test worked for me.  I was able to generate files from the data collection after creating the collection from the Search API results! 

Thanks for making the fix.

**Comment by spficklin** [comment]
@bradfordcondon did your testing work?

**Comment by bradfordcondon** [comment]
I'm sorry I didn't follow through yet, too much extra stuff to set up the search.

**Comment by bradfordcondon** [comment]
Confirmed collection creation, code looks good.

We have two issues with this feature currently:
* it took ~5 minutse to create a collection from 40 features.  This is because the views doesnt have the bundle.
* how do fields work?  For now, ALL fields go in the collection but that might not be ideal.

However we've decided to merge this as is and create seperate issue for speed.

Thank you @laceysanderson

**Comment by laceysanderson** [comment]
Great!
Follow-up Issues:
 - Performance: #436 
 - Configure Fields: #437

**Pull request merged**
