### PR TITLE
Fix a few warnings

### PR DESCRIPTION
**Pull request by abretaud**
Maybe a little of Issue #683?

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

A few little changes:
- Fixed a typo in various places "Tripal Publiation Ontology." -> "Tripal Publication Ontology."
- [Fixed wrong argument to tripal_set_bundle_variable](https://github.com/tripal/tripal/compare/7.x-3.x...abretaud:3_fixes?expand=1#diff-a984303b8516b93a524794d0cae62670L546)
- renamed "$is_a" element to "is_a" in the cache (see #683) -> that's not enough to fix the problem in #683 
- fixed several undefined variables/array indices

There are a lot of trailing whitespace removal too. It would be nice to make sure no trailing whitespace is in the code (with travis?), it makes diff hard to read...

## Additional Notes (if any):

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by spficklin** [comment]
Thanks @abretaud the code changes look good and make sense, but the unit testing is now failing.  So before we can merge this in we'll have to look into that.

**Comment by bradfordcondon** [comment]
2 failing tests, provided below for convenience:

```

Time: 4.25 minutes, Memory: 56.00MB
There were 2 failures:
1) Tests\OBOImporterTest::testCVtermPath with data set #0 ('56', '43')
Cound not find the cvtermpath record for the relationship: node02 => node01.
Failed asserting that false is not false.
/home/travis/build/tripal/drupal/sites/all/modules/tripal/tests/tripal_chado/loaders/OBOImporterTest.php:511
2) Tests\OBOImporterTest::testOBOChanges with data set #0 ('56', '43')
The node08 (TOT:008) should be marked as obsolete after update.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'node08 (obsolete)'
+'node08 (TOT:008)'
/home/travis/build/tripal/drupal/sites/all/modules/tripal/tests/tripal_chado/loaders/OBOImporterTest.php:604

```

**Comment by abretaud** [comment]
Didn't have th time to look more into the failed test today, but, I may have a fix for #683 in 5f49d8a
(What I don't understand is why you don't get the same error in travis without 5f49d8a, but well...)

**Comment by abretaud** [comment]
Green now!

**Comment by spficklin** [comment]
Hi @abretaud .  Thanks for fixing the failing unit tests.  Most of your changes are typo fixes and the few changes to the loader are typos and `array_key_exists` calls.  So, I think this only needs one review and I approve so I'm merging. 

It wasn't clear to me if this fixes #683 for you or not. I am not able to duplicate the problem for that issue so I hope this fixes it.

**Pull request merged**
