### PR TITLE
GFF3 Importer Update

### PR DESCRIPTION
**Pull request by par12005**
# 

Issue #1040

## Description

Added functionality to load Dbxref, Derives_from, and FASTA information into chado through the new GFF3 Importer.
Also fixed the `assignFeatureIDs` and `getCvtermID` methods and fixed some bugs in the `loadFeatureLocs` method.

## Testing
Either submit a new GFF3 Importer job or rerun an old one and verify that Dbxref information has been loaded into chado.

You can also run the gff3 unit test for dbxref information with 
```
./vendor/bin/phpunit --filter testGFFImporterAttributeDbxref tests/tripal_chado/loaders/GFF3ImporterTest.php
```
and note that the importer now passes the Dbxref unit tests.

The same works for Derives_from unit tests: 
```
./vendor/bin/phpunit --filter testGFFImporterAttributeDerivesFrom tests/tripal_chado/loaders/GFF3ImporterTest.php
```

As well as a new FASTA section unit test:
```
./vendor/bin/phpunit --filter testGFFImporterAttributeFastas tests/tripal_chado/loaders/GFF3ImporterTest.php
```

### CODE REVIEW

**Comment by par12005** [comment]
Added some additional bug fixes:

- The first two were for the `loadFeatureLocs` method:
  - Use `$feature['stop']` instead of `$feature['end']` [on line 1535](https://github.com/tripal/tripal/pull/1076/commits/c599975d97b606ab6df883065b1ce1cd736c0384), since `$feature['stop']` is the value that was [corrected](https://github.com/par12005/tripal/blob/1040-tv3-gff3_performance/tripal_chado/includes/TripalImporter/GFF3Importer.inc#L853) during the `parseFeature` method.
  - [Uncomment](https://github.com/tripal/tripal/pull/1076/commits/e8548ad31a9618614b8a219356fd985c75d49a86) actual insertion of the featureLocs batch.
- Get the sequence ontology cv ID from `$this->feature_cv` [in `getCvtermID`](https://github.com/tripal/tripal/pull/1076/commits/7ef8a2b7e6c09aa825a381d2f40456efbbc2517d), since `$this->sequence_cv_id` is no longer initialized.

**Comment by par12005** [comment]
Added `loadFastas()` method to GFF3Importer and added a new unit test `GFF3ImporterTest::testGFFImporterAttributeFastas()`

**Comment by spficklin** [comment]
I'm going to close out this PR because we have a whole lot of more work done to rewrite the GFF loader and this PR is no longer valid.  A new PR will be coming soon.

**Comment by spficklin** [comment]
Whoops.   My mistake. I should not have closed this.  this is new code

**Comment by mpoelchau** [comment]
Hi @spficklin 

@Ferrisx4 and I are testing this PR with the following files:
genome fasta:https://i5k.nal.usda.gov/sites/default/files/temp/GCF_013357705.1_ASM1335770v1_genomic.fna.gz
gff: https://i5k.nal.usda.gov/sites/default/files/temp/cheins_for_chado.gff

We've loaded these files successfully with the gff3 importer from the 7.x-3.x branch. 

and ran into the following error at the property insertion step: 

```
Opening /data/GFFLoader/cheins_for_chado.gff
Step 1: Preloading GFF3 file...                       
Step 2: Load landmarks sequences...                       
Step 3: Find existing features...                         
Step 4: Prepare for any updates ...                       
Step 5: Loading 343273 features...                 
Step 6: Get new feature IDs...                            
Step 7: Loading locations...                              
Step 8: Loading properties...                             
SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

Looking at the database logs, here's an example of what the loader was trying to do:
Example gff3 line: `NW_023276341.1	Gnomon	gene	6139	10868	.	-	.	Alias=gene-LOC118070384;ID=LOC118070384;Dbxref=GeneID:118070384;Name=LOC118070384;gbkey=Gene;gene=LOC118070384;gene_biotype=protein_coding`

Database error statement (this is just one of many: 
```
2020-09-21 14:46:19.941 EDT [12038] tripal@tripal_i5k ERROR:  null value in column "type_id" violates not-null constraint
2020-09-21 14:46:19.941 EDT [12038] tripal@tripal_i5k DETAIL:  Failing row contains (9507166, 10459101, null, LOC118070384, 0).
2020-09-21 14:46:19.941 EDT [12038] tripal@tripal_i5k STATEMENT:  INSERT INTO chado.featureprop (feature_id, type_id, value, rank) VALUES ('10459101', '74603', 'Gene', '0'), ('10459101', NULL, 'LOC118070384', '0'),('10459101', '74604', 'protein_coding', '0'),
```

It looks like the loader is having trouble (not just with this feature, but many) with the 'gene' cvterm. However, this cvterm exists in the database:
```
SELECT * FROM "chado"."cvterm" WHERE "name" = 'gene';
289	14	gene	A region (or regions) that includes all of the sequence elements necessary to encode a functional transcript. A gene may include regulatory regions, transcribed regions and/or other functional sequence regions. [SO:immuno_workshop]	332	0	0
74621	8	gene		335727	0	0
```
and
```
tripal_i5k=> select * from chado.cv where cv_id=8;
 cv_id |       name       |                            definition                            
-------+------------------+------------------------------------------------------------------
     8 | feature_property | A local vocabulary that contains properties for genomic features
(1 row)
```

We are not sure why the new loader can't tell that this cvterm exists. It seems like it loads everything else. Any pointers?


For reference, here is how the gff3 job was set up:

gff form

**Comment by mpoelchau** [comment]
Another possible issue: when we first tried loading this gff3 file, we got the following error:

```
Opening /data/GFFLoader/cheins_for_chado.gff
Step 1: Preloading GFF3 file...                       
Step 2: Load landmarks sequences...                       
The landmark (reference) sequence, NW_023276341.1, is not in the database and not specified in the GFF3 file. Please either pre-load the landmark sequences or set a "Landmark Type" in the GFF importer.
```

This error goes away after selecting 'supercontig' as the landmark type in the loader. However, we never needed to this before (with the T2 gff3 loader or the loader from the the 7.x-3.x branch), and it shouldn't be needed since the supercontig features already exist in the database. The documentation in the loader states "Optional. Use this field to specify a Sequence Ontology type for the landmark sequences in the GFF fie (e.g. 'chromosome'). If the GFF file contains a '##sequence-region' line that describes the landmark sequences to which all others are aligned and a type is provided here then the features will be created if they do not already exist. If they do exist then this field is not used."

```
tripal_i5k=> select name,uniquename,type_id from chado.feature where uniquename='NW_023276341.1';
      name      |   uniquename   | type_id 
----------------+----------------+---------
 NW_023276341.1 | NW_023276341.1 |     386
(1 row)

tripal_i5k=> SELECT cvterm_id,cv_id,name FROM chado.cvterm WHERE "cvterm_id" = '386';
 cvterm_id | cv_id |    name     
-----------+-------+-------------
       386 |    14 | supercontig
(1 row)
```

**Comment by spficklin** [comment]
Hi @mpoelchau . Just to confirm... on your second post. The landmark sequences were already in the database and the loader still said they were missing?

**Comment by spficklin** [comment]
Thanks @mpoelchau for reporting the errors on inserting the  properties. I'll download those two GFF files and see if I can reproduce the problem.  Thanks for testing!

**Comment by mpoelchau** [comment]
Right. The landmark sequences were already in the database;  but the loader states `The landmark (reference) sequence, NW_023276341.1, is not in the database and not specified in the GFF3 file. Please either pre-load the landmark sequences or set a "Landmark Type" in the GFF importer.`

**Comment by spficklin** [comment]
@mpoelchau and @Ferrisx4 . I was able to reproduce both problems you mentioned with the GFF file you gave (thanks for including the link).  I have just pushed an update to the code that should get you past the two problems. After the fixes, I've tested loading the GFF file and it loaded just fine in about 3 minutes and 3.2GB RAM.

**Comment by Ferrisx4** [comment]
@spficklin thanks, I was able to load the GFF with the new code from the branch to completion and with similar performance. I left the Landmark Type field empty.

**Comment by spficklin** [comment]
@Ferrisx4 great!  If you have any more GFF files to test and load that would be great.  This is such a critical piece of Tripal that I just want to make sure it gets a thorough testing.

**Comment by mpoelchau** [comment]
Thanks for the fixes @spficklin! I can contribute more files for testing but not for the next 2 weeks or so...

**Comment by Ferrisx4** [comment]
I ran the GFF loader with a few more examples from TreeGenes:

Testing the Kandelia obovata (Mangrove) [genome](https://treegenesdb.org/FTP/Genomes/Kaob/v1.0/genome/Kaob.1_0.fa.gz) and [gff](https://treegenesdb.org/FTP/Genomes/Kaob/v1.0/annotation/Kaob.1_0.gff.gz) files - GFF load took 41 seconds.

Testing the Corylus avellana (Common hazel) [genome](https://treegenesdb.org/FTP/Genomes/Coav/v1.0/genome/Coav.1_0.fa.gz) and [gff](https://treegenesdb.org/FTP/Genomes/Coav/v1.0/annotation/Coav.1_0.gff.gz) - GFF load failed with the new GFF loader but also the current 7.x-3.x version. It seems to be a parsing issue, perhaps the file needs to be examined. Error:
```Attribute is not correctly formatted on line <em class="placeholder">22</em>: <em class="placeholder">g3</em>```

Testing the Juglans intermedia (hybrid walnut), also from [TreeGenes](https://treegenesdb.org/FTP/Genomes/Juit/v1.0/), with a small customized fasta file to populate the feature table with the appropriate names. GFF size is 238MB and took just under 5 minutes and maxed at almost 11GB RAM.

**Comment by spficklin** [comment]
Hi @Ferrisx4 thanks for testing more files.  So, I tried the Corylus avellana  and the problem with that file is that it is in GFF2 format, not GFF3. The parser only supports GFF3.  I'm not sure we want to support both GFF2 and GFF3 formats with the loader.  Any chance you can convert that file to a GFF3 format?

**Comment by mpoelchau** [comment]
Those files are just for testing - probably easier just to pick a different file.

**Comment by Ferrisx4** [comment]
Yes indeed, I just picked a few random ones from TreeGenes, except for the Juglans intermedia which I chose for its size.

**Comment by spficklin** [comment]
Hi @Ferrisx4.  I just pushed a fix to the loader that reduces memory usage for large files.   I was able to load that _Juglans intermedia_ file using only 2.5GB of RAM (instead of the 11 it was using before).  If you'd like to try that one again and see if you're getting similar behavior.  I have 5GB GFF from Flybase that I'm going to test soon... but it has issues I've got to deal with first. If you have a super larger GFF file to test that would be great too.

**Comment by spficklin** [comment]
Hi all. I'm going to move this discussion over to the #1040 issue rather than this closed PR.  Check for my update on this issue over there.

**Pull request merged**
