### PR TITLE
New Default Content Types

### PR DESCRIPTION
**Pull request by spficklin**
Issue #441 and #527 

## Type(s) of Change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

As per our recent discussions in the Tripal User's Meeting and in the Slack #PMC channel this PR adds new default content types to services most of Chado.  It also updates the 'Add Tripal Content' page to order the content types by categories.

## Testing?

To this this PR

1)  This test has an update function for tripal_chado.  If you do not want to apply the update now (so that you can apply it off the 7.x-3.x branch) then you can run this command:
```
drush php-eval 'module_load_include("install", "tripal_chado", "tripal_chado"); tripal_chado_update_7330()'
```
2)  To add the new content types you must prepare chado again. It won't harm your setup to do so.

3)  Go to the "Add Tripal Content" page and you should see all of the content types (new and old) organized by category.

## Screenshots (if appropriate):
Screenshot of the updated "Add Tripal Content" page.

image

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Hello @spficklin 

When I attempted to run `drush updatedb`, I got errors about missing cvterms. Are there required ontologies to load before testing this?

```bash
$ drush updatedb
 Tripal_chado  7330  Associates categories with content types.
Do you wish to run all pending updates? (y/n): y
WD tripal_chado: Could not find bundle with term accession:          [error]
NCIT:C47885
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: NCIT:C47885
WD tripal_chado: Could not find bundle with term accession:          [error]
SIO:001066
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: SIO:001066
WD tripal_chado: Could not find bundle with term accession:          [error]
local:contact
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: local:contact
WD tripal_chado: Could not find bundle with term accession: sep:00101[error]
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: sep:00101
WD tripal_chado: Could not find bundle with term accession: data:1280[error]
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: data:1280
WD tripal_chado: Could not find bundle with term accession:          [error]
NCIT:C16223
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: NCIT:C16223
WD tripal_chado: Could not find bundle with term accession:          [error]
operation:0525
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: operation:0525
WD tripal_chado: Could not find bundle with term accession:          [error]
operation:0362
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: operation:0362
WD tripal_chado: Could not find bundle with term accession:          [error]
local:Genome Project
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: local:Genome Project
WD tripal_chado: Could not find bundle with term accession: data:1278[error]
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: data:1278
WD tripal_chado: Could not find bundle with term accession:          [error]
SO:0000771
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: SO:0000771
WD tripal_chado: Could not find bundle with term accession:          [error]
SO:0001060
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: SO:0001060
WD tripal_chado: Could not find bundle with term accession:          [error]
SO:0001645
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: SO:0001645
WD tripal_chado: Could not find bundle with term accession:          [error]
SO:0001500
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: SO:0001500
WD tripal_chado: Could not find bundle with term accession:          [error]
CO_010:0000044
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: CO_010:0000044
WD tripal_chado: Could not find bundle with term accession:          [error]
CO_010:0000255
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: CO_010:0000255
WD tripal_chado: Could not find bundle with term accession:          [error]
CO_010:0000029
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: CO_010:0000029
WD tripal_chado: Could not find bundle with term accession:          [error]
CO_010:0000162
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: CO_010:0000162
WD tripal_chado: Could not find bundle with term accession:          [error]
OBI:0000070
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: OBI:0000070
WD tripal_chado: Could not find bundle with term accession:          [error]
EFO:0000269
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not find bundle with term accession: EFO:0000269
Performed update: tripal_chado_update_7330                           [ok]
```

Thanks!

**Comment by almasaeed2010** [comment]
On the other hand, I do see the changes reflected on my admin panel:

download

I don't see anything missing or any other errors.

Thanks!

**Comment by spficklin** [comment]
Hi @almasaeed2010 I forgot to give the testing instructions... Sorry about that. I've added it now..  But it looks like you figured it out.  I think that error message appeared because you didn't have those bundle types.   I will try to add a fix for those warning messages. You got them because you don't have the bundle types... which you shouldn't if you haven't run prepare again.

**Comment by spficklin** [comment]
Let's wait to merge this in until after PR #616 gets merged.  After that gets merged then I have to updated this branch so that the new content types that use the prop tables have the correct type_ids.

**Review by almasaeed2010 — APPROVED** [review]

**Comment by spficklin** [comment]
Fixed the merge conflicts and removed the "On Hold" this is now ready for merging as other dependent PRs have been merged.... and of course after testing.

**Comment by spficklin** [comment]
@almasaeed2010 I fixed the issue with the warnings with the most recent commit.

Also, for anyone else willing to review, this is now ready for review given all other dependent PRs are merged!

**Comment by spficklin** [comment]
Adding the reviewer 1 approval label due to positive review from @almasaeed2010

**Review by laceysanderson — CHANGES_REQUESTED** [review]
- Updating: no errors 👍 
 - Preparing to add the new content types: no errors and worked perfectly 👍 
 - Add content page shows all Tripal content types nicely categorized 😞 

I can confirm the new types are available at Structure > Tripal Content Types:
screen shot 2018-08-31 at 10 03 20 pm

However, when I go to "Add Tripal Content", I don't see the new types 😞 Also, the ordering of the text vs. the fieldsets is off and ideally the fieldsets would be expanded by default.
screen shot 2018-08-31 at 10 03 07 pm

**Comment by spficklin** [comment]
Thanks @laceysanderson .  

**Fixed**:  I've adjusted the code so that the categories are not collapsed by default.  If you re-pull you should see the change.

**Fixed**:  I've added weights to all of the fieldsets and instruction text so hopefully they will now be in order for you.

Also, it is bizarre that you would see the content types on the Tripal Content Types page and not on the Add Tripal Content page...  At first I thought it may have been a permissions issue and then I realized that permission weren't being checked at all!! So, I added a permissions check as well.   Now users who don't have the "create" permission for a content type won't see it in the list.  But that doesn't explain why you wouldn't see the new content types.  The way that page is built is that it queries for all the bundle types and then iterates through them.  Can you run this SQL statement to see what you get back:

```
    SELECT TB.id, TB.label, TBV.value as category, TV.name as variable_type, TV.description
    FROM tripal_bundle TB
      LEFT JOIN tripal_bundle_variables TBV on TB.id = TBV.bundle_id
      LEFT JOIN tripal_variables TV on TV.variable_id = TBV.variable_id
    WHERE TV.name = 'bundle_category'
    ORDER BY TBV.value, TB.label 
```

**Comment by laceysanderson** [comment]
- [x] love the expanded fieldsets 👍 
- [ ] still not seeing the right order: shouldn't general come first?
![screen shot 2018-09-04 at 12 37 21 pm](https://user-images.githubusercontent.com/1566301/45050728-4f9e4200-b03f-11e8-9ddd-2b5959a8ca4a.png)

Results 
```sql
psql =#SELECT TB.id, TB.label, TBV.value as category, TV.name as variable_type, TV.description
    FROM tripal_bundle TB
      LEFT JOIN tripal_bundle_variables TBV on TB.id = TBV.bundle_id
      LEFT JOIN tripal_variables TV on TV.variable_id = TBV.variable_id
    WHERE TV.name = 'bundle_category'
    ORDER BY TBV.value, TB.label;

 id |       label       |  category  |  variable_type  |                   description                    
----+-------------------+------------+-----------------+--------------------------------------------------
  8 | Biological Sample | Expression | bundle_category | Bundles can be categorized to allow for grouping
  2 | Analysis          | General    | bundle_category | Bundles can be categorized to allow for grouping
  5 | Publication       | General    | bundle_category | Bundles can be categorized to allow for grouping
  1 | Species           | General    | bundle_category | Bundles can be categorized to allow for grouping
  6 | Gene              | Genomic    | bundle_category | Bundles can be categorized to allow for grouping
  9 | Phylogenetic Tree | Genomic    | bundle_category | Bundles can be categorized to allow for grouping
  7 | mRNA              | Genomic    | bundle_category | Bundles can be categorized to allow for grouping
(7 rows)

psql =# SELECT TB.id, TB.label, TBV.value as category, TV.name as variable_type
      FROM tripal_bundle TB
      LEFT JOIN tripal_bundle_variables TBV on TB.id = TBV.bundle_id
      LEFT JOIN tripal_variables TV on TV.variable_id = TBV.variable_id;

  id |                label                 |                                                                                                     
                                                       category                                                                                  
                                                                           |  variable_type   
----+--------------------------------------+-----------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------+------------------
  1 | Species                              | A material entity that is an individual living system, such as animal, plant, bacteria or virus, tha
t is capable of replicating or reproducing, growth and maintenance in the right environment. An organism may be unicellular or made up, like huma
ns, of many billions of cells divided into specialized tissues and organs. | description
  1 | Species                              | hide                                                                                                
                                                                                                                                                 
                                                                           | hide_empty_field
  1 | Species                              | [taxrank__genus] [taxrank__species] [taxrank__infraspecific_taxon,TAXRANK:0000045]                  
                                                                                                                                                 
                                                                           | title_format
  1 | Species                              | organism/[TripalEntity__entity_id]                                                                  
                                                                                                                                                 
                                                                           | url_format
  1 | Species                              | General                                                                                             
                                                                                                                                                 
                                                                           | bundle_category
  2 | Analysis                             | General                                                                                             
                                                                                                                                                 
                                                                           | bundle_category
  5 | Publication                          | General                                                                                             
                                                                                                                                                 
                                                                           | bundle_category
  6 | Gene                                 | Genomic                                                                                             
                                                                                                                                                 
                                                                           | bundle_category
  7 | mRNA                                 | Genomic                                                                                             
                                                                                                                                                 
                                                                           | bundle_category
  9 | Phylogenetic Tree                    | Genomic                                                                                             
                                                                                                                                                 
                                                                           | bundle_category
  8 | Biological Sample                    | Expression                                                                                          
                                                                                                                                                 
                                                                           | bundle_category
 20 | QTL                                  |                                                                                                     
                                                                                                                                                 
                                                                           | 
 25 | Generated Germplasm (breeding Cross) |                                                                                                     
                                                                                                                                                 
                                                                           | 
 26 | Cultivar (germplasm Variety)         |                                                                                                     
                                                                                                                                                 
                                                                           | 
 27 | Recombinant Inbred Line              |                                                                                                                                                                                                                                                                                                                                 | 
 11 | Study                                |                                                                                                                                                                                                                                                                                                                                 | 
 17 | Genome Annotation                    |                                                                                                                                                                                                                                                                                                                                 | 
 12 | Contact                              |                                                                                                                                                                                                                                                                                                                                 | 
 10 | Project                              |                                                                                                                                                                                                                                                                                                                                 | 
 18 | Genome Project                       |                                                                                                                                                                                                                                                                                                                                 | 
 15 | DNA Library                          |                                                                                                                                                                                                                                                                                                                                 | 
 13 | Protocol                             |                                                                                                                                                                                                                                                                                                                                 | 
 21 | Sequence Variant                     |                                                                                                                                                                                                                                                                                                                                 | 
 19 | Genetic Map                          |                                                                                                                                                                                                                                                                                                                                 | 
 24 | Germplasm Accession                  |                                                                                                                                                                                                                                                                                                                                 | 
 28 | Assay                                |                                                                                                                                                                                                                                                                                                                                 | 
 29 | Assay Design                         |                                                                                                                                                                                                                                                                                                                                 | 
 16 | Genome Assembly                      |                                                                                                                                                                                                                                                                                                                                 | 
  4 | Map                                  |                                                                                                                                                                                                                                                                                                                                 | 
 23 | Heritable Phenotypic Marker          |                                                                                                                                                                                                                                                                                                                                 | 
 22 | Genetic Marker                       |                                                                                                                                                                                                                                                                                                                                 | 
  3 | Project                              |                                                                                                                                                                                                                                                                                                                                 | 
 14 | Physical Map                         |                                                                                                                                                                                                                                                                                                                                 | 
(33 rows)
```

Looks like I don't have a category or variable_type set?

**Comment by almasaeed2010** [comment]
I tested this again since I haven't re-prepared chado to see the new content types (instructions were added later). I got the following error when running the `prepare chado` job:

```
ERROR (TRIPAL_CHADO): chado_insert_record; Cannot insert duplicate record into cvterm table: Array
(
    [cv_id] => 7
    [name] => part of
    [definition] => 
    [dbxref_id] => 99244
    [is_obsolete] => 0
    [is_relationshiptype] => 1
)

[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_insert_record; Cannot insert duplicate record into cvterm table: Array(    [cv_id] => 7    [name] => part of    [definition] =>     [dbxref_id] => 99244    [is_obsolete] => 0    [is_relationshiptype] => 1)
[site http://default] [TRIPAL WARNING] [TRIPAL_CV] Failed to insert the relationship term: part of (cv: tripal_contact db: TContact)
Exception: Cannot add the term part_of in /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc:898
Stack trace:
#0 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(668): OBOImporter->processTerm(Array, 'tripal_contact', 1, 'TContact')
#1 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(628): OBOImporter->loadTypeDefs(Object(stdClass), 'TContact')
#2 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(493): OBOImporter->loadOBO_v1_2('//Users/Almsaee...', 'Tripal Contact')
#3 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(457): OBOImporter->loadOBO_v1_2_file('Tripal Contact', '//Users/Almsaee...', 0)
#4 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(403): OBOImporter->loadOBO_v1_2_id(Object(stdClass))
#5 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc(133): OBOImporter->run()
#6 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc(195): tripal_chado_load_ontologies()
#7 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal/includes/TripalJob.inc(325): tripal_chado_prepare_chado(Object(TripalJob))
#8 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal/api/tripal.jobs.api.inc(421): TripalJob->run()
#9 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal/tripal.drush.inc(232): tripal_launch_job(0, '62', -1, 0)
#10 phar:///usr/local/bin/drush/includes/command.inc(422): drush_tripal_trp_run_jobs()
#11 phar:///usr/local/bin/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#12 phar:///usr/local/bin/drush/includes/command.inc(199): drush_command()
#13 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#14 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 phar:///usr/local/bin/drush/includes/startup.inc(462): drush_main()
#16 phar:///usr/local/bin/drush/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#17 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#18 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#19 {main}
Job execution failed: Exception: Cannot add the term part_of in                                                                                                        [error]
/Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc:898
Stack trace:
#0 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(668): OBOImporter->processTerm(Array,
'tripal_contact', 1, 'TContact')
#1 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(628): OBOImporter->loadTypeDefs(Object(stdClass),
'TContact')
#2 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(493):
OBOImporter->loadOBO_v1_2('//Users/Almsaee...', 'Tripal Contact')
#3 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(457): OBOImporter->loadOBO_v1_2_file('Tripal
Contact', '//Users/Almsaee...', 0)
#4 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(403):
OBOImporter->loadOBO_v1_2_id(Object(stdClass))
#5 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc(133): OBOImporter->run()
#6 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc(195): tripal_chado_load_ontologies()
#7 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal/includes/TripalJob.inc(325): tripal_chado_prepare_chado(Object(TripalJob))
#8 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal/api/tripal.jobs.api.inc(421): TripalJob->run()
#9 /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal/tripal.drush.inc(232): tripal_launch_job(0, '62', -1, 0)
#10 phar:///usr/local/bin/drush/includes/command.inc(422): drush_tripal_trp_run_jobs()
#11 phar:///usr/local/bin/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#12 phar:///usr/local/bin/drush/includes/command.inc(199): drush_command()
#13 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#14 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 phar:///usr/local/bin/drush/includes/startup.inc(462): drush_main()
#16 phar:///usr/local/bin/drush/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#17 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#18 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#19 {main}
```

Seems like we need to add a check before we insert?

Thanks!

**Comment by spficklin** [comment]
@laceysanderson the bundle_category gets added in the update:  tripal_chado_update_7330.  With all of the PR reviews you've done maybe your module got ahead.   Try running this and then reloading:

```
drush php-eval "module_load_include('install', 'tripal_chado', 'tripal_chado'); tripal_chado_update_7330()"
```
However, before you do that I'll add a fix to try and prevent this problem from happening as this may inadvertently happen again.  And if you don't mind I'd like you to test it on your current setup before applying the update.

In terms of the ordering, do we want General at the top and open and the rest below and collapsed?  I thought it would seem funny if everything was in alphabetical order except general.  And to me general isn't any more important than any other...  But if you feel strongly that it should be at the top I can make it be so.

**Comment by spficklin** [comment]
@almasaeed2010 what part of the prepare did you see those errors?  Was it in ontology loading? If so, I think the OBO loader updates in #627 might help resolve those.

**Comment by laceysanderson** [comment]
I do feel strongly that General should be at the top :shrugs: Also, I assume fieldsets only appear if there are content types in them? For example, if I delete the Biological Sample type then the Expression fieldset will disappear?

As far as testing, I'll hold off until you tell me what to do :-)

**Comment by spficklin** [comment]
@laceysanderson I've made the fixes you requested. Specifically:

1)  The General fieldset comes at the top
2)  Fieldsets with no content types don't appear.
3)  All fieldsets are open
4)  Ordering problems should be fixed.
5)  Content types without bundle_variable category show up in "Other" and are not missing.  But, after you apply the update then those content types should move to the right category.

**Review by laceysanderson — APPROVED** [review]
Thanks @spficklin. I couldn't test on my original dev site since c9 is currently down. In the meantime, I testing on one of my KP dev sites and confirmed all of your fixes worked 🎉 👍 

- [x] The General fieldset comes at the top
- [x] Fieldsets with no content types don't appear.
- [x] All fieldsets are open
- [x] Ordering problems should be fixed.
- [x] Content types without bundle_variable category show up in "Other" and are not missing.
- [x] Applying the update adds the catagories so existing content types are sorted into the correct fieldsets.

**Comment by laceysanderson** [comment]
Removed @almasaeed2010 approval since he's currently troubleshooting some newly discovered issues.

**Comment by laceysanderson** [comment]
Update, I was able to test on my original dev site and everything worked beautifully there too 🎉 Additionally, I confirmed the update adds categories correctly to existing but re-labelled content types (e.g. My ever-problematic `Species`). So that's a 👍 👍 from me!

**Comment by spficklin** [comment]
@almasaeed2010 I was able to duplicate the problem you experienced.  The error occurs when reloading the ontologies during prepare.  That puzzles me because it is not supposed to reload ontologies if they are already loaded:

https://github.com/tripal/tripal/blob/76caa3b65d8b56de9394525123d81394f066b416/tripal_chado/includes/setup/tripal_chado.setup.inc#L122-L140

However, I do recall that I repeatedly had this problem in the past where the TContact ontology would get reloaded on every prepare.  That got fixed in a previous PR and the code above is correct.  So, what I think happened is that you had an incorrect name for the CV for the TContact ontology in your cv table.  That triggered the code above to try and reload it on prepare and failed because it was already loaded and the old OBO Importer (not the one in #627) has problems.   

So, I suspect if you prepare again you will not get that error because the CV name will now be corrected and the content types will be created.  Can you give it a try?

**Comment by bradfordcondon** [comment]
didnt a seperate active PR rename the tripal contact ontology from TContact to TCONTACT ?  (edit: looks like it was just the shortname.  probably irrelevant).  If he was testing it, would that be problematic?

**Comment by almasaeed2010** [comment]
Hello @spficklin 

I pulled the latest changes on the same server that gave me the error and reran the prepare job. This time around I didn't get any errors. Has the problem been fixed?

And you are right that the cv that was causing the issue was Tripal_contact:

```
select * from chado.cv where cv_id = 7;
7	tripal_contact	Tripal Contact Ontology. A temporary ontology until a more formal appropriate ontology an be identified.
```

Do we need to account for that for our other sites that have been previously prepared?

**Comment by spficklin** [comment]
@almasaeed2010 the problem was unrelated to this PR. I think it's aside effect from all of our fixes but it only happens once and we can't duplicate it.  This should only be a problem, if at all, for existing Tripal 3 sites so in general I don't think it shouldn't be an issue for new adopters.  If you ran your test and things worked then I think this PR is good to be merged and if someone has the problem we encountered we just let them know to re-run the prepare.

@bradfordcondon yes, there was a change from TContact to TCONTACT but that was in the new OBO loader PR which hasn't yet been committed.

**Comment by almasaeed2010** [comment]
Sounds good to me @spficklin. I didn't see any other issues popup and everything worked fine after running it again so I believe we are good to go here.

Thanks!

**Comment by spficklin** [comment]
Okay, Thanks! @almasaeed2010 and @laceysanderson and @bradfordcondon . Merging now.

**Pull request merged**
