### PR TITLE
Functional Docs for the User's Guide:  Setup and Blast.

### PR DESCRIPTION
**Pull request by spficklin**
# Documentation

Issue #689 

**NOTE**: This PR should not be merged until The Tripal Analysis Blast module has a valid Tripal v3 release.

## Description

This PR only adds new documentation to the User's Guide.  It adds:
1. The structure for the functional annotation steps for the User's Guide
2.  And a completed page for importing BLAST results.
3.  It moves the "Working with Content Types" before the "Setup Example Genomics Site" because it's necessary that folks understand how to work with content types before loading functional data.

it lacks the Interpro, KEGG and GO modules. 

## Testing?

N/A  Just Read the Docs

Can be view in the built form at :  https://tripal.readthedocs.io/en/689-tv3-docs/user_guide/example_genomics/func_annots.html

## Screenshots (if appropriate):

image

image

### CODE REVIEW

**Comment by bradfordcondon** [comment]
```
The top section of this page provides multiple methods for providing results file: via an upload interface, specifying a remote URL or a file path that is local to the server.  Most likely, you will always upload or provide a remote URL.  However, we downloaded the files earlier, and stored them here: ```$DRUPAL_HOME/sites/default/files```.  So, in this case we can use the path on the local server.  Provide the following value for this form:

```

this is going to go in pretty much all of them.  want to factor it out?

**Comment by bradfordcondon** [comment]
hi all.

I'm tagging this as ready for review.  It's a collab between me and stephen so i dont know if that means it needs only 1 review or not. 

Anyway, we have docs for 

* general funcftional annotation setup
* BLAST
* IPR

we dont have it for
* GO
* KEGG

but given that this has been slow going, and we have some roadblocks for the other modules, i'm asking that we merge as is.

I've gone ahead and built the docks on this pr's branch so you can more easily review: its available here:
https://tripal.readthedocs.io/en/689-tv3-docs/user_guide/example_genomics/func_annots.html

**Comment by spficklin** [comment]
As this is really needed by a few folks who requested documentation and it can be easily edited later, and it's just documentation I vote we merge.

**Review by laceysanderson — APPROVED** [review]
I gave it a quick scan and the docs look good to me!

**Comment by bradfordcondon** [comment]
merging with lacey's readthrough.  No one will be offended if typos are fixed down the road :) . thanks everybody.

**Pull request merged**
