### PR TITLE
Added array design field

### PR DESCRIPTION
**Pull request by spficklin**
Issue #432 

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

This PR adds a new efo__array_design field that gives support to the Assay content type for setting the array design.   It also fixes a bug in the local__contact field when adding a new content type.
## Testing?

1)  If you do not have an Assay content type then you should create one.  Use the term 'assay', and all records of this type map to the table 'assay' of Chado.
2)  If you do have an Assay content you will need to go to the Content Type page for Assay delete the field 'Array Design' , and then click the link to check for new fields.  The Array Design field should come back.
3)  if you do not have an Array design content type you should create one. using the term 'array design' and all records of this type map to the table 'arraydesign' of Chado.  Then create a new Array design entity (page).
4)  Create a new Assay entity (page).  On the form, the Array Design element should be a select box that lists the assays.  You can select one, fill out the other fields and save the entity.  
5)  Now that the entity exists, tests editing it, and saving. If you have another Assay Design to change that would be a good thing to test changing.
6) Test that the array design shows up in web services.  Go to your site's web-services and navigate to the Assay you added (using a JSON viewer in the browser helps navigate easily).  You should see the array design name in the assay.
7) You should be able to search for your Assay using the array design name from a web services query like this:  http://[tripal_site]/web-services/content/v0.1/Assay?array_design,name=[array_design_name].  Experiment with changing the value of [array_design_name] to ensure that you see no results.
8) You can test searching for the Assay using the array design in the Views based searches that Tripal creates for each content type.  Go to http://[tripal_site]/data_search/assay, click the link when you mouse over the upper right of the form to edit the view.  Add the assign design name field as an exposed filter.  Save the view.  You should now be able to search for your assay using the array design name.  Experiment with correct and incorrect names to make sure the search is fully working.

Doing all of this also tests the bug with the local__contact field.  If you are able to save the Assay without any errors then it works. 

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by bradfordcondon — COMMENTED** [review]
All functionality tested and confirmed.  🐲 


At first I was annoyed that array_design is required but Chado does require it (we just create a "NULL" array_design to associate).

👍

**Review by bradfordcondon — APPROVED** [review]

**Comment by laceysanderson** [comment]
Confirmed this worked as described :-) I did have to re-prepare my chado to ensure I had the appropriate cvterms but after that, all worked beautifully.

**Comment by laceysanderson** [comment]
Resolved merge conflict and re-tested quickly. All is still well, just waiting for Travis CI to confirm checks pass ;-)

PS. Feel free to merge if you see this issue still open and Travis CI has completed successfully.

**Comment by spficklin** [comment]
Thanks!

**Pull request merged**
