### PR TITLE
Tripal 4 Chado Unit field tv4g1-issue1414-uo__unit

### PR DESCRIPTION
**Pull request by pdtouch**
…_10_19_2023_tv4g1-issue1414-uo__unit

# New Feature

## Description
Create a unit field for use on featuremap content types (Genetic Map, Physical Map)

### CODE REVIEW

**Review by dsenalik — CHANGES_REQUESTED** [review]
I created a docker and the field is working. I created a genetic map
map-one
```
sitedb=> select M.*, T.name from chado.featuremap M left join chado.cvterm T on M.unittype_id=T.cvterm_id;
 featuremap_id |  name   |  description  | unittype_id |   name   
---------------+---------+---------------+-------------+----------
             1 | Map One | Description 1 |         100 | bin_unit
(1 row)
```
Then I edited it and saved
map-edited
```
sitedb=> select M.*, T.name from chado.featuremap M left join chado.cvterm T on M.unittype_id=T.cvterm_id;
 featuremap_id |  name   |  description  | unittype_id | name 
---------------+---------+---------------+-------------+------
             1 | Map Two | Description 2 |          99 | bp
(1 row)
```

Changes to make
 [ ] Line 14 of formatter, I think the description should be more generic, change to
 The default unit widget which allows curators to enter unit on the featuremap content edit page.
 [ ] Remove commented out line 30 in the formatter
 [ ] Lines 32..38 - remove the hardcoded cv_id and (1 == 1) condition, and replace with appropriate join and updated condition, e.g.
```
      $query->leftJoin('cv', 'cv', 'cvt.cv_id = cv.cv_id');
      $query->condition('cv.name', 'featuremap_units', '=');
```
 [ ] line 61 the #placeholder line can be removed. Stephen brought this up for one of my fields https://github.com/tripal/tripal/pull/1578#issuecomment-1672379611 , this is never given a value, so it doesn't do anything and can be deleted.

**Comment by pdtouch** [comment]
Regarding requested changes:
Does this look reasonable for the formatter description:
"Chado unit formatter for default unit widget which allows curators to enter unit on the featuremap content edit page". ?

**Comment by dsenalik** [comment]
Good point. But for the formatter I would remove the widget reference. I am looking at all of the fields and I see some formatters also reference the widget, but that will be a separate issue.
For consistency with other fields, how about just this:
"A Chado unit type formatter"

**Review by dsenalik — APPROVED** [review]

**Comment by dsenalik** [comment]
I'm sorry but I did test one more time, and there is an error if you fail to select a unit (see below)

Can you please add this code at the bottom of the widget
```
  /**
   * {@inheritDoc}
   */
  public function massageFormValues(array $values, array $form, FormStateInterface $form_state) {
   // Remove any empty values that don't have a unit type
    foreach ($values as $delta => $item) {
      if ($item['unittype_id'] == '') {
        unset($values[$delta]);
      }
    }
    return $values;
  }
```

The website encountered an unexpected error. Please try again later.

Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "" LINE 4: WHERE "cvterm_id" = '' ^: SELECT "fk"."cvterm_id" AS "cvterm_id" FROM "cvterm" "fk" WHERE "cvterm_id" = :db_condition_placeholder_0; Array ( [:db_condition_placeholder_0] => ) in Drupal\tripal_chado\Plugin\TripalStorage\ChadoStorage->validateFKs() (line 1667 of modules/contrib/tripal/tripal_chado/src/Plugin/TripalStorage/ChadoStorage.php).
```
Drupal\Core\Database\StatementWrapperIterator->execute(Array, Array) (Line: 790)
Drupal\Core\Database\Connection->query('SELECT "fk"."cvterm_id" AS "cvterm_id"
FROM
{cvterm} "fk"
WHERE "cvterm_id" = :db_condition_placeholder_0', Array, Array) (Line: 221)
Drupal\pgsql\Driver\Database\pgsql\Connection->query('SELECT "fk"."cvterm_id" AS "cvterm_id"
FROM
{cvterm} "fk"
WHERE "cvterm_id" = :db_condition_placeholder_0', Array, Array) (Line: 525)
Drupal\Core\Database\Query\Select->execute() (Line: 155)
Drupal\pgsql\Driver\Database\pgsql\Select->execute() (Line: 1667)
Drupal\tripal_chado\Plugin\TripalStorage\ChadoStorage->validateFKs(Array, 'featuremap', 0, Array, Array) (Line: 1850)
Drupal\tripal_chado\Plugin\TripalStorage\ChadoStorage->validateValues(Array) (Line: 647)
Drupal\tripal\Entity\TripalEntity->validate() (Line: 188)
Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object)
call_user_func_array(Array, Array) (Line: 82)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object) (Line: 275)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'tripal_entity_physical_map_add_form') (Line: 118)
Drupal\Core\Form\FormValidator->validateForm('tripal_entity_physical_map_add_form', Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('tripal_entity_physical_map_add_form', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 592)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Review by dsenalik — APPROVED** [review]
With this last change this is ready to merge :beetle::hammer:

**Pull request merged**
