### PR TITLE
DRAFT Tripal 3 chado linker fields

### LINKED ISSUE #1318: Tripal fields don't exist for all of the linker tables, e.g. link analysis and project
## Feature Request/Discussion

* This feature does attempt to solve an existing problem with Tripal
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core
* This feature is Not Urgent

### Description
Correct me if I'm wrong, but right now in core tripal, there is not a field to link between project and analysis or even assay. I wrote one for CarrotOmics, but is there a reason this field does not already exist, the table ```project_analysis``` exists, so why not a field for it?

### Your Specific Use Case
Here is an example of linking a project to an analysis and assays
https://www.carrotomics.org/Project/291804
and each of those then has a link back to the project. 

### Generally Applicable
I "overloaded" the field so a project also links to assays for example, and that's why I never finished the widget. Is there a possibility of a more general "linker" field that will just use all linker tables in chado? Sort of like the ```sio__references``` field does for publications? However that field doesn't have a widget so couldn't be used to add links.

### Testing
See https://github.com/tripal/tripal/pull/1319#issuecomment-1329543545

### PR DESCRIPTION
**Pull request by dsenalik**
# New Feature

## Description

This branch will add several new tripal fields to link between content types as described in issue #1318:

| proposed cvterm | field name |
| --- | --- |
| [NCIT:C25391 (Analysis)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C25391)<sup>3,4</sup> | chado_linker__analysis |
| [NCIT:C60819 (Assay)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C60819)<sup>4</sup> | chado_linker__assay |
| [NCIT:C43376 (Biologically-Derived Material)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C43376)<sup>4</sup> | chado_linker__biomaterial |
| local:contact | chado_linker__contact (**existing**) |
| [NCIT:C73619 (Feature)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C73619)<sup>4</sup> | chado_linker__feature |
| EDAM [data:1274 (map)](https://edamontology.github.io/edam-browser/#data_1274) | chado_linker__featuremap |
| [NCIT:C14250 (Organism)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C14250) | chado_linker__organism |
| [NCIT:C47885 (Project)](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C47885) | chado_linker__project |
| [NCIT:C48288 (Stock)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C48288)<sup>4</sup> | chado_linker__stock |
| [NCIT:C63536 (Study)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C63536) | chado_linker__study |

## Testing?

See https://github.com/tripal/tripal/pull/1319#issuecomment-1329543545

### CODE REVIEW

**Comment by dsenalik** [comment]
### Testing

1. Run database update ```7341 - Adds cvterms for new chado_linker__xxx tripal fields.``` with ```drush updatedb``` or at https://your.testing.site/update.php
2. Rebuild menus with https://your.testing.site/devel/menu/reset to get the new administrative form added for step 7.
3. Add new fields to at least one instance of each of the five content types at ```https://your.testing.site/admin/structure/bio_data``` with ```manage fields``` then ```+ Check for new fields```. ~~By default labels are hidden, it helps to set them to "Inline".~~ The fields added depend on the presence of the appropriate linker table, so if a custom linker table exists, the corresponding field will be added.
  * Analysis: Added field: analysis_feature; Added field: analysis_project
  * Assay: Added field: assay_project
  * Gene (feature): Added field: feature_analysis; Added field: feature_project
  * Germplasm Accession (stock): Added field: stock_analysis; Added field: stock_feature; Added field: stock_project
  * Project: Added field: project_analysis; Added field: project_assay; Added field: project_feature; Added field: project_stock
4. Go to a page for each of these content types (note the entity number), and edit it and add one or more links with the appropriate widget, e.g. on an analysis page add a gene and add a project
5. Test deletion also, remove the record in the widget and see that it is deleted.
6. Use the entity numbers from step 3 to test web services for the same pages, e.g. https://your.testing.site/web-services/content/v0.1/Project/123456
7. View a page with numbers of records over the limit. This can temporarily be set low (e.g. reduce from 500 to 2) for testing on the admin page at https://your.testing.site/admin/tripal/storage/chado/field_settings
overlimit


Entities with lots of linked content are timing out in web services, but simpler ones are working.

**Comment by dsenalik** [comment]
The ```mainlab_tripal``` module adds a custom table ```featuremap_stock```
Because of the order of searching, the ```chado_linker__stock``` field uses this one in preference to the base tripal ```stock_featuremap```
The ```chado_linker__stock``` widget crashes on a genetic map content page because I am not getting a schema for this table for some reason.
```
$field_table = 'featuremap_stock';
$schema = chado_get_schema($field_table);
var_dump($schema);
bool(false)
```
Add commit https://github.com/tripal/tripal/pull/1319/commits/1ae41ae401517d74a020d3c69a845b9b20dd80b4 to deal with this, prioritize core tripal tables over mainlab tripal.

**Comment by dsenalik** [comment]
Commit https://github.com/tripal/tripal/pull/1319/commits/d6fd9d25c23747805bf0d8a6f28b278ae82b991e implements an administration form for setting the maximum number of records to display before switching to the summary view.
fieldsettings
Use the devel module /devel/menu/reset to get this new menu item added.

**Comment by dsenalik** [comment]
Commit https://github.com/tripal/tripal/pull/1319/commits/a67e98c9514fb44ec927e6662dea5d9d0eaf3288 makes the maximum displayed height into a configurable value.

max_height

**Comment by spficklin** [comment]
Hey @dsenalik sorry this has sat so long. I  just saw an email come through that a `chado_linker__biomaterial field` field has been added. I'm wondering if that would be better suited for the expression module?

**Comment by dsenalik** [comment]
biomaterial is not limited to expression, it is also used for genome assemblies, etc. Since there are three core linker tables, I feel it is appropriate here, but am open to your more experienced opinion.

**Comment by dsenalik** [comment]
Example, I have this biomaterial linked to an analysis, and need this field to do the reverse link from analysis to biomaterial (plus I define a custom linker table)
https://www.carrotomics.org/biologicalsample/296399

**Comment by dsenalik** [comment]
The majority of the code to implement these new fields will be moved to a new module [chado_linker_fields](https://github.com/tripal/chado_linker_fields)

Some of the code is best kept in core tripal like the api functions for autocompletes.

These changes can be found in pull #1487

The fields themselves, and admin page for setting max_delta will be moved to this new module, and so this pull request is hereby closed.

**Pull request closed without merging**
