### PR TITLE
Tripal 4 change chado storage handling of empty fields

### LINKED ISSUE #1544: Tripal 4 chado storage validation error with form fields where null is allowed
# BUG/ERROR report

### Issue description
We need to fix the organism validation when adding a new organism. If an organism with an infraspecies already exists, we cannot add one without the infraspecies.

#### Steps to reproduce

  1. Create new organism Tripalus databasica subsp. postgresqlulus
  2. Create new organism Tripalus databasica
`Error Message  
The item cannot be saved as another already exists with the following values. Genus: 'Tripalus'. Species: 'databasica'. `

### PR DESCRIPTION
**Pull request by dsenalik**
# Bug Fix

## Description
This PR changes chado storage validation in the particular case of database columns _without_ a NOT NULL constraint, and when the form field is left blank. When this happens, we check for either a NULL or an empty string in that database column instead of comparing to the string that comes from the form field. The current behavior is to just ignore these with a `continue` 🙈. This means, for example, that you can't enter a new organism with no infraspecies if an organism with the same genus+species and has a subsp. exists.

## Testing?
  1. Create a new analysis "Program, Pipeline, Workflow or Method Name" = 3, "Software Version" = 3, "Data Source Name" = 3.
  2. Create a new analysis "Program, Pipeline, Workflow or Method Name" = 3, "Software Version" = 3, "Data Source Name" = left blank. Before this PR this will fail, after this PR it will succeed.

Alternative test
  1. Create new organism "Tripalus databasica subsp. postgresqlulus"
  2. Create new organism "Tripalus databasica" Before this PR this will fail, after this PR it will succeed.

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
I'm getting an error :-(

Specifically,
- Built image based on this branch (Drupal 10.0.x-dev, PHP 8.1)
- Ran a container from this image
- Created an organism only filling in:
    - Genus: Tripalus
    - Species: Databasica
    - Infra Type: subspecies
    - Infra Value: Postgresquelus
- Tried to create an organism with the same genus + species without touching any other fields... This resulted in a WSOD with the following error:

```
The website encountered an unexpected error. Please try again later.

Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "" LINE 4: ... AND ("species" = 'databasica') AND (("type_id" = '') OR ("t... ^: SELECT "ct".* FROM chado.organism "ct" WHERE ("genus" = :db_condition_placeholder_0) AND ("species" = :db_condition_placeholder_1) AND (("type_id" = :db_condition_placeholder_2) OR ("type_id" IS NULL)) AND (("infraspecific_name" = :db_condition_placeholder_3) OR ("infraspecific_name" IS NULL)); Array ( [:db_condition_placeholder_0] => Tripalus [:db_condition_placeholder_1] => databasica [:db_condition_placeholder_2] => [:db_condition_placeholder_3] => ) in Drupal\tripal_chado\Plugin\TripalStorage\ChadoStorage->validateUnique() (line 1141 of modules/contrib/tripal/tripal_chado/src/Plugin/TripalStorage/ChadoStorage.php).

Drupal\Core\Database\StatementWrapper->execute(Array, Array) (Line: 765)
Drupal\Core\Database\Connection->query('SELECT "ct".*
FROM
chado.organism "ct"
WHERE ("genus" = :db_condition_placeholder_0) AND ("species" = :db_condition_placeholder_1) AND (("type_id" = :db_condition_placeholder_2) OR ("type_id" IS NULL)) AND (("infraspecific_name" = :db_condition_placeholder_3) OR ("infraspecific_name" IS NULL))', Array, Array) (Line: 191)
Drupal\pgsql\Driver\Database\pgsql\Connection->query('SELECT "ct".*
FROM
chado.organism "ct"
WHERE ("genus" = :db_condition_placeholder_0) AND ("species" = :db_condition_placeholder_1) AND (("type_id" = :db_condition_placeholder_2) OR ("type_id" IS NULL)) AND (("infraspecific_name" = :db_condition_placeholder_3) OR ("infraspecific_name" IS NULL))', Array, Array) (Line: 525)
Drupal\Core\Database\Query\Select->execute() (Line: 155)
Drupal\pgsql\Driver\Database\pgsql\Select->execute() (Line: 1141)
Drupal\tripal_chado\Plugin\TripalStorage\ChadoStorage->validateUnique(Array, 'organism', 0, Array, Array) (Line: 1395)
Drupal\tripal_chado\Plugin\TripalStorage\ChadoStorage->validateValues(Array) (Line: 716)
Drupal\tripal\Entity\TripalEntity->validate() (Line: 188)
Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object)
call_user_func_array(Array, Array) (Line: 82)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object) (Line: 275)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'tripal_entity_bio_data_1_add_form') (Line: 118)
Drupal\Core\Form\FormValidator->validateForm('tripal_entity_bio_data_1_add_form', Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('tripal_entity_bio_data_1_add_form', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 74)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 686)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by dsenalik** [comment]
I have replicated this error on a docker using same versions.
And on the 4.x branch we still get the previous situation 
`The item cannot be saved as another already exists with the following values. Genus: 'Tripalus'. Species: 'databasica'.`

The problem arises with the `type_id` column, which does not have a NOT_NULL constraint. My new code is attempting to check for an empty string there, but it is an integer type, thus blowing up in my face.

**Comment by dsenalik** [comment]
I wanted to handle this with a `CAST()` to keep the code simpler, but it turns out you can't do that for a dynamic query, an alias from an expression cannot be used in the SELECT. So the fix here is to only do the special check for an empty string on database columns with one of the text types.

**Review by laceysanderson — APPROVED** [review]
Confirmed that the updated version works as expected via manual testing.
I could easily add both an organism and analysis using the same steps outlined in the PR description without validation error on this branch. Also I added a gene and stock for good measure and they added as expected.

I think this can be merged.
(Note: Testing is still too difficult for chadostorage)

**Pull request merged**
