### PR TITLE
Tripal Blast: Request for Gold Badge Status

### PR DESCRIPTION
**Pull request by laceysanderson**
# Documentation

## Description

We are applying for the Gold-level badge for Tripal Blast as we meet the following requirements. I have provided examples below to make review easier.

Repository: https://github.com/tripal/tripal_blast/

## Bronze

| Requirement                                                                              | Status        |
|-------------------------------------------------------------|------------|
| Has a public release.  | [Yes](https://github.com/tripal/tripal_blast/releases)   |
| Should install on a Tripal site appropriate for the versions it supports. |  [Yes](https://www.hardwoodgenomics.org/blast) |
| Defines any custom tables or materialized views in the install file (if applicable). | [Yes](https://github.com/tripal/tripal_blast/blob/7.x-1.x/blast_ui.install#L55)  |
| Adds any needed controlled vocabulary terms in the install file (Tripal3). |  **Not Applicable** (No cvterms needed.) |
| Provides Installation and admin instructions README.md (or RTD). |  [Yes](https://tripal-blast-ui.readthedocs.io/en/latest/user_guide/install.html) |
| Has a license (distributed with module). | [Yes](https://github.com/tripal/tripal_blast/blob/7.x-1.x/LICENSE.txt)  |

## Silver
| Requirement           | Status |
|------------------- |---------------------|
| Follows basic Drupal Coding standards; specifically, code format and API documentation. | Yes |
| Uses Tripal API functions. Specifically, it should use the Chado Query API for querying chado (if using chado as the storage system). | Yes (e.g. [chado.db for linkouts](https://github.com/tripal/tripal_blast/blob/7.x-1.x/includes/blast_ui.node.inc#L230))   |
| Tripal Jobs API for long running processes. |  [Yes](https://github.com/tripal/tripal_blast/blob/7.x-1.x/includes/blast_ui.form_per_program.inc#L556-L562) |
| TripalField class to add data to pages (Tripal3). |  **Not Applicable** |
| Provides ways to customize the module (e.g. drush options, field/formatter settings, admin UI). | Yes (e.g. [admin UI](https://tripal-blast-ui.readthedocs.io/en/latest/user_guide/install.html#configure-tripal-blast), [custom linkouts hook](https://tripal-blast-ui.readthedocs.io/en/latest/dev_guide/custom_linkouts.html)) |
| Latest releases should follow Drupal naming best practices. e.g. first release for Drupal 7 should be: 7.x-1.x. | Yes (e.g. [7.x-1.3](https://github.com/tripal/tripal_blast/releases/tag/7.x-1.3))  |

## Gold
| Requirement  | Status |
|-------------|---------|
| Extensive documentation for the module (similar to Tripal User’s Guide). |  [Yes, RTD](https://tripal-blast-ui.readthedocs.io/en/latest/index.html)|
| Unit testing is implemented using PHPUnit with the TripalTestSuite or something similar. | [Yes, TripalTestSuite](https://github.com/tripal/tripal_blast/tree/7.x-1.x/tests)  |
| Continuous integration is setup (e.g. such as with TravisCI). | [Yes, TravisCI](https://travis-ci.org/tripal/tripal_blast) |
| Imports data via Tripal’s importer class (Tripal3). | **Not Applicable** (doesn't import data) |
| Tripal 3 fields are Fully compatible with web services. | **Not Applicable** (no TripalFields) |
| The elementInfo function is fully implemented. | **Not Applicable** (no TripalFields) |
| The query and queryOrder functions fully implemented. | **Not Applicable** (no TripalFields) |
| Web Services uses Tripal’s Web Service Classes (Tripal3). | **Not Applicable** (no WebServices) |
|  Code sniffing and testing coverage reports (optional but encouraged). | [Yes](https://codeclimate.com/github/tripal/tripal_blast) |
| Drupal.org vetted release (optional but encouraged). | [Yes](https://www.drupal.org/project/tripal_blast) |

NOTE: This PR was made using [the following template](https://gist.github.com/laceysanderson/d4c4534e6ac41ece3063f9b1270d749b).

### CODE REVIEW

**Comment by spficklin** [comment]
Looks great @laceysanderson. I approve.

**Comment by spficklin** [comment]
I forget do these only require one approval?  It's a documentation change, but I just want to make sure.

**Comment by spficklin** [comment]
Okay, no further comments. I'm going to merge.

**Comment by laceysanderson** [comment]
Thanks @spficklin!

**Pull request merged**
