### PR TITLE
Tripal 4 Fields: Sequence Length + Sequence Checksum

### PR DESCRIPTION
**Pull request by srobb1**
# Tripal 4 Core Dev Task

Issue #1414 
### Tripal: 4.x

This is now ready for review however, it is dependant on #1388 as it includes the field created in that PR and makes some specific changes related to these two fields.

@srobb1 could you please fill out this template? Before reviewing a PR it needs to be well described and have some information on how to test it. Thanks!

### CODE REVIEW

**Comment by srobb1** [comment]
This pull request has both length and md5. They seem to be working for me. I still need to learn how to write tests. I think this is ready for someone who knows what they are actually doing to look at it.

**Comment by dsenalik** [comment]
I tried your branch on my bogus test site. I have one gene 28 b.p. long, seqlen column contains 28, MD5 column is null.

~~I added ```TTTT```` to the end, so length should now be 32, but I also typed in an incorrect sequence length, and saved. Well that's already better than the field I am working on, it actually saved! It saved the new sequence, but it went ahead and saved the length incorrectly as the incorrect value I had typed in. And the MD5 was not populated in the table.~~
TB000001
~~I think Stephen said there should not be a seqlen widget, however I wonder about this. You might want to enter a feature with a sequence length, but not actually enter the sequence. Anyway, I think it should only save my sequence length if it matches the residues length, or if residues is null, and otherwise pop up a validation error. I see that if I leave the box empty, there is a validation error "This value should be of the correct primitive type. " I'll look at your code and maybe learn something 🧐~~

~~And I'm not seeing the checksum field on the display or the widget even after I put a checksum in the feature table with sql. But is shows as being in the form.~~

So wait, there was already a sequence and length field, I only had to add your checksum. If I delete the original fields and add your three fields, they function correctly! 
srobb_3

The fields already there may be from ```tripal_chado/config/install/tripal.tripal_content_terms.chado_content_terms.yml```

**Comment by srobb1** [comment]
Ok!! that is good!! I might have actually done it!! I think i need to calculate the length of the md5, I hard code in a size of 32.

**Comment by srobb1** [comment]
Lacey had suggested not creating a Field for md5 but I wanted to make sure that I could make it work. It might be unnecessary. I also added both the default formatter for length and one with commas. @dsenalik, you should try changing the formatter. It is fun to see it work!

Lacey also suggested making a download formatter for sequence. I have no idea how to format a url to download the sequence. I will need to come back to this.

**Comment by laceysanderson** [comment]
## Instructions for Testing

1. Create an organism
2. Go to Tripal > Page Structure > Gene > Manage Fields
3. Delete the existing "Sequence" (bio_data_8_data_2044) and "Sequence Length" (bio_data_8_data_1249).
4. Add the following fields in this order:
    - Chado Sequence Residues
    - Chado Feature Sequence Length
    - Chado Feature Sequence Checksum
5. Then create a gene:
    - Go to Tripal > Content, click "add Tripal Content" and then "Gene"
    - Select an organism, enter an identifier, and then fill in "Sequence" in specific ways to test the field.

**How to add a field:**
On Tripal > Page Structure > Gene > Manage Fields

1. Click "Add field"
2. Select the field name from the "Add a new field" dropdown and enter a label. Click "Save and continue".
3. On the next form, select "feature" as the Chado Base Table and click "Save Field settings".
4. Then on the final page, leave the defaults and click "Save settings".

**Note: There is no widget for the sequence length and sequence checksum fields. Instead the value is calculated based on the sequence residues and then displayed by the formatter.**

**Review by laceysanderson — CHANGES_REQUESTED** [review]
I followed the instructions in https://github.com/tripal/tripal/pull/1419#issuecomment-1520716576 and received the following error repeated many times when creating the Chado Feature Sequence Checksum field.

It shows up on the field settings step (after step 2 in the How to add a field instructions) and is then repeated on every page that the checksum field is on. The error messages are at the bottom.

## Solution

This seems to be a simple typo on line 72 in your field class.

```patch
diff --git a/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php b/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php
index a3401674f..7caa44651 100644
--- a/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php
+++ b/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php
@@ -69,7 +69,7 @@ class ChadoSequenceChecksumDefault extends ChadoFieldItemBase {
     $chado = \Drupal::service('tripal_chado.database');
     $schema = $chado->schema();
     $feature_def = $schema->getTableDef('feature', ['format' => 'Drupal']);
-    $md5_checksum_len = $feature_def['fields']['smd5_checksum']['size'];
+    $md5_checksum_len = $feature_def['fields']['md5checksum']['size'];
```

## Error Messages

```
Warning: Undefined array key "smd5_checksum" in Drupal\tripal_chado\Plugin\Field\FieldType\ChadoSequenceChecksumDefault::tripalTypes() (line 72 of modules/contrib/tripal/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php).

Drupal\tripal_chado\Plugin\Field\FieldType\ChadoSequenceChecksumDefault::tripalTypes(Object) (Line: 295)
Drupal\tripal\TripalField\TripalFieldItemBase::schema(Object) (Line: 456)
Drupal\field\Entity\FieldStorageConfig->getSchema() (Line: 2329)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->getDedicatedTableSchema(Object) (Line: 1554)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->createDedicatedTableSchema(Object, NULL) (Line: 1535)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->performFieldSchemaOperation('create', Object) (Line: 695)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->onFieldStorageDefinitionCreate(Object) (Line: 1534)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->Drupal\Core\Entity\Sql\{closure}() (Line: 1590)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException(Object) (Line: 1537)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->onFieldStorageDefinitionCreate(Object) (Line: 85)
Drupal\Core\Field\FieldStorageDefinitionListener->onFieldStorageDefinitionCreate(Object) (Line: 343)
Drupal\field\Entity\FieldStorageConfig->preSaveNew(Object) (Line: 297)
Drupal\field\Entity\FieldStorageConfig->preSave(Object) (Line: 562)
Drupal\Core\Entity\EntityStorageBase->doPreSave(Object) (Line: 517)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 253)
Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object) (Line: 339)
Drupal\Core\Entity\EntityBase->save() (Line: 608)
Drupal\Core\Config\Entity\ConfigEntityBase->save() (Line: 374)
Drupal\field_ui\Form\FieldStorageAddForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 595)
Drupal\Core\Form\FormBuilder->processForm('field_ui_field_storage_add_form', Array, Object) (Line: 323)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 169)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 718)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

```
Warning: Trying to access array offset on value of type null in Drupal\tripal_chado\Plugin\Field\FieldType\ChadoSequenceChecksumDefault::tripalTypes() (line 72 of modules/contrib/tripal/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php).

Drupal\tripal_chado\Plugin\Field\FieldType\ChadoSequenceChecksumDefault::tripalTypes(Object) (Line: 295)
Drupal\tripal\TripalField\TripalFieldItemBase::schema(Object) (Line: 456)
Drupal\field\Entity\FieldStorageConfig->getSchema() (Line: 2329)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->getDedicatedTableSchema(Object) (Line: 1554)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->createDedicatedTableSchema(Object, NULL) (Line: 1535)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->performFieldSchemaOperation('create', Object) (Line: 695)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->onFieldStorageDefinitionCreate(Object) (Line: 1534)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->Drupal\Core\Entity\Sql\{closure}() (Line: 1590)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException(Object) (Line: 1537)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->onFieldStorageDefinitionCreate(Object) (Line: 85)
Drupal\Core\Field\FieldStorageDefinitionListener->onFieldStorageDefinitionCreate(Object) (Line: 343)
Drupal\field\Entity\FieldStorageConfig->preSaveNew(Object) (Line: 297)
Drupal\field\Entity\FieldStorageConfig->preSave(Object) (Line: 562)
Drupal\Core\Entity\EntityStorageBase->doPreSave(Object) (Line: 517)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 253)
Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object) (Line: 339)
Drupal\Core\Entity\EntityBase->save() (Line: 608)
Drupal\Core\Config\Entity\ConfigEntityBase->save() (Line: 374)
Drupal\field_ui\Form\FieldStorageAddForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 595)
Drupal\Core\Form\FormBuilder->processForm('field_ui_field_storage_add_form', Array, Object) (Line: 323)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 169)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 718)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Review by laceysanderson — COMMENTED** [review]
This review assumes the change mentioned in https://github.com/tripal/tripal/pull/1419#pullrequestreview-1398775610 has been applied.

When I create a gene with no sequence, I expect to see 
✅ the sequence field excluded
✅ sequence length set to 0
❌ the checksum field excluded

But instead the field computes a checksum for an empty string which is a bit confusing.
Screen Shot 2023-04-24 at 4 02 41 PM

When I edited an existing gene and added sequence, I expect to see
✅ the new sequence displayed on the page
✅ a correctly calculated length
✅ a checksum

Screen Shot 2023-04-24 at 4 13 34 PM

When I create a gene with a sequence, I expect to see 
✅ the sequence field to display the sequence
✅ sequence length correctly set
✅ a checksum

Screen Shot 2023-04-24 at 4 23 58 PM

When I edit the gene and make no changes, I expect
✅ the sequence to stay the same
✅ the sequence length to stay the same
✅ the checksum to stay the same

**Comment by laceysanderson** [comment]
All commits in this PR are in #1607. Since the mentioned PR also includes the fixes asked for in review, we will close this one in favour of that one.

**Pull request closed without merging**
