### PR TITLE
Update install_drupal.rst

### PR DESCRIPTION
**Pull request by spficklin**
Fixed version of Drupal from 7.59 to 7.61 on install docs.

### CODE REVIEW

**Comment by spficklin** [comment]
HOld off on this. The correct current version 7.63.  Need to fix this.

**Comment by spficklin** [comment]
Okay, fixed version and added one more doc fix for install.    Ready for review.

**Comment by spficklin** [comment]
Ha... so the 7.64 update came out since I adjusted this.... so, again one more fix.

**Comment by bradfordcondon** [comment]
looks like the current version is at 7.64 . Looks good to me, thanks @spficklin

**Pull request merged**
