### PR TITLE
TripalStorage doesn't support Tripal fields using Drupal Storage

### LINKED ISSUE #1611: TripalStorage doesn't support fields using Drupal Storage
# BUG/ERROR report

### Tripal Version: 4.x
* Drupal Version: All
* PostgreSQL Version: 13
* PHP Version: All

### Issue description

I would expect to be able to create basic Tripal Fields without specific storage and add them to a Tripal Content Type without error.

Currently when I do, I am able to add the field to the content type without error but then when I try to add content of that type, I get an error that it's not able to create a Tripal storage instance with no name. See the Error messages section for the full output.

#### Steps to reproduce

1. Create a fresh docker image + container based on this branch ([see these instructions if needed](https://tripaldoc.readthedocs.io/en/latest/contributing/docker-for-testing.html#testing-an-unmerged-pull-request)).
2. Copy the following field class files into the Tripal/src/Plugin/Field/FieldType, FieldWidget and FieldFormatter folders and replace `.txt` with `.php`: 
[TripalExampleSimpleStringTypeItem.txt](https://github.com/tripal/tripal/files/12388873/TripalExampleSimpleStringTypeItem.txt), [TripalExampleSimpleStringWidget.txt](https://github.com/tripal/tripal/files/12388874/TripalExampleSimpleStringWidget.txt),  [TripalExampleSimpleStringFormatter.txt](https://github.com/tripal/tripal/files/12388875/TripalExampleSimpleStringFormatter.txt)
3. Go to Tripal > Page Structure > Organism > Manage Fields and click on "Add Field"
4. Select "Tripal Example Simple String Field Type" from the "Add a new field" drop-down. Enter a label for the field and click "Save and Continue".
5. Use the default field settings and click Save. Set a Term and click Save.
6. Now create an organism by going to Admin > Tripal > Content and clicking "Add Tripal Content". This branch should show you a form element for the new field you added with no errors. Fill out this field and all required fields and click save.
7. The view page should show the value of the field just as you entered it.
8. Edit the page and change the field value then click save. It should be updated as expected with no errors.
 
#### Error messages and screenshots

If you follow the above instructions one the 4.x branch you will see the following errors when you try to create an organism after adding the type:

```
The website encountered an unexpected error. Please try again later.

Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" plugin does not exist. Valid plugin IDs for Drupal\tripal\TripalStorage\PluginManager\TripalStorageManager are: chado_storage in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).
Drupal\Core\Plugin\DefaultPluginManager->getDefinition('') (Line: 16)
Drupal\Core\Plugin\Factory\ContainerFactory->createInstance('', Array) (Line: 83)
Drupal\Component\Plugin\PluginManagerBase->createInstance('', Array) (Line: 48)
Drupal\tripal\TripalStorage\PluginManager\TripalStorageManager->getInstance(Array) (Line: 486)
Drupal\tripal\Entity\TripalEntity::getValuesArray(Object) (Line: 697)
Drupal\tripal\Entity\TripalEntity->validate() (Line: 188)
Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object)
call_user_func_array(Array, Array) (Line: 82)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object) (Line: 275)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'tripal_entity_organism_add_form') (Line: 118)
Drupal\Core\Form\FormValidator->validateForm('tripal_entity_organism_add_form', Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('tripal_entity_organism_add_form', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 74)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 692)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

### PR DESCRIPTION
**Pull request by laceysanderson**
# Bug Fix

Issue #1611

## Description

This PR simply allows TripalStorage to be bypassed for Tripal Fields which do not specify a backend storage. This allows developers to create simple visualization fields, etc which use the Drupal Storage backend while still taking advantage of the benefits of Tripal Fields.

## Testing?

1. Create a fresh docker image + container based on this branch ([see these instructions if needed](https://tripaldoc.readthedocs.io/en/latest/contributing/docker-for-testing.html#testing-an-unmerged-pull-request)).
2. Copy the following field class files into the Tripal/src/Plugin/Field/FieldType, FieldWidget and FieldFormatter folders and replace `.txt` with `.php`: 
[TripalExampleSimpleStringTypeItem.txt](https://github.com/tripal/tripal/files/12388873/TripalExampleSimpleStringTypeItem.txt), [TripalExampleSimpleStringWidget.txt](https://github.com/tripal/tripal/files/12388874/TripalExampleSimpleStringWidget.txt),  [TripalExampleSimpleStringFormatter.txt](https://github.com/tripal/tripal/files/12388875/TripalExampleSimpleStringFormatter.txt)
3. Go to Tripal > Page Structure > Organism > Manage Fields and click on "Add Field"
4. Select "Tripal Example Simple String Field Type" from the "Add a new field" drop-down. Enter a label for the field and click "Save and Continue".
5. Use the default field settings and click Save. Set a Term and click Save.
6. Now create an organism by going to Admin > Tripal > Content and clicking "Add Tripal Content". This branch should show you a form element for the new field you added with no errors. Fill out this field and all required fields and click save.
7. The view page should show the value of the field just as you entered it.
8. Edit the page and change the field value then click save. It should be updated as expected with no errors.

### CODE REVIEW

**Review by dsenalik — CHANGES_REQUESTED** [review]
I followed the test procedure for organism with cardinality 1, cvterm "RNA", and it worked as expected. Value was saved, value could be edited, value could be set to empty string
Confirmed values stored in database in public schema
```
sitedb=> select * from public.tripal_entity__field_testsimplestring;
  bundle  | deleted | entity_id | revision_id | langcode | delta | field_testsimplestring_value 
----------+---------+-----------+-------------+----------+-------+------------------------------
 organism |       0 |         1 |           1 | und      |     0 | ACGUACGU
(1 row)
```
I then tried on phylogenetic tree with cardinality unlimited, entering three values
```sitedb=> select * from tripal_entity__field_tree_string;
  bundle   | deleted | entity_id | revision_id | langcode | delta | field_tree_string_value 
-----------+---------+-----------+-------------+----------+-------+-------------------------
 phylotree |       0 |         3 |           3 | und      |     0 | Item one
 phylotree |       0 |         3 |           3 | und      |     1 | Item two
 phylotree |       0 |         3 |           3 | und      |     2 | Item three
 phylotree |       0 |         3 |           3 | und      |     3 | 
(4 rows)
```
Upon editing, order of items can be changed as expected by dragging, and is saved.
```
sitedb=> select * from tripal_entity__field_tree_string;
  bundle   | deleted | entity_id | revision_id | langcode | delta | field_tree_string_value 
-----------+---------+-----------+-------------+----------+-------+-------------------------
 phylotree |       0 |         3 |           3 | und      |     0 | Item one
 phylotree |       0 |         3 |           3 | und      |     1 | Item three
 phylotree |       0 |         3 |           3 | und      |     2 | Item two
 phylotree |       0 |         3 |           3 | und      |     3 | 
 phylotree |       0 |         3 |           3 | und      |     4 | 
(5 rows)
```

My only question is those blank rows. They were was present on the form so were saved - but every time you edit and save, an additional blank row is added. I wonder if there is an easy fix, ignore the last row somehow if there is nothing in it. That would also prevent the additional blank rows from getting added.
Is it reasonable to request this change? Should this happen in `preSave()` ?
tree

**Comment by laceysanderson** [comment]
Thank you for the thorough review @dsenalik and good catch! I'll look into this <3

**Comment by spficklin** [comment]
So, this issue of saving blank items was a problem we had with TripalFields but I believe our current solution does not have this problem.  I have not looked over this PR yet, but if Drupal is taking over storing of these field values, this sounds like a Drupal problem, right?

**Comment by laceysanderson** [comment]
So I've confirmed that the problem with empty lines does not exist for Drupal fields (in this branch or in 4.x) and does not exist for Chado fields (in this branch or in 4.x) but only for Tripal fields using Drupal storage. So that's interesting...

On another note though, I'm going to redo this PR to use an approach in between mine and Stephens. Although we do not know we need findValues for TripalFields it is better to create the class now just in case. If we do not create a Drupal SQL Storage implementation of TripalStorage now and then need it later we would need to have all developers change their fields 😬  Additionally, we've decided it is more intuitive for developers to indicate "Drupal SQL Storage" for their Tripal field as compared to indicate no storage backend which is what my current approach would require.

I'll make a new PR with the new functionality.

**Pull request closed without merging**
