### PR TITLE
Fix for optional treatment for bulk loader

### PR DESCRIPTION
**Pull request by btski**
Corrected bulk loader behavior when processing optional fields. Current behavior fails to load optional null values when the field is required to be non-null. Expected behavior is that the field be omitted.

# Bug Fix

## Description

[Issue #1164](https://github.com/tripal/tripal/issues/1164): Fix for bulk loader optional setting. Currently, the optional setting only works for required values (not null?) that are absent. I'm not sure what criteria is used to define "required" values. I believe the intended behavior for the optional setting is that if a null value is provided for a field that is required to be non-null, the field and all children are omitted from upload. To reflect this understanding, I made a simple [modification](https://github.com/btski/tripal/commit/63734c169e8c54cf6b8181baa09040b0576a8068#diff-6c01ec69165fffbaf8e13dc21f320027a78d8c66619bfac7a6d3858dc49001a1). 

[Issue #1165](https://github.com/tripal/tripal/issues/1165): Null value would trigger a false error when the null value is called as a foreign key in another table. My proposed solution can be found [here](https://github.com/btski/tripal/commit/be4642efe82578c77c241c6d969213586ab6b43e#diff-347452757b032417e3eef4c4019ba6bbecefc8a29cc595bd0ced49510d0a979c). 

## Testing?

Successfully loaded all data hosted on my Tripal site. Previously, I used filler text on non-null fields and manually removed these fields after loading data.

### CODE REVIEW

**Comment by spficklin** [comment]
Hi @btski can you provide an example data set and template that causes the problem that this PR is meant to fix?  I'm not 100% sure what the problem is.   

Thanks

**Comment by dsenalik** [comment]
I realize that I have this exact problem too!
I am loading organisms with a chado bulk loader, and the data file includes NCBI taxid and GRIN taxid columns. Some organisms don't have those, so for those I have to have a fake id "NULL" and delete the dbxref after loading. Even though my bulk loader has those with "optional" checked.

I tested this branch, and it appears that I can now load with the "optional" columns being empty.
I am attaching my test file and my bulk loader template.

[pull_1170_taxaimport.template.txt](https://github.com/tripal/tripal/files/6103645/pull_1170_taxaimport.template.txt)
[pull_1170_test1.tsv.txt](https://github.com/tripal/tripal/files/6103646/pull_1170_test1.tsv.txt)

**Comment by spficklin** [comment]
So, after looking into this problem I think this PR isn't ideal.  There are two issues
1)  The problem can somewhat be circumvented if the 'required' option is  turned on for 'optional inserts'.  I think the logic in the bulk loader needs correcting. When chatting with @btski in the dev meeting this morning he seemed to think this PR wasn't quite right either for that reason.
2)  This PR changes the `chado_insert_record`  and `chado_update_record` functions which shouldn't be needed for fixing the bulk loader and changing those functions makes me nervous.  I think the fix should be restricted to just the bulk loader code.

I suggested to @btski to leave this PR here to remind us to come up with a better solution and so this issue doesn't get lost in the other outstanding issues.

**Comment by spficklin** [comment]
After chatting with @btski here's what we think the solution should be.

1.  When editing a field in the bulk loader, under the 'Additional Options' section, the 'Make this field required' checkbox doesn't hold it's check and doesn't pick up what the setting is in the template.  This needs fixing first.
2. Next, we need to makes sure the checkbox for 'Make this field required' is set by default to checked if the column in the Chado table has a 'NOT NULL' designation and the end-user cannot uncheck it. It needs to stay fixed.  A message should be shown to the end-user indicating that the box must stay checked because the underlying table requires it.  

I think this will fix the original problem, but I did notice there was another issue with the template provided by @dsenalik that might need fixing too.  Also, it would be nice if the field view, when editing the bulk loader would show the options so that the user can tell which fields are required.

**Comment by spficklin** [comment]
I'm closing out this PR in favor of PR #1177 .  @dsenalik and @btski can you test the new PR to see if it solves the problem for you (see the testing instructions).

**Pull request closed without merging**
