### PR TITLE
edit to documentation: added common path to modules directory

### PR DESCRIPTION
**Pull request by srobb1**
## Type(s) of Change(s)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [x] Updates documentation (inline or markdown files)

## Description

adding some detail to the instructions as I go through them. Just in case someone does not know where modules are stored, I added the path.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
thanks @srobb1 
I really appreciate this, please keep creating issues or PRs as you go through the documentation!  It will make it so much better.


how would you feel about this instead?

>The Tripal modules must also be downloaded and updated. To do this, delete the old Tripal v2 modules directories, located in `sites/all/modules` from your Drupal root:  for example `/var/www/html/sites/all/modules `(be sure you have a backup before removing). The following command will retrieve the Tripal 3 version:

Your suggestion is just as corect, but i want to convey that a) tripal is by default in `/sites/all/modules/` from wherever the drupal root is, and, b) the "default" drupal root is `/var/www/html`

**Comment by spficklin** [comment]
Thanks @srobb1 this is great!

**Comment by srobb1** [comment]
@bradfordcondon That is great! Thanks!

**Comment by bradfordcondon** [comment]
ok thanks, i made the suggestion and will merge in 👍 thanks again

**Pull request merged**
