### PR TITLE
Cache set check

### PR DESCRIPTION
**Pull request by bradfordcondon**
Issue #389

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

Fields that are not set for an entity caused this warning:

```
Notice: Undefined property: TripalEntity::$tripal__ena_last_update in TripalEntityController->attachLoad() (line 658 of /var/www/html/sites/all/modules/custom/tripal/tripal/includes/TripalEntityController.inc).
```

So for example, if you set a chado_property for a content type, and then open another entity with that property not set, you will get this error.  This error is present on my live site (with warnings enabled) and dev site.

However, @laceysanderson was not able to duplicate on her system.  
It's such a minor fix that I'm hoping that won't be an issue.

## Screenshots (if appropriate):

* add a chado property
* fill out for one entity but not another
* clear cache
* visit the entity lacking the entity's page.

before fix
screen shot 2018-06-05 at 1 33 47 pm

after fix
with_patch

## Additional Notes (if any):

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by spficklin** [comment]
When you say "open another entity" do you mean create a new entity of the same content type that has the field attached?

**Comment by bradfordcondon** [comment]
yes, or visit a pre-existing entity of that type (which should have null for the field).

**Comment by spficklin** [comment]
I was able to duplicate this bug and this PR does fix it.  The source of the problem is in the chado_linker__prop.load() function.  At the end if the property does not exist then it manually removes the field from the $entity object.  This is the only field that does this and it's a hack to keep the property key from showing up in the TOC on the page when no properties are actually present.   I think the fix is fine and while we should probably dig into why we had to put that adjustment in the load() function of the chdao_linker__prop field, this fix corrects the problem and makes the Entity controller more robust.

**Comment by spficklin** [comment]
This fix is so simple, I think it only needs one reviewer. I'm going to merge.

**Pull request merged**
