### PR TITLE
Implement chado_get_organism_id_from_scientific_name

### PR DESCRIPTION
**Pull request by dsenalik**
# New Feature

Issue #1327 

## Description

This adds
1. A new api function ```chado_get_organism_id_from_scientific_name()``` which will look up and return an ```organism_id``` from a taxon name _e.g._ ```Tripalus domesticus subsp. chadoii```
2. A new identifier that can be passed to ```chado_get_organism()``` of ```scientific_name```, which allows the return of an organism given a taxon name (as in 1)
 

## Testing?
Since so far nothing is using this, test in the devel module php window
```
$s = 'Tripalus domesticus subsp. chadoii';  // A fake or a real organism name
$o = chado_get_organism(['scientific_name' => $s], []);
var_dump($o);
```

## Additional Notes:

This will first be used for the ```sbo__relationship``` widget on organism pages, see https://github.com/tripal/tripal/pull/1267#issuecomment-1339482302

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
Thanks @dsenalik!

The logic flow and options in the new chado_get_organism_id_from_scientific_name() function could use some improvements to be more consistent with other API functions in Tripal. Specifically,

- Since the name specifies scientific name, that should be always checked first and if a match found then nothing else should be checked.
- The options should be changed as follows:
```php
/*
 * @param $options
 *     An array of options. The following keys are available:
 *        -  check_abbreviation: If TRUE and the $name did not match the scientific name then check the abbreviation.
 *        - check_common_name:  If TRUE and the $name did not match the scientific name then check the common name.
 *        - case_sensitive:  If TRUE then all searches should be case sensitive. Default is FALSE.
 */
```

**Comment by dsenalik** [comment]
I made the suggested changes, thanks for the feedback, much appreciated.

A few of the tests I ran, but these depend on the organisms in the database
```
$s = 'Daucus carota subsp. sativus';
$o = chado_get_organism_id_from_scientific_name($s, []);
print 'default: '.count($o)."\n";

$s = 'D. carota';
$o = chado_get_organism_id_from_scientific_name($s, ['check_abbreviation']);
print 'abbreviation: '.count($o)."\n";

$s = 'carrot';
$o = chado_get_organism_id_from_scientific_name($s, ['check_common_name']);
print 'common name case insensitive: '.count($o)."\n";

$s = 'carrot';
$o = chado_get_organism_id_from_scientific_name($s, ['check_common_name', 'case_sensitive']);
print 'common name case sensitive: '.count($o)."\n";

$s = 'daucus carota subsp. sativus';
$o = chado_get_organism(['scientific_name' => $s], []);
print 'chado_get_organism default: '.($o?'found':'null')."\n";

$s = 'daucus carota subsp. sativus';
$o = chado_get_organism(['scientific_name' => $s], ['case_sensitive']);
print 'chado_get_organism case_sensitive: '.($o?'found':'null')."\n";

$s = 'carrot';
$o = chado_get_organism(['scientific_name' => $s], ['check_common_name']);
print 'chado_get_organism common_name: '.($o?'found':'null')."\n";
```
Results
```
default: 1
abbreviation: 1
common name case insensitive: 1
common name case sensitive: 0
chado_get_organism default: found
chado_get_organism case_sensitive: null
chado_get_organism common_name: found
```

**Comment by dsenalik** [comment]
~~The Chado 1.2 way of handling infraspecific nomenclature was to put it all in the 'species' column. Should I add code to support this, what do people think?
For example genus = 'Daucus' species = 'carota subsp. sativus'~~
Edit: Never mind, it seems I forgot how the code works, this will be handled automatically.

**Review by spficklin — APPROVED** [review]

**Comment by spficklin** [comment]
The code changes look fine.  @dsenalik responded to the requests that @laceysanderson made and I tested it with the following:

1. Added a new organism to to match that @dsenalik provided as an example.  
2. Ran the following drush command:
```bash
drush php-eval "\$s = 'Tripalus domesticus subsp. chadoii'; \$o = chado_get_organism(['scientific_name' => \$s], []); var_dump(\$o);"
```    
It worked as behaved.

**Pull request merged**
