### PR TITLE
701 tv3 publishing fix

### PR DESCRIPTION
**Pull request by spficklin**
# Bug Fix

Issue #701 

## Description

This PR is an extension of the PR #701 submitted by @abretaud .  It brings the publishing code up to date with the TripalJob API and reporting.

## Testing?

Just publish some content and make sure it works!  And take a look at the code.

### CODE REVIEW

**Comment by spficklin** [comment]
Also, once this is merged then it will automatically include the fixes by @abretaud in PR #701 and that PR can be closed.

**Review by laceysanderson — APPROVED** [review]
Code looks good and publishing works for me 👍

**Comment by spficklin** [comment]
Thanks Lacey. I added your approval.  I approve the changes @abretaud made from PR #701 so if you @abretaud can test my updates and give your approval it can be merged.  

Also, I believe @abretaud your credit for the contributions should still be present in this PR because I built of of the code in your branch

**Review by abretaud — APPROVED** [review]
lgtm, I tested it and it worked fine

**Comment by laceysanderson** [comment]
With @abretaud approval above, we have the two required reviews. As such I'm merging this PR.

Thanks @spficklin and @abretaud!

**Pull request merged**
