### PR TITLE
Fix for #1064 - Chado Upgrade 1.2-1.3 SQL

### PR DESCRIPTION
**Pull request by Ferrisx4**
# Bug Fix

Issue https://github.com/tripal/tripal/issues/1064

## Description

Reverts (and slightly modifies) changes made to the Chado install process in [2016](https://github.com/tripal/tripal/commit/6cd8b469b8ead4304970eac7b650e8ee8431d78c#diff-1d2ba65756645ba7ee3de90f8f1066da). Sequence creation is now (again) handled in the SQL file rather than in PHP.

As discussed in several meetings and in the related issue, this change will require databases to be using Postgres 9.5 or later. This is required due to the use of "CREATE SEQUENCE **IF NOT EXISTS**" in the upgrade process which did not exist prior to Postgres 9.5.

## Testing?

These changes can be tested by upgrading a Tripal 7 site from Chado 1.2 to Chado 1.3. 

## Additional Notes (if any):

Two commits in this PR are unrelated, (0f07995, 21d5f93), but they cancel each other out.

### CODE REVIEW

**Review by bradfordcondon — COMMENTED** [review]
>As discussed in several meetings and in the related issue, this change will require databases to be using Postgres 9.5 or later. 

So this was OK'd by the community?    Are we incrementing the required Postgres version to 9.5?  According to our docs we support it at 9.3: should that be updated? (here) https://github.com/tripal/tripal/blob/7.x-3.x/docs/user_guide/install_tripal/server_setup.rst#server-setup



edit: after re-reading the issue, I see that @laceysanderson  was ok with `9.5`.  So please if we could include a note about that in the documentation i linked i'll be happy.   ie something like

> PostgreSQL 9.3 or higher (9.5 required for Chado 1.2 to 1.3 upgrade)

Lacey also requested a note in the README and a warning in the upgrade Chado form which would also be nice.

Thanks!

**Comment by Ferrisx4** [comment]
Updated the documentation, readme, and the upgrade form to reflect the new requirement for PostgreSQL 9.5

**Review by bradfordcondon — APPROVED** [review]

**Comment by bradfordcondon** [comment]
Thanks for adding the documentation!  if @spficklin  or @laceysanderson can confirm we're happy with this change we'll get it merged.

**Review by laceysanderson — APPROVED** [review]
Looks good to me! Thanks @Ferrisx4

**Pull request merged**
