### PR TITLE
Additional Relationship Formatter

### PR DESCRIPTION
**Pull request by laceysanderson**
Issue #523

## Type(s) of Change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

Currently the relationship formatter for Tripal 3 states all relationships in sentence form in a single-columned table. This is quite different from the format for relationships used in Tripal 2 with a multi-columned table per relationship type.

This formatter mimics the Tripal 2 format providing one table per relationship type with the columns name, uniquename, species, type of related item; eg. stock. I think this one belongs in core since it allows admin to mimic the old pages during upgrade.

Things of interest:
- Supports related tables where there is no uniquename and/or organism_id by simply not including those tables.
- Required backwards compatible update to the sbo__relationship field to load the organism information.
- Should be similar performance as the original formatter (both loop through all relationships to add to a table)
- Doesn't support paging since Tripal 3 `TripalFormatter->ajaxifyPager()` currently only supports a single pager per field.

## Testing?

1. Pick a content type with relationships to test and navigate to Admin > Structure > Tripal Content Types > [your content type] > Manage Fields.
2. Clear the cache and click find new fields.
3. Navigate to Manage Display, you should now see two items in the format drop-down for the relationship field: "Relationship Statements" (original formatter) and "Relationship Table" (this formatter).
4. Switch the formatter to "Relationship Table" and click "Save" at the bottom of the page.
5. Navigate to an entity page of that type with relationships and confirm the field now looks similar to the screenshot below.

## Screenshots (if appropriate):
The following screenshot shows an example of the relationship formatter in use on a stock-based content type. As you can see, it follows the relationships in both directions (current entity can be subject or object) and provides the same readable sentence describing the relationship above the table the way it was done in Tripal 2.
screen shot 2018-08-03 at 8 57 08 am

The following screenshot shows the configuration of this formatter. It provides default "sentences" for use at the top of each table as shown in the screenshot above. The admin can change these sentences to make them more intuitive to their user base. Supports use of a few tokens for embedding type information in the sentence and different sentences based on whether the current entity is the subject or object in the relationship.
screen shot 2018-08-03 at 8 58 42 am

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by spficklin — APPROVED** [review]

**Comment by spficklin** [comment]
Works great!  I approve, although there is one oddity.  Notice in the relationship table in the screenshot below that it says "The following Genes(s) are Part Of of this Gene".   Shouldn't it read: "The following mRNA(s) are Part of this gene".... The text in the screenshot has "Gene" instead of "mRNA" and there are two of's.

image

**Comment by spficklin** [comment]
I'm marking this as approved as I think a fix for the text I pointed out doesn't need my input again.

**Comment by laceysanderson** [comment]
I've fixed the wording issues you pointed out -Thanks @spficklin!

**NOTE:** To test the new defaults, you need to copy the following into the configuration form on the "Manage Display" page. **This is only needed if you have tested before this change was made.**
 - Subject Caption: `This @content_type is <em>@rel_type</em> the following:`
 - Object Caption: `The following are <em>@rel_type</em> this @content_type:`

**Comment by chunhuaicheng** [comment]
It works great on my site. Thank you for the new feature.

**Comment by laceysanderson** [comment]
Awesome :-) Thank you @chunhuaicheng!

**Pull request merged**
