### PR TITLE
Tripal 4 issue1568 add missing legacy_ro.obo

### PR DESCRIPTION
**Pull request by dsenalik**
# Bug Fix

## Description
We forgot to copy over `legacy_ro.obo`, this copies it from the exact same location in tripal 3
`tripal_chado/files/legacy_ro.obo` and incorporates some fixes found when loading it.

## Testing?
Described in Issue #1568

### CODE REVIEW

**Comment by dsenalik** [comment]
Bleeding edge testing (PHP 8.1 Drupal 10.1) and we get this:
```
 [notice] Step 1: Preloading File //var/www/drupal9/web/modules/contrib/tripal/tripal_chado/files/legacy_ro.obo...
Percent complete: 0%. Memory: 35,341,592 bytes.
 [notice] Percent complete: 0%. Memory: 35,341,592 bytes.
Percent complete: 5.11 %. Memory: 35,353,504 bytes.
 [notice] Percent complete: 5.11 %. Memory: 35,353,504 bytes.
 [warning] Undefined variable $chado OBOImporter.php:1187
 [error]  Error: Call to a member function query() on null in Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->setDefaults() (line 1187 of /var/www/drupal9/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php) #0 /var/www/drupal9/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php(2358): Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->setDefaults(Array)
```

**Comment by dsenalik** [comment]
Fix that with https://github.com/tripal/tripal/pull/1570/commits/e4607467c608fd02f55c9f81f08a106e69e2ae96
but now:
```
Step 1: Preloading File //var/www/drupal9/web/modules/contrib/tripal/tripal_chado/files/legacy_ro.obo...
 [notice] Step 1: Preloading File //var/www/drupal9/web/modules/contrib/tripal/tripal_chado/files/legacy_ro.obo...
Percent complete: 0%. Memory: 35,322,504 bytes.
 [notice] Percent complete: 0%. Memory: 35,322,504 bytes.
Percent complete: 5.11 %. Memory: 35,334,416 bytes.
 [notice] Percent complete: 5.11 %. Memory: 35,334,416 bytes.
ERROR: Cannot cache terms without a default DB.Array
(
    [id] => Array
        (
            [0] => OBO_REL:is_a
        )

    [alt_id] => Array
        (
            [0] => OBO_REL:0000001
        )

    [name] => Array
        (
            [0] => is_a
        )
etc.
```

This is because in `setDefaults()` the variable `$short_name` never gets a name assigned to it.
This file does not contain an `ontology` header line, and this section of code is the last chance to get a value for `$short_name`
```
      // Try the EBI Lookup: still experimental.
      if (!$short_name) {
        //$short_name = $this->findEBIOntologyPrefix($namespace);
      }
```
It's commented out in tripal 3 too

**Comment by dsenalik** [comment]
I just tested loading this on tripal 3 and the exact same error happens 😭

**Comment by dsenalik** [comment]
Because the obo file is included with tripal, a "safe" (that means don't break anything) resolution is to just manually add the missing `ontology: OBO_REL` header line https://github.com/tripal/tripal/pull/1570/commits/be9399a120539d931297303c3ef3f9a7178b6c4b

Next error:
` [error]  DivisionByZeroError: Division by zero in Drupal\tripal\TripalImporter\TripalImporterBase->setItemsHandled() (line 466 of /var/www/drupal9/web/modules/contrib/tripal/tripal/src/TripalImporter/TripalImporterBase.php)`

This will be a simple fix in commit https://github.com/tripal/tripal/pull/1570/commits/89dfea4b16de59b459bfb528b27bbd8a2d6fb287 + https://github.com/tripal/tripal/pull/1570/commits/fe0ad32fb3d2f1b13b914431deb003b9e21d3098 to catch when total_items is zero, and in such a case make the percent handled also be zero.

**Comment by dsenalik** [comment]
With all these changes the ontology loads without error under PHP 8.1 Drupal 10.1, ready for review

**Review by laceysanderson — APPROVED** [review]
✅ Code Review looks good
✅ Automated Testing Passes

✅ Manual Testing

I tested importing the legacy relationship ontology into the default chado schema:
- ✅ No errors in the job output
- ✅ Relationship ontology in the cv table
- ✅ Expected terms associated with the relationship ontology in the cvterm table including have is_relationshiptype set to true

Thanks for the fix @dsenalik ❤️

**Pull request merged**
