### PR TITLE
Fix for issue #586

### PR DESCRIPTION
**Pull request by spficklin**
Issue #586

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

Some combination of previous PRs broke our ability to publish content types with an organism. The filters defaulted to adding '__NULL__' for organism in the filters. That obviously won't work.  This PR fixes it.

## Testing?

Just pull the branch and try to publish any content type based on features. 

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by spficklin** [comment]
This is such a simple fix it only needs on review.

**Comment by bradfordcondon** [comment]
beautiful thank you @spficklin

**Review by bradfordcondon — APPROVED** [review]

**Comment by bradfordcondon** [comment]
i will merge after CI checks.

**Comment by spficklin** [comment]
I should also state that I tested creating of a biomaterial as well (no organism_id is required... which is hte reason for the __NULL__ being set for the value) and this PR does not break that either.

**Pull request merged**
