### PR TITLE
Add db transaction to tripal_update_cvtermpath

### PR DESCRIPTION
**Pull request by almasaeed2010**
We've added db transaction support in the cvtermpath builder function to avoid having to clear the table when an error occurs during the building process.

Thanks!

### CODE REVIEW

**Comment by laceysanderson** [comment]
Looks like a good PR although I'm not the person to test it :-) I'm not sure where the addition of the "in progress" tag came from -maybe my ZenHub adds it automatically?

**Comment by almasaeed2010** [comment]
I should add that I have ran the script on cellular_component and it didn't cause any problems (takes about 6 hours to complete the test unfortunately)

Thanks!

**Comment by spficklin** [comment]
This looks good to me.  Can you make one adjustment non-related to your fix but since you're doing a pull request on the function?  The line "chado_set_active($prev_db);" appears on line 405, in the catch block and on line 411.  I think we only need it on line 411.  Would you mind adjusting your pull request to remove that entry on line 405?

**Comment by almasaeed2010** [comment]
Sorry for the delay @spficklin! I removed the extra call in the latest commit.

Thanks!

**Comment by almasaeed2010** [comment]
Come to think about it, it is re-throwing the error so it's in fact needed in both areas or in a `finally {}` statement otherwise it won't execute since throwing an error stops the script. I'll add a `finally` which executes even in case of an error.

**Review by bradfordcondon — APPROVED** [review]

**Pull request merged**
