### PR TITLE
Remote fields not working if content type name changed.

### PR DESCRIPTION
**Pull request by spficklin**
Issue #491

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

If the content type name is different on a remote site (e.g. Organism is renamed to Species) then the remote data field does not work as per the description provided in the issue.   This PR fixes that problem by using the remote ws @context definition to map the type to it's vocabulary accession.  All content types are accessible via their accessions so this changes resolves the problem.

## Testing?

I think it's best for @laceysanderson and @almasaeed2010  to test this as they already have tested as per issue #491.  And it saves me from having to write a detailed testing instructions ;-)

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by almasaeed2010 — APPROVED** [review]

**Comment by almasaeed2010** [comment]
This works perfectly for me.

Here is how I tested this:
1. setup a remote tripal site by going to admin/tripal/storage/ws/tripal_sites/edit and the url should be the same as your site's url
1. create a remote data field in organism content type
1. point the field to load data from your own site
1. add the following as the query: `Organism?species=[taxrank__species]&genus=[taxrank__genus]`
1. add `abbreviation` in the "Field to Display" field
1. save
1. visit the organism page to confirm the remote field works
1. go to manage fields for the organism and edit the label for the abbreviation field (I named it abbr)
1. visit the organism page to confirm the remote field still works

Thanks @spficklin!

**Comment by bradfordcondon** [comment]
approved by @almasaeed2010  adding tag.

**Comment by spficklin** [comment]
@laceysanderson any chance you can review this one?

**Comment by laceysanderson** [comment]
On holidays this week but I’ll try to get to it next week. Feel free to remind me again if I don’t ;-p

**Comment by bradfordcondon** [comment]
friendly ping for @laceysanderson

**Comment by laceysanderson** [comment]
Ok, I confirmed that changing the label of the content type no longer breaks the remote field 🎉  However, I found another bug with remote field described here: #625.

**Review by laceysanderson — APPROVED** [review]

**Comment by spficklin** [comment]
Thanks @almasaeed2010 and @laceysanderson !!

**Pull request merged**
