### PR TITLE
Fix automated test chado install errors

### PR DESCRIPTION
**Pull request by laceysanderson**
# Bug Fix

Issue #1237 

## Description
Recently our automated testing switched to PostgreSQL version 14. This brought out a bug that had been lurking for a very long time 🤪 Apparently Chado feature location comparison functions have been using old notation (`@` to indicate contained in or on for geometric set operations) that was [deprecated in version 8.2](https://www.postgresql.org/docs/8.2/functions-geometry.html) and just finally removed in version 14. As such, this PR updates to the new contained in operator, `<@` and thus automated testing passes again 😄 

## Testing?
The tests passing on this PR should be sufficient but you can also confirm that chado installs locally on your own version of PostgreSQL. (Note: the new operator has been available since 2006 and is in all supported versions of PostgreSQL).

## Additional Notes

I also added my SQL patch for the create_point errors to make it easier for us to help people in the future. It includes instructions for applying manually and is not currently referenced anywhere 🤷

### CODE REVIEW

**Review by dsenalik — COMMENTED** [review]
"intented" should be "intended".
Otherwise awesome work, thanks for figuring this out!

**Comment by guignonv** [comment]
I have a concern about featureloc_createpoint.patch.sql: I think all the functions reside in the chado schema and therefore, the search_path should be set to chado instead of public.
`SET search_path = chado;`

Then, this:
```
DROP INDEX IF EXISTS chado.binloc_boxrange;
CREATE INDEX binloc_boxrange ON chado.featureloc USING GIST (boxrange(fmin, fmax));
```
should not be schema-qualified (ie. no `chado.`). I think this is important to make it more easy to use the script with Chado instances in other schemas not using the "chado" name.

**Review by guignonv — CHANGES_REQUESTED** [review]
- use `SET search_path = chado;`
- remove `chado.` prefix on lines 33 and 34.

**Comment by laceysanderson** [comment]
Thank you both for the comments!

I think the featureloc patch needs more discussion based on @guignonv's comments so I have removed it, for now, to allow this fix to be merged sooner.

The main fix was the small change to the default schema SQL taking into PostgreSQL version changes.

Unless there are any concerns with the default schema SQL changes, I'm going to merge this come Monday assuming the tests pass which they should.

**Pull request merged**
