### PR TITLE
Update TPPS Module Rating Badge

### PR DESCRIPTION
**Pull request by par12005**
# Documentation

## Description

I am applying for the Silver-level badge for TPPS as I meet the following requirements. TPPS was already approved for the Bronze rating in #947. I don't think TPPS needs to create any new TripalField classes, because it reuses existing ones provided by tripal_chado.

Repository: https://github.com/par12005/TPPS

## Bronze

| Requirement                                                                              | Status        |
|-------------------------------------------------------------|------------|
| Has a public release.  | [Yes](https://github.com/par12005/TPPS/releases) |
| Should install on a Tripal site appropriate for the versions it supports.  | [Yes](https://treegenesdb.org/tpps) |
| Defines any custom tables or materialized views in the install file (if applicable).  | [Yes](https://github.com/par12005/TPPS/blob/7.x-1.x/tpps.install#L191) |
| Adds any needed controlled vocabulary terms in the install file (Tripal3).  | [Yes](https://github.com/par12005/TPPS/blob/7.x-1.x/tpps.install#L345) |
| Provides Installation and admin instructions README.md (or RTD).  | [Yes](https://tpps.readthedocs.io/en/latest/install.html) |
| Has a license (distributed with module).  | [Yes](https://github.com/par12005/TPPS/blob/7.x-1.x/LICENSE) |

## Silver
| Requirement           | Status |
|------------------- |---------------------|
| Follows basic Drupal Coding standards; specifically, code format and API documentation.  | Yes |
| Uses Tripal API functions. Specifically, it should use the Chado Query API for querying chado (if using chado as the storage system).  | Yes (e.g. [chado.query for autocomplete fields](https://github.com/par12005/TPPS/blob/7.x-1.x/ajax/tpps_ajax.php#L18)) |
| Tripal Jobs API for long running processes.  | [Yes](https://github.com/par12005/TPPS/blob/7.x-1.x/admin/panel.php#L334) |
| TripalField class to add data to pages (Tripal3).  | Not Applicable |
| Provides ways to customize the module (e.g. drush options, field/formatter settings, admin UI).  | Yes, (e.g. [admin config panel](https://github.com/par12005/TPPS/blob/7.x-1.x/admin/config.php#L19)) |
| Latest releases should follow Drupal naming best practices. e.g. first release for Drupal 7 should be: 7.x-1.x.   | Yes (e.g. [7.x-1.0](https://github.com/par12005/TPPS/releases/tag/7.x-1.0)) |

This PR was made using [this template](https://gist.github.com/laceysanderson/d4c4534e6ac41ece3063f9b1270d749b)

### CODE REVIEW

**Comment by spficklin** [comment]
Hi @par12005 .  We noticed that the function calls don't seem to following the Drupal naming convention.  Here's the link with the rules: https://www.drupal.org/docs/develop/standards/coding-standards#naming

Specifically:

> Functions should in addition have the grouping/module name as a prefix, to avoid name collisions between modules.

There are probably parts of Tripal core that mess up on some of the coding standards so I'm not going to be difficult about it. But this is an important one because of the potential for naming conflicts. Can you fix it?

**Comment by par12005** [comment]
I forgot to change all those function names! Thanks for pointing this out! I think I've changed them all to abide by that rule now, if you'd like to take another look.

**Comment by spficklin** [comment]
Hi @par12005 

I'm just doing a quick check over all of the criteria and for bronze I don't see  a public release. The GitHub repository for TPPs has no items under the "releases" tab.   Drupal's rules for releases is here:  https://www.drupal.org/node/1015226.  Also, the tpps module is missing the version in the `tpps.info` file.  If you were to distribute the module via Drupal then it would automatically add the version number to the `.info` file for you.  But since you are using GitHub for distribution and users can't use drush to install this module you will need to put the `version` parameter in the .info file (see instructions here:  https://www.drupal.org/docs/7/creating-custom-modules/writing-module-info-files-drupal-7x#version).  

So, can you,
1)  Add a release to your module that follows the Drupal release naming convention
2)  Add that same release number to the `.info` file of your module.  

And in the future just remember each time you issue a new release you have to update both. 

I'm sorry we missed this on the Bronze classification, but the problem with not have a release is your module cannot provide updates as Drupal uses the release numbers to allow modules to provide updates.

As an aside, you can tie your module into Zenodo through GitHub. If you do that before you make a release then each time you make a release, Zenodo will add a DOI. You can then add a new DOI badge to your module on GitHub like core Tripal has and this will allow folks to reference specific release of your modules using DOIs.

**Comment by par12005** [comment]
Thanks @spficklin! I had a draft release but forgot to publish it! As for the version, the reason I left that out of my tpps.info file was because on the instructions it says "discouraged," so I figured it would be better to leave out. I've published the release and added the version number to tpps.info. I also added the Zenodo DOI integration and put the badge in my README.md.

**Comment by par12005** [comment]
My release keeps getting unpublished. I think this may have to do with my mirror configuration.

**Comment by spficklin** [comment]
> on the instructions it says "discouraged,"

Yes, Drupal wants to control it for you.  But in your case Drupal can't do it. So it's now highly encouraged :-)

**Comment by par12005** [comment]
Alright, I think I've got my release working now, if you would like to take a look!

**Comment by spficklin** [comment]
Thanks @par12005 .  I've merged the request.

**Comment by spficklin** [comment]
silver approved

**Review by spficklin — APPROVED** [review]

**Pull request merged**
