### PR TITLE
User's and Dev Guides migrated to Read the Docs.

### PR DESCRIPTION
**Pull request by spficklin**
Issue #566 

## Type(s) of Change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [x] Updates documentation (inline or markdown files)

## Description

This PR presents efforts by @bradfordcondon and myself to move our online Tv3 documentation over to read the docs.  The advantages include
1)  The documentation lives with the code.
2)  Others can easily tweak the documenation and provide updates.
3)  When code changes are made it's easier to adjust the documentation along with the code which improves the review process.
4)  The User's Guide can be made available in downloadable PDF.

## Testing?

Just review the current latest build here.   Tell us what you think, and if there's anything missing or mistakes in migration:  https://tripal.readthedocs.io/en/latest/

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
First of all, this is Awesome!!!

### Review for User Guide Only.
Differences I noticed (quoted text from ReadtheDocs):
- "Setup of an Example Site" should specify "Genomics" in the title. I think we should include this so I can one day add a guide for a breeding site.
- On Docs » User’s Guide » Install Tripal, "Themeing your Site" rather then creating a custom theme but *I like this change*
- On Docs » User’s Guide » Install Tripal » Server Setup » Server Setup (Ubuntu 18.04 LTS) 
    - In Ubuntu Installation "Please follow the online instructions for download and installation of Ubuntu *16.04* Desktop edition" should be *18.04*
    - In Apache Setup, "By default in Ubuntu *16.04*" should be *18.04*
    - In Setup PHP, "Drupal uses PHP. In Ubuntu *16.04* there are two different" should be *18.04*
    - In PostgreSQL Server, " PostgreSQL can be installed on Ubuntu *16.04*"
 - Docs » User’s Guide » Install Tripal » Upgrade from Tripal v2 to v3 under "Step 2: Migrate Content" the screenshot for "2. Select an individual content type" is incorrect.
- Docs » User’s Guide » Setup of an Example Site » Analyses the last screenshot on the page is incorrect.
- Docs » User’s Guide » Setup of an Example Site » Genomes and Genes the last screenshot on the page is wrong.
 - Docs » User’s Guide » Bulk Loader is missing the link to the file to be loaded and instructions on where to place it.
 - Noticed minor changes in wording of actual paragraphs and other fixes (numbering, etc.) all of which I like 👍 

Other Suggested Changes:
 - Docs » User’s Guide » Brief Drupal Overview » Finding Content, perhaps we should update this section to mention the new "Tripal Content" tab as well.
- Docs » User’s Guide » Setup of an Example Site » Genomes and Genes perhaps the following should be a notice box?
>  It is important to ensure prior to importing, that the FASTA loader will be able to appropriately match the sequence in the FASTA file with existing sequences in the database. Before loading FASTA files, take special care to ensure the definition line of your FASTA file can uniquely identify the feature for the specific organism and sequence type.
 - Docs » User’s Guide » Creating Content Types, I noticed you removed the table of common types. I'm not sure agree with this change as including that here increases the chances of people using the same term... I understand it may be difficult to maintain but worry people won't click through to the issue queue and wait for discussion.
- Docs » User’s Guide » Install Tripal » Automating Job Execution in Option #3 we should link to the readthedocs Tripal Daemon page (Docs » User’s Guide » Job Management (Tripal Daemon)) rather then github.
- I also think the Galaxy documentation should be moved out to that module.

**Comment by bradfordcondon** [comment]
>Docs » User’s Guide » Bulk Loader is missing the link to the file to be loaded and instructions on where to place it.

so theres wget instructions:

```

  cd /var/www/html/sites/default/files
  wget http://tripal.info/sites/default/files/book_pages/Fragaria_0.txt

```

but we need to decide where to host the file. Is this URL OK/will the server stay up?  Do we need to host it in github (is that too big?)


Thanks for the 👀 all of teh wrong screenshots were super obvious/easy to fix so I'll commit a fix very soon.

**Comment by spficklin** [comment]
Thanks @laceysanderson  for the review!  We'll make the corrections.

One request I have is to leave 'Setup of an Example Site' as is because we don't have any other example and there are some important steps even in that example that everyone needs to know.  I was worried if someone wasn't interested in setting up a genomics site that they would skip that section and miss important details so I renamed it.

**Comment by bradfordcondon** [comment]
the table i have moved to a seperate issue for further work... #598

**Comment by bradfordcondon** [comment]
I have incorporated all of @laceysanderson 's suggestions except...


* Setup of an Example Site (at @spficklin 's request)
* Docs » User’s Guide » Creating Content Types, I noticed you removed the table of common types. ... moved to seperate issue #598 
* I also think the Galaxy documentation should be moved out to that module.   ---> I will move this out once i make a PR to Galaxy.  it needs to be finished, too....

**Comment by spficklin** [comment]
thanks @bradfordcondon for making those fixes.

BTW... I think once @laceysanderson approves we can go ahead and merge since this isn't a code change that needs testing and 3 of us on the PMC like this change.

**Comment by spficklin** [comment]
Oh. I just remembered.  we do have one outstanding issue for the docs.  

1)  The copyright currently says the following: "2018, Stephen Ficklin, Lacey Sanderson, Bradford Condon et al".  I'm not sure if we can personally copyright this.  Usually our respective institutions would do that, but Tripal is multi-institutional so I don't know what this should be.  
2)  the author list  says: 'Stephen Ficklin, Lacey Sanderson, Bradford Condon et al'.   I think for the User's/Dev Guide this list of authors is okay, but I'm concerned someone may associate the authors with Tripal too.  Not just the authors of the doc.  

Can we just remove both of those?

**Comment by bradfordcondon** [comment]
Hi @spficklin 

these lines in conf.py can be altered.  copyright can be removed.  Author MUST be set.

```
copyright = u'2018, Stephen Ficklin, Lacey Sanderson, Bradford Condon et al'
author = u'Stephen Ficklin, Lacey Sanderson, Bradford Condon et al'

```

Can we set authors to The Tripal Software Foundation or something similar?

**Comment by spficklin** [comment]
I just moved the Galaxy docs over to the Galaxy Extension module.

**Comment by spficklin** [comment]
I also left the author in but made it blank and removed the copyright. We can add those back in after we've had time to discuss.

**Comment by laceysanderson** [comment]
Awesome :-)
I still have the developer docs to review which I will try to do tonight and a quick look over the changes but I agree with @spficklin that once we get a full look-through from all three of us, that should be enough.

**Review by laceysanderson — CHANGES_REQUESTED** [review]
### User Guide Review:
I checked all the changes and it looks great 👍 
### Developers Guide Review:
- I missed the introduction and requirements since it was on the bottom of [this page](https://tripal.readthedocs.io/en/latest/dev_guide.html). I later noticed it is in the TOC but at the bottom rather then the top.
- On [Selecting Vocal Terms](https://tripal.readthedocs.io/en/latest/dev_guide/custom_field/select_vocab_terms.html#case-5-you-really-cant-a-term), the heading reads “Case 5: You really can't a term!” when it should be “Case 5: You really can't find a term!”

Other then that the guide looks great. I added a number of issues to remind us to fill in sections that are missing but that's a goal for another day 😝

**Comment by bradfordcondon** [comment]
>On Selecting Vocal Terms, the heading reads “Case 5: You really can't a term!” when it should be “Case 5: You really can't find a term!”

its a joke, toned down from my original guide which was something like **so you're a monster: using a local term**. This is probably an improvement

>I missed the introduction and requirements since it was on the bottom of this page. I later noticed it is in the TOC but at the bottom rather then the top.


To fix this ill move them to a separate page and list them at the top of the toc

**Comment by laceysanderson** [comment]
> its a joke, toned down from my original guide which was something like so you're a monster: using a local term. This is probably an improvement

I like the joke by the way (and the original 😆) but was it meant to be missing the word "find"?

**Comment by bradfordcondon** [comment]
missing the word find **IS** the joke.  But as they say if you've got to explain it, its probably not a joke at all

not a joke so much as a meme.  and memes dont need to be in the guide.

**Comment by spficklin** [comment]
Okay, I have made the last few fixes requested by @laceysanderson and will be merging!

**Pull request merged**
