### PR TITLE
Restructure Prepare + add separate Import Type Collection

### LINKED ISSUE #1678: Restructure Prepare with separate modules creating Content Types in mind
### Task Description

Currently the prepare methods is a bit of a monolith. Specifically it does the following:

1. Creates Tripal Custom Tables
2. Creates Tripal Materialized Views
3. Import Terms + Ontologies
4. Create all the content types
5. Attach all the fields
6. Populate two core mviews: cv_root_mview and db2cv_mview

Items 1-3 + 6 are all focused mostly on Chado and thus it makes sense for them to remain together in the prepare. This also facilitates preparing multiple chado instances on a single site with these vocabularies and tables. This is traditionally run once right after tripal_chado is installed and never again. It will still be run once, right after install but then could be run again as needed.

Items 4 + 5 would traditionlly be run once and only on a single chado, right after tripal_chado install and before extension modules are installed. With extension modules handling more of the content type + field creation, this workflow no longer works.

Instead, I propose we have a button on the Admin > Tripal > Page Structure page which allows for bulk addition of content types. This would then have a generic UI which is essentially an interface for the tripal.tripalentitytype_collection and tripal.tripalfield_collection services. It would
 - auto-discover yml descriptions of content types and fields across all modules
 - allow the admin to select the yml file they would want to load
 - submit a job to load those specific content types.

There would not be a way to select the schema to install into as it would use the default chado schema. Admin can change the default chado schema through the Manage Chado Instances UI.

I don't believe this should impact the Prepare functionality that @spficklin is working on as that would work on any content type, not just those added in bulk.

I've added this to the release milestone as it's key to moving content types out of tripal/tripal and into extension modules.

If you have any concerns or suggestions regarding this plan, please comment below.

### Branch Name

tv4g1-issue1678-restructurePrepare

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task

## Description

This PR makes the following changes:
1. Removes creating content types and attaching fields from the old prepare. This allows the prepare functionality to be focused entirely on preparing a specific chado instance. It can be run repeatedly for as many chado instances as you want.
2. Create a new "Import Type Collection" form reached from the Tripal > Page Structure menu. This allows admin to choose specific collections of content types to be created. Each collection listed is a single yaml file with the `tripal.tripalentitytype_collection.*.yml` file and they are auto-detected.
3. Update the existing *collection services to allow install of a single collection at a time. Previously the `install()` method installed all files available, but now it takes an array of collection ids and only installs those specified.
4. Break up the original massive `tripal.tripalentitytype_collection.default_chado.yml` and `tripal.tripalfield_collection.default_chado.yml` files into one file per category of data type. This is in preparation for all data types except "General" moving into their own extension modules.
5. Create a drush command allowing people to automatically import type collections from the command-line.
6. Add a call to the above drush command to tripaldocker to import the general type collection by default.

### Automated Testing

Upgraded existing Function TripalEntityTypeCollectionTest to a number of Kernel Tests which result in a total coverage of `tripal/src/Services/TripalEntityTypeCollection.php`: 94.62% (123 / 130) lines and 100% coverage for 4 / 6 methods.

Screenshot 2023-11-20 at 4 09 13 PM

Existing Functional TripalFieldCollectionTest which had a total coverage of `tripal/src/Services/TripalFieldCollection.php`: 80.40% (160 / 199) lines and 100% coverage of 1/6 methods.

Screenshot 2023-11-20 at 4 12 12 PM

### Manual Testing

1. Create a fresh docker image + container on this branch.
2. Go to Admin > Tripal > Page Structure and confirm the General Types are the only ones present. NOTE: Until I finish the 2 TODOs in the description you will actually see no content types listed by default.
Page Structure showing only general content types
3. Click on the new "Import type collection" button to see the new form. Confirm that all the expected types are listed as shown below.
New Import type collection form
4. Choose 1+ of these types and click the Import button. You will see a message saying that the Tripal job was submitted.
5. Run the tripal job (i.e. docker exec CONTAINER drush trp-run-jobs --username=drupaladmin`) and confirm that it completes without error. It will list each content type being created and also list each field being added to that content type. For example, you will see the following if you choose to import Genomic Content types.
Terminal capture of import job
6. Go back to the Page Structure page and confirm that the content types for that collection are now present. Click on manage fields for a few and confirm the fields are present. Add content for a few and confirm it adds without error.
Page structure showing general and genomic content types
7. Click on the "Import type collection" button and select the same collection you already imported. Choose to import it and run the tripal job. Now you should see "Skip" in front of each one and still no errors.
8. Go to the command line and test the drush command. For example, `docker exec CONTAINER drush tripal:trp-import-types --username=drupaladmin --collection_id=germplasm_chado`

### CODE REVIEW

**Comment by dsenalik** [comment]
I know it is not fair to complain on a draft PR, sorry 😈, but I see this error at step 4 of manual testing
The website encountered an unexpected error. Please try again later.

Error: Class "Drupal\tripal\Services\Tripaljob" not found in Drupal\Component\DependencyInjection\Container->createService() (line 259 of core/lib/Drupal/Component/DependencyInjection/Container.php).

**Comment by laceysanderson** [comment]
Weird @dsenalik -I don't see that. What versions are you using? Can you attach a screenshot?

**Comment by dsenalik** [comment]
`--build-arg drupalversion="10.1.x-dev" --build-arg chadoschema='chado' --file tripaldocker/Dockerfile-php8.2-pgsql13`
20231120_genomic

Here's the full error screen:
The website encountered an unexpected error. Please try again later.

Error: Class "Drupal\tripal\Services\Tripaljob" not found in Drupal\Component\DependencyInjection\Container->createService() (line 259 of core/lib/Drupal/Component/DependencyInjection/Container.php).
```
Drupal\Component\DependencyInjection\Container->get('tripal.job') (Line: 197)
Drupal::service('tripal.job') (Line: 79)
Drupal\tripal\Form\ImportTripalEntityTypeCollection->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 597)
Drupal\Core\Form\FormBuilder->processForm('tripal_import_tripal_entity_type_collection', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 592)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by laceysanderson** [comment]
So, I wasn't able to reproduce what you saw for some reason 🤔 

```
git clone https://github.com/tripal/tripal.git tv4g1-issue1678-restructurePrepare
cd tv4g1-issue1678-restructurePrepare
git checkout tv4g1-issue1678-restructurePrepare
docker build --tag=tripalproject/tripal1678 --build-arg drupalversion="10.1.x-dev" --build-arg chadoschema='chado' --file tripaldocker/Dockerfile-php8.2-pgsql13 ./
docker run --publish=80:80 -tid --name=tripal1678 --volume=$(pwd):/var/www/drupal/web/modules/contrib/tripal tripalproject/tripal1678 
docker exec tripal1678 service postgresql restart
```

That said, reading the message more shows it's looking for `Tripaljob` when it should be `TripalJob`. I found two instances of this mistake and fixed them so hopefully it works for you now @dsenalik 🤷‍♀️

**Comment by dsenalik** [comment]
Confirming that step 4 works now for me.
Note that for step 5 I don't see as much output when running the job, just this
```
2023-11-21 12:52:26
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2023-11-21 12:52:26: Job ID 1.
2023-11-21 12:52:26: Calling: import_tripalentitytype_collection(Array)
```
but everything is created and works, all testing steps otherwise as expected.
The logger Notice messages are visible afterwards at `/admin/reports/dblog`

**Review by dsenalik — APPROVED** [review]
Awesome work with the added automated testing too!

**Comment by dsenalik** [comment]
I merged this branch into #1694, and the notice messages are now appearing. I'm not sure what I did with that other docker, but everything here still looks good.

**Comment by laceysanderson** [comment]
Thanks for the review + testing @dsenalik! Going to merge this now!

**Pull request merged**
