### PR TITLE
Much improved GFF3 loader

### PR DESCRIPTION
**Pull request by spficklin**
# New Feature

Issue #1040

## Description

The GFF3 loader is unbearably slow when Chado begins to fill up.  It can take days to load a genome.  This fix greatly improves the performance and adds a quite a few functional tests.

## Testing?

To test the GFF3 loader you can use any GFF3 file available to you, but it is best if you have one that contains as many of the GFF3 acceptable attributes (Dbxref, Alias, Target, Note, Ontology_Term).  

1. Create a new organism (if it doesn't already exist) for the GFF3 data
2. Create a new analysis (if it doesn't already exist) for the GFF3 data
3. Use the GFF3 loader to import the GFF3 file.
4. After import of the GFF3 file, publish the features of interest (e.g. genes, mRNA)
5. Review the pages to ensure all relevant details of your GFF3 file are present.

The loader takes about 5 minutes to import a GFF3 file with 1 million features.

You should see output similar to the following

```
2020-12-17 19:41:25
Tripal Job Launcher
Running as user 'admin'
-------------------
2020-12-17 19:41:25: There are 1 jobs queued.
2020-12-17 19:41:25: Job ID 214.
2020-12-17 19:41:25: Calling: tripal_run_importer(39)

Running 'Chado GFF3 File Loader' importer
NOTE: Loading of file is performed using a database transaction. 
If it fails or is terminated prematurely then all insertions and 
updates are rolled back and will not be found in the database

Opening /var/www/html/sites/default/files/tripal/users/1/Hebr.1_0.gff
Opening temporary cache file: /tmp/TripalGFF3Import_zXc0QF
Step  1 of 26: Caching GFF3 file...                             
Step  2 of 26: Find existing landmarks...                         
Step  3 of 26: Insert new landmarks (if needed)...                
Step  4 of 26: Find missing proteins...                           
Step  5 of 26: Add missing proteins to list of features...        
Step  6 of 26: Find existing features...                          
Step  7 of 26: Clear attributes of existing features...            
Step  8 of 26: Processing 1,020,864 features...               
Step  9 of 26: Get new feature IDs...                             
Step 10 of 26: Insert locations...                               
Step 11 of 26: Associate parents and children...                 
Step 12 of 26: Calculate child ranks...                          
Step 13 of 26: Add child-parent relationships...                 
Step 14 of 26: Insert properties...                               
Step 15 of 26: Find synonyms (aliases)...                         
Step 16 of 26: Insert new synonyms (aliases)...                  
Step 17 of 26: Insert feature synonyms (aliases)...              
Step 18 of 26: Find cross references...                          
Step 19 of 26: Insert new cross references...                    
Step 20 of 26: Get new cross references IDs...                   
Step 21 of 26: Insert feature cross references...                
Step 22 of 26: Insert feature ontology terms...                  
Step 23 of 26: Insert 'derives_from' relationships...            
Step 24 of 26: Insert Targets...                                 
Step 25 of 26: Associate features with analysis....              
Step 26 of 26: Adding sequences data (Skipped: none available)...

Done.
Committing Transaction...
```

### CODE REVIEW

**Comment by spficklin** [comment]
I should add that a huge thanks goes to @risharde and @par12005 for writing functional testing.

**Comment by spficklin** [comment]
I should also add that this GFF3 loader has been tested on many GFF3 files by myself and @Ferrisx4.  But before merging I think it should be tested just one more time by @Ferrisx4 on his most complex GFF3 files.

**Comment by Ferrisx4** [comment]
Testing the Hevea brasiliensis GFF from TreeGenes: https://treegenesdb.org/FTP/Genomes/Hebr/v1.0/annotation/Hebr.1_0.gff.gz, the following error was discovered:
Hebr 2020Dec18

**Comment by mpoelchau** [comment]
@Ferrisx4 interesting use case - technically the gff is legal since it looks like the gene is modeled as a discontinuous feature (see the 'ID' definition in the gff3 spec: https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md). However, most software (including apparently Tripal) expects features such as genes and mRNAs to not be modeled as discontinuous, even though in practice, in particular with poor genome assemblies, they are. 

Others that I've discussed this with have advocated for a more pragmatic approach towards modeling these 'broken' genes in order to not break software - e.g. have unique IDs for the features, but signify that they are from the same biological entity some other way (e.g. locus_tag for NCBI-derived gffs). 

We can bring this up with the AgBioData gff3 working group if that helps. From a software developer standpoint it would be great to hear @spficklin's or others' thoughts on this as well.

**Comment by spficklin** [comment]
Hey @Ferrisx4 that's one of the two genes I mentioned to you on Slack.  In that GFF3 file, notice that these two genes are both duplicated and have the same coordinates on the first feature.  So, I didn't think this was a discontinuous feature.  It seems like a mistake in the GFF3 file to me and not a problem with the loader. Can you check it?

```
NC_015308.1     RefSeq  gene    74171   74284   .       -       .       ID=gene42616;Dbxref=GeneID:10351928;Name=rps12;exception=trans>
NC_015308.1     RefSeq  gene    146419  147212  .       +       .       ID=gene42616;Dbxref=GeneID:10351928;Name=rps12;exception=trans>
```

```
NC_015308.1     RefSeq  gene    74171   74284   .       -       .       ID=gene42642;Dbxref=GeneID:10352012;Name=rps12;exception=trans>
NC_015308.1     RefSeq  gene    103189  103982  .       -       .       ID=gene42642;Dbxref=GeneID:10352012;Name=rps12;exception=trans>
```
@mpoelchau the loader does support two types of discontinuous features with the same ID. These are 

1. Alignment features (match, cDNA_match, EST_match, etc.)
2. Any item with a Parent tag.  So, this would allow CDSs for the same transcript to also use the same ID (or not have an ID at all) and still be associated with the transcript.

Anything else gets flagged as a problem.  

edit:

I should add this is the same behavior as the Chado GFF3 loader for continuous features. And if a discontinuous feature repeatedly uses the same ID, we are forced, due to constraints in Chado to make the ID unique.  So, we keep the name the same but the ID has to have some suffix added to ensure it's unique in the Chado constraints.

**Review by laceysanderson — APPROVED** [review]
Did a full code review on this PR and nothing jumped out at me. I like the new logic, the separating each stage into methods and the new batch functionality! Also, I greatly appreciate the automated testing! Great job!

NOTE: I did not do a functional test.

**Comment by spficklin** [comment]
Thanks @laceysanderson for the code review!  It was a lot of changes.

**Review by Ferrisx4 — APPROVED** [review]
Nothing in the code stands out at me as being a problem. Recent tests using GFF files from the TreeGenes database have performed well and successfully. I'll approve with the disclaimer that, given the irregularities found in GFF formatting, more edge cases yet undiscovered might need to be addressed. The overall performance and bug fixes, however, warrant an approval.

**Comment by spficklin** [comment]
Great! Thanks @Ferrisx4 .  I agree, we may find something in the future that may break. But that's par for the course.   I'll merge. I'm curious.  Were those two genes meant to be a discontinuous feature or was it a mistake in the GFF3 file?

**Pull request merged**
