### PR TITLE
Fix issue #350

### PR DESCRIPTION
**Pull request by almasaeed2010**
Hello,

This PR fixes issue #350 by preventing duplicate records from getting inserted.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by spectacledweb** [comment]
I'm worried this will keep actual records that should be inserted from being inserted. The test you've setup is: 
```
$find_query = db_select('chado.cvtermpath', 'CVTP');
$find_query->fields('CVTP', ['subject_id']);
$find_query->condition('object_id', $origin);
$find_query->condition('subject_id', $child_id);
$find_query->condition('type_id', $type_id);
$find_query->condition('pathdistance', $depth);
$exists = $find_query->execute()->fetchObject();
```

This isn't considering the cv_id and I believe there will be records that have the same object_id, subject_id, type_id, pathdistance but different cv_id's.

Did you test this against a large data set like gene ontology and ensure you're getting the same number of records without and without this check?

**Comment by almasaeed2010** [comment]
I've based this query on the fact that cvtermpath has only 1 unique constraint defined as such:
```
UNIQUE (subject_id, object_id, type_id, pathdistance)
```

Having this constraint in place means that a record that has all of those but a different cv_id cannot get inserted.

Thanks!

**Comment by almasaeed2010** [comment]
Sorry forgot to answer the tests question.

This is currently running on our dev server to repopulate Gene Ontology (cellular_component, biological_process, mollecular_function). It has finished both biological_process and cellular_component successfully (without any errors but I have no other proof that the content produced is accurate).

Thanks!

**Comment by spectacledweb** [comment]
I am aware of that constraint, it was the reason why the GoSlim wouldn't load because that unique constraint was failing because the cv's were different but everything else was the same. I believe @spficklin put in a ticket about it (am I remembering that correctly?).

The errors don't worry me, it's the number of records that get written. If the GO fully loads, ie exactly the same number as a previously loaded GOs, is what I am curious about.

**Comment by almasaeed2010** [comment]
I see your point. You think that chado might change that constraint so that ontologies like GoSlim can get inserted?

Unfortunately, we couldn't test the number of records before the fix since it kept failing to insert all available terms. However, if you have a fully loaded GO, I can provide the number of terms in cvtermpath for a given cv that you can compare. I'll add the numbers here once the run is completed.

**Comment by almasaeed2010** [comment]
**cellular_component**
```
select count(*) from chado.cvtermpath
   inner join chado.cv ON cv.cv_id = cvtermpath.cv_id
   where cv.name = 'cellular_component';


 count  
--------
 260030
(1 row)
```

**biological_process**
```
select count(*) from chado.cvtermpath
inner join chado.cv ON cv.cv_id = cvtermpath.cv_id
where cv.name = 'biological_process';

  count  
---------
 1872499
(1 row)
```

**molecular_function**
```
select count(*) from chado.cvtermpath
inner join chado.cv ON cv.cv_id = cvtermpath.cv_id
where cv.name = 'molecular_function';
 count  
--------
 107222
(1 row)
```

**Comment by spficklin** [comment]
I'm just checking on this PR.  Do we need more validation?

**Comment by shawnawsu** [comment]
Sorry, I lost visibility on this ticket when I went away on vacation. 

I checked the numbers and they line up. So it should be good to merge.

**Comment by spficklin** [comment]
PR merged!  Thanks @almasaeed2010

**Comment by almasaeed2010** [comment]
Great! Thanks @shawnamspoor and @spficklin

**Pull request merged**
