### PR TITLE
Fix issue with aliases token not filled (#790)

### PR DESCRIPTION
**Pull request by mboudet**
# Bux Fix

Issue #790 

## Description
1) Put the $field_ids definition outside the loop to avoid a reset.

2) Fixed token management for text fields (based on implementation in tripal_chado_field_storage_load)

### CODE REVIEW

**Comment by mboudet** [comment]
The travis fails with an out of memory error, but I'm not exactly sure why the changes would affect that..

**Comment by bradfordcondon** [comment]
the out of memory error is a problem with our travis setup/the OBO loader: its a consistent bug right now where 7.0 passes and 7.1 doesn't: please ignore it for now.

**Comment by bradfordcondon** [comment]
hi @mboudet thank you very much for the contribution.  I'd like @spficklin to weigh in before i pass judgement, but my hunch is that using the Chado implementation isn't correct, as base Tripal entities wont have the keys you added (chado_record, chado_table ,etc).

**Comment by mboudet** [comment]
You might be right, I only checked for the mRNA entity type, so it might bug out for others.
There might be an easier way to access the field value. 

Some tokens also seems to crash out (like the [data__image].. though I do not know why someone would want to use that, nor what the url would look like) when calling field_info_field

**Comment by mboudet** [comment]
While i'm doing some tests, we should probably add a check for the existence of $element in the $value array in _tripal_replace_entity_tokens_for_elements(). We just assume there is a value associated with the element, but it might not be the case.

(Example, the default page title format is [taxrank__genus] [taxrank__species] [taxrank__infraspecific_taxon,TAXRANK:0000045], but the infraspecific_name might not be set..)

**Comment by spficklin** [comment]
Hi @mboudet,

Yes @bradfordcondon is correct there should be no code in the tripal module that pulls data from Chado.  Anything that pulls data from Chado to populate fields should be in the tripal_chado module.  On the issue you posted #790 I approve of the fix for the first problem. If you want to cancel out this PR and submit that fix by itself we can get that merged in.  For the second issue I think we need to better understand why you're not getting values and that conversation. I'll post a follow-up quesion there.

**Comment by mboudet** [comment]
That's fine, I will submit the PR again. Thanks.

**Pull request closed without merging**
