### PR TITLE
Tripal 4 - NCBI Taxonomy Loader

### PR DESCRIPTION
**Pull request by risharde**
This is the first version of the NCBI Taxonomy Loader for Tripal 4
It also includes some basic tests to ensure it works properly
Issue #1513

### CODE REVIEW

**Comment by dsenalik** [comment]
I tested with my Drupal 10.1.1-dev PHP 8.2.6 docker on this branch with the current 4.x branch merged
I used my API key,
taxid 40921 (Anethum),
Root taxon: Apiales

```
 [notice] Running 'Taxonomy Loader' importer   
NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database   
 [notice] NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database   
Initializing Tree...   
 [notice] Initializing Tree...   
Insert phylotree: Created phylotree with phylotree_id: 1   
Rebuilding Tree...   
 [notice] Rebuilding Tree...   
Percent complete: 0%. Memory: 34,174,504 bytes.
 [notice] Percent complete: 0%. Memory: 34,174,504 bytes.
Importing Taxonomy IDs...
 [notice] Importing Taxonomy IDs...
 [error]  Error: Class "Drupal\tripal_chado\Plugin\TripalImporter\Exception" not found in Drupal\tripal_chado\Plugin\TripalImporter\TaxonomyImporter->importRecord() (line 973 of /var/www/drupal9/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/TaxonomyImporter.php) #0 /var/www/drupal9/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/TaxonomyImporter.php(377): Drupal\tripal_chado\Plugin\TripalImporter\TaxonomyImporter->importRecord('40921', 'apiales')
```

That's from this line `throw new Exception(t('Cannot add organism: @sci_name', ['@sci_name' => $sci_name]));`
see also line 455 that also needs the `\Exception` fix.

If I fix that https://github.com/tripal/tripal/pull/1560/commits/f92e13f5f42fb78db10de8907ef0502a25f287ab I get a proper error message (because I specified a genus!)
```
 [error]  ERROR: Cannot add organism: Anethum 
[site http://default] [TRIPAL] ERROR: Cannot add organism: Anethum
```

Try again with taxon id 40922 (Anethum graveolens)
```
...
 [notice] Updating Existing...
 [warning] Invalid placeholder (!count) with string: "WARNING: The following !count organisms do not have an NCBI taxonomy ID, and have not been included in the tree: !omitted_list" FormattableMarkup.php:245
 [warning] Invalid placeholder (!omitted_list) with string: "WARNING: The following !count organisms do not have an NCBI taxonomy ID, and have not been included in the tree: !omitted_list" FormattableMarkup.php:245
```

If I fix that https://github.com/tripal/tripal/pull/1560/commits/74a1fd618cdc60b135f22c4c675cf31282453dfd then we have success, just some missing quotation marks to fix
```
...
[warning] WARNING: The following 2 organisms do not have an NCBI taxonomy ID, and have not been included in the tree: Tripalus bogusii subsp. fakus", "Tripalus bogusii
[site http://default] [TRIPAL] WARNING: The following 2 organisms do not have an NCBI taxonomy ID, and have not been included in the tree: Tripalus bogusii subsp. fakus", "Tripalus bogusii
Import phylotree: Associated Anethum graveolens to organism_id: 3
Import phylotree summary: 1 were successfully associated to content, 0 nodes could not be associated
Done.
 [notice] Done.
```

**Comment by dsenalik** [comment]
So I have a question, should those `\Exception`s be changed to `logger->error` ?

**Comment by dsenalik** [comment]
By chance I had a download glitch retrieving an xml, and the retry kicked in.
```
 [notice] Importing Taxonomy IDs...
 [warning] fopen(https://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=taxonomy&id=40922): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 TaxonomyImporter.php:914
Percent complete: 25.00 %. Memory: 32,064,184 bytes.
 [notice] Percent complete: 25.00 %. Memory: 32,064,184 bytes.
```
but I see in that loop there is no informative message, so add one with https://github.com/tripal/tripal/pull/1560/commits/36586f6184e98c21032eff6c42d3d9c822998029

**Comment by risharde** [comment]
Thanks Doug, I really didn't test this with an API key. I'll try to do that
soon!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dsenalik** [comment]
Okay, API key is not working. And to be sure it wasn't something I did, I built a nice new docker on this branch at commit https://github.com/tripal/tripal/pull/1560/commits/578ad3bb743863aced62bdbf05c5252b80706fbd which is before I changed anything
`$ git branch`
`* (HEAD detached at 578ad3bb7)`
1. enter something in the API Key box
2. click on another box
3. observe this message
Screenshot_2023-07-06_14-06-31
4. observe this in the log
`Symfony\Component\HttpKernel\Exception\HttpException: The specified #ajax callback is empty or not callable. in Drupal\Core\Form\FormAjaxResponseBuilder->buildResponse() (line 67 of /var/www/drupal9/web/core/lib/Drupal/Core/Form/FormAjaxResponseBuilder.php).`

**Review by dsenalik — APPROVED** [review]
Well, with the Ajax fixed https://github.com/tripal/tripal/pull/1560/commits/915898d20b4d40a8b4537c8e057d45b91c2122e2 + https://github.com/tripal/tripal/pull/1560/commits/3d04960a4c0fafefd92cfdfef2f77d96f27d7482, now everything appears to be working as expected. I was able to import an organism, I verified that my API key was saved, and was used in the queries (using a temporary print of the url generated). After import, the organism was in the chado.organism table, and chado.organismprop values were populated for (genetic_code_name, lineage, genetic_code, division, mitochondrial_genetic_code_name).

I have renamed the variable used to store the NCBI API key, because it could also be used by other loaders (pub importer) or modules (tripal_eutils), so a more generic name is appropriate `tripal_taxon_importer_ncbi_api_key` becomes `tripal_ncbi_api_key`

**Comment by dsenalik** [comment]
I've added a few kernel tests for the api functions, and I'm going to merge this, but because the Newick loader is not yet implemented, Issue #1513 will remain open for implementing that, functional tests for that, and implementing API kernel tests that require that loader for testing.

**Pull request merged**
