### PR TITLE
Fix for missing pager in Views

### PR DESCRIPTION
**Pull request by spficklin**
Issue #535

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

It seems a recent fix has disrupted the pager on views based on Tripal content types.  This PR fixes the problem.

## Testing?

Simply pull the branch and go to any search based on a Tripal content type.  You should see the pager. Without this fix the pager is missing.

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by spficklin** [comment]
This is a simple fix and only affects a few lines of code.  I think one review is all that is needed.

**Review by almasaeed2010 — APPROVED** [review]

**Comment by almasaeed2010** [comment]
Works for us 👍 

screen shot 2018-08-11 at 8 11 20 am

**Comment by bradfordcondon** [comment]
@spficklin assigned this as one reviewer and @almasaeed2010 has approved, so i am merging.

**Comment by spficklin** [comment]
Thanks @almasaeed2010 and @bradfordcondon

**Pull request merged**
