### PR TITLE
Backport of OBO and cvtermpath updates to Tripal v2

### PR DESCRIPTION
**Pull request by spficklin**
**NOTE: this is a PR for update to Tripal v2** 

This pull request responds to the last comment of issue #253. We have made many fixes to the OBO importer and cvtermpath importer of Tripal v3 that did not get included into Tripal v2. This pull request fixes that.

With this PR I can successfully node the full GO on a Tripal v2 site with the following number of entries added to the cvtermpath:

biological_process: 1,656,785
molecular_function: 43,944
cellular_component: 152,030

I can also load the Plant GO Slim without issues.

### CODE REVIEW

**Comment by spficklin** [comment]
Oh, this fix also includes a few other minor fixes for PHP 7.2 compatibility and a few typos for views.

**Comment by bradfordcondon** [comment]
I've confirmed loading GOslim successfully.

**Comment by spficklin** [comment]
It seems there are two approvals on this... one from @bradfordcondon and one from @laceysanderson . I'm going to merge.

**Comment by laceysanderson** [comment]
Oh, I had just added the reviewer #1 tag for Bradford since he had forgot... I didn't actually get the chance to test this yet --Sorry for the confusion! It's likely good though 🤷‍♀️

**Comment by bradfordcondon** [comment]
i neglected to add it because i had only tested one piece of the functionality the plant GOslim.  and I am a little intimidated by this portion of the code...

**Pull request merged**
