### PR TITLE
Add tripal web services http tests

### PR DESCRIPTION
**Pull request by almasaeed2010**
Issue #567

## Type(s) of Change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)
- [x] Unit Tests

## Description

Adds unit tests to verify that http calls to web services behave as expected.

## Testing?

1. Be sure to run `composer update` to get the latest version of TripalTestSuite
2. Run `./vendor/bin/phpunit tests/tripal_ws` (there are no side effects to running tests since they are wrapped in a transaction)
3. Verify all assertions are passing (green)

## Additional Notes (if any):

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

I encountered an issue when testing pulling a newly published feature. When sending a GET request to `/web-services/content/v0.1/mRNA/$entity_id`, where `$entity_id` is a newly created mRNA entity, I get an error indicating that the entity is not available. However, using `tripal_load_entity()` finds and loads the entity perfectly fine. Any idea why this test doesn't pass? (see method `testGettingAFeatureResource()` in this PR).

Thanks!

### CODE REVIEW

**Comment by spficklin** [comment]
So I botched up the fix for PR #565.  You will want to merge in the new fix (PR #575) to this PR once it gets merged into the 7.x-3.x branch.

**Comment by almasaeed2010** [comment]
Ok so I merged master, fixed the tests and added a new travis env file. This should make tests pass here (we'll see). Thanks for the help @spficklin

**Comment by bradfordcondon** [comment]
these are the errors on travis
```

..[Thu Aug 23 18:56:28 2018] 127.0.0.1:51366 [404]: /web-services/content/v0.1 - No such file or directory
F[Thu Aug 23 18:56:28 2018] 127.0.0.1:51368 [404]: /web-services/content/v0.1/Organism - No such file or directory
```

Confirmed passing when I set my `.env` file correctly.

**Comment by bradfordcondon** [comment]
@almasaeed2010 do we have any previous tests taht confirm the web-client component of our travis environment are working properly?

See, for example, https://docs.travis-ci.com/user/gui-and-headless-browsers/#starting-a-web-server

We specify PHP and Postgres but not, say, apache... do we have a webserver running?

**Comment by almasaeed2010** [comment]
So this is where we run our web server:

https://github.com/tripal/tripal/blob/3b6306a209dc935949304e0915336ecdc15fc878/.travis.yml#L49

I am not sure yet why this is not working though. I am gonna try figuring this out on another module then submit a fix once I understand the issue better.

So let's put this on pause for a few days.

Thanks!

**Comment by almasaeed2010** [comment]
this PR is contingent on an issue with the TripalTestSuite package: https://github.com/statonlab/TripalTestSuite/issues/111

**Comment by almasaeed2010** [comment]
The tests should pass once #679 gets merged.

**Comment by spficklin** [comment]
Issue #679 is now merged.  Testing on this can continue...

**Comment by bradfordcondon** [comment]
test pass: @almasaeed2010 is this ready for review?

**Comment by almasaeed2010** [comment]
Yep this is ready for review. If you can think of more tests that I should include, I'd be happy to implement them. I think this gives a pretty good example on how to use HTTP testing.

**Comment by spficklin** [comment]
This PR has these files are they really needed:

- .travis.yml
- composer.lock
- tests/.travis.env

**Comment by almasaeed2010** [comment]
Hello @spficklin. Yes the changes are needed for the following reasons:
- `.travis.yml`:  Use the PHP default server instead of drush.
- `composer.lock`: Updates TripalTestSuite to the latest version
- `tests/.travis.env`: Adds the newest environment variables that TripalTestSuite  provides.

The HTTP tests in the older TripalTestSuite were bugged and that's what made these tests fail.

Please let me know if you have any questions. Thanks!

**Review by bradfordcondon — COMMENTED** [review]
Tests are passing locally and on travis, way to go!

**Review by bradfordcondon — APPROVED** [review]

**Review by laceysanderson — APPROVED** [review]
These tests look good to me and passed on my local dev site. Thanks for the addition @almasaeed2010!

**Pull request merged**
