### PR TITLE
Support detailed upload file format descriptions

### LINKED ISSUE #1656: Defining the upload description in a Tripal Importer doesn't easily accomodate detailed and formatted descriptions
### This feature attempts to solve an existing problem

No

### I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

No

### Is this feature urgent?

No

### Description

Currently, writing an upload description for a custom Tripal Importer is done in the annotation of the class. This can feel limiting in terms of writing long and detailed upload descriptions which describe the file format for upload, especially if custom HTML markup is desired. While there is a workaround to make it work in the annotation, the resulting code looks pretty gross 😜 For example, in order to span multiple lines for a single property, additional lines have to be uncommented within the annotation.

Here is how the upload description is currently displayed for my custom importer:

Screen Shot 2023-09-26 at 3 49 20 PM
<p>

And here is how the code looks to accomplish it:

Screen Shot 2023-09-26 at 3 54 26 PM

### Your specific use case

_No response_

### Generally Applicable

_No response_

### Additional information/screenshots

_No response_

### PR DESCRIPTION
**Pull request by laceysanderson**
# New Feature

## Description

This PR adds a method to allow TripalImporter developers to provide formatted and detailed upload file descriptions. It is backwards compatible :-)

Whereas before, an importer wanting to provide a HTML list describing the columns would need to do something like this:

Now they can implement the `describeUploadFileFormat` in their importer class like this:

```php
/**
 * @{inheritdoc}
 */
public function describeUploadFileFormat() {
  $output = "Germplasm file should be a tab separated file with the following columns:";

  $columns = [
    'Germplasm Name' => 'Name of this germplasm accession.',
    'External Database' => 'The institution who assigned the accession.',
    'Accession Number' => 'A unique identifier for the accession.',
    'Germplasm Species' => 'The species of the accession.',
    'Germplasm Subtaxa' => 'Subtaxon can be specified here or any additional taxonomic identifier.',
    'Institute Code' => 'The code for the Institute that bred the material.',
    'Institute Name' => 'The name of the Institute that bred the material.',
    'Country of Origin Code' => '3-letter ISO 3166-1 code of the country in which the sample was originally sourced.',
    'Biological Status of Accession' => 'The 3 digit code representing the biological status of the accession.',
    'Breeding Method' => 'The unique identifier for the breeding method used to create this germplasm.',
    'Pedigree' => 'The cross name and optional selection history.',
    'Synonyms' => 'Any synonyms of the accession.',
  ];

  $output .= '<ol>';
  foreach ($columns as $title => $definition) {
    $output .= '<li><b>' . $title . '</b>: ' . $definition . '</li>';
  }
  $output .= '</ol>';

  return $output;
}
```

Additionally, they can also use a twig template :-)

## Testing?

Test that this is a backwards compatible change by loading each of the core loaders and confirming that they are the same as before.

Test in an existing importer by implementing the `describeUploadFileFormat` method and returning a string. Then confirm that the string shows up as expected above the upload file form element.

### CODE REVIEW

**Comment by reynoldtan** [comment]
All core data loaders appear the same particularly the placement of text description about the file upload.

Implemented **describeUploadFileFormat()** method and it produced the following list in the preferred location 💯 

```
/**
 * {@inheritdoc}
 */
public function describeUploadFileFormat() {
  return 'Title Text<ol><li>Item 1</li> <li>Item 2</li> <li>Item 3</li></ol>';
}
```
Screen Shot 2023-09-27 at 1 10 36 PM

**Review by reynoldtan — APPROVED** [review]

**Comment by reynoldtan** [comment]
I also tried using a twig template using the steps below.

1. define a theme in your .module file
```
function my_module_theme($existing, $type, $theme, $path) {
  return [
    'header-theme' => [
      'template' => 'header-template-file',
      'variables' => [
         'data' => [
           'headers' => []
         ]
      ]
    ]
  ];
}
```

2. in your /templates directory create the template file (twig) required by the template key in the hook_theme above.

**templates/header-template-file.html.twig**
```
<ol>
    {% for header,description in data.headers %}
    <li>
      <strong>{{header}}</strong>: {{description}}
    </li>  
    {% endfor %}
</ol>

```

4. in the method **describeUploadFileFormat()**
```
/**
 * {@inheritdoc}
 */
public function describeUploadFileFormat() {   
  $headers = [
    'Header 1' => 'Header 1 Description',
    'Header 2' => 'Header 2 Description',
    'Header 3' => 'Header 3 Description',
    'Header 4' => 'Header 4 Description',
    'Header 5' => 'Header 5 Description',
  ];
    
  $build = [
    '#theme' => 'header-theme',
    '#data' => [ 
      'headers' => $headers,
    ],
  ];

  return \Drupal::service('renderer')->render($build);
}
```

Output:
Screen Shot 2023-09-27 at 2 00 46 PM

**Review by carolyncaron — APPROVED** [review]
It works for mine as well! :tada: 
Screen Shot 2023-09-27 at 2 13 31 PM

I also confirmed backwards compatibility with the FASTA and GFF3 importers 👍 (Fun fact: If you have 2 Tripal dockers going at once, then you can't stay logged in to both websites at the same time 🙃)

**Comment by laceysanderson** [comment]
Thank you both for the reviews!

**Pull request merged**
