### PR TITLE
Publication Importer fix Tv3

### PR DESCRIPTION
**Pull request by spficklin**
Issue #438 

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)
This publication does not import properly:  https://www.ncbi.nlm.nih.gov/pubmed/?term=29792315.  The problem is that it has embedded HTML in the title and abstract (e.g. ```<i>Juglans</i>```).  That threw off the XML importer.  This PR fixes the problem.

## Description

Use this drush command to import the publication:
```
drush trp-import-pubs --dbxref=PMID:29792315 --username=[username]
```
(substitute the [username] tag)

Then publish new entities of type "Publication" and find the new publication page.  You should see it has a title and an abstract.  Previously the import would fail completely and not import or it would import partially and the title would be truncated and the abstract missing.

This is such a simple PR and it has already been tested by @bradfordcondon with issue #438 that I think this only needs on reviewer. 

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
did you make any changes since i tested?  If no I can just approve and we can merge.

**Comment by spficklin** [comment]
No changes. I just did a PR on that same branch as it was.

**Comment by spficklin** [comment]
Although I just now fixed a small merge conflict.

**Comment by bradfordcondon** [comment]
OK great then I approve :) 👍

**Pull request merged**
