### PR TITLE
Compatibility with Drupal 10.0 🎉  (and keeping 9.4 and 9.5)

### LINKED ISSUE #1378: Having TripalDBX compatible with Drupal 10
Several breaking changes in Drupal core (https://www.drupal.org/node/3129492 , https://www.drupal.org/node/2768219) makes current version not compatible with Drupal 10.

The database driver namespace change can be supported if we raise Tripal minimum Drupal version to 9.4.
The per-table prefix support change, however, is more tricky since there were many changes in database Connection class. Since Drupal 10, there is no support for per-table prefixing, therefore they change the way they handle database table prefixing because there is still a support for (all) table prefixing. It needs to be investigated and tested but it will not be simple as we would still support per-table prefixing in Drupal 10 if we want to stay backward compatible with Drupal 9.

Drupal 10 Connection::setPrefix() now only supports string as argument and not array anymore. "tablePlaceholderReplacements" class member must also be initialized while it does not exist in Drupal 9. And there are many other details that are not easily solvable. But it does not appear impossible to do.

Do we want to keep Drupal 9 per-table support and have a different release for Drupal 10? Do we want to drop per-table support and rise minimum requirements to Drupal 9.4? Do we want to back port changes of Drupal 10 Connection into Drupal 9 to have only one branch for both Drupal 9 and 10? Do we have time to spend on that and maintain back ports of future D10 changes into Tripal DBX Connection? ... Discussion is open.

### LINKED ISSUE #1510: Get Tests to pass on Drupal 10
# Core Tripal 4 Development Task

## Branch Name: tv4g9-issue1510-testsPassingOnD10

We need to get our tests passing on Drupal 10 as it has been officially released and we need to support it ASAP.

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task

Issue #1510 and #1378

## Description

This PR achieves compatibility of Tripal 4 with Drupal 10.0 while keeping compatibility with Drupal 9.4.x and 9.5.x. We will be dropping support for 9.2.x and 9.3.x which are no longer supported by Drupal anyway.

### Summary of Changes

**As this was a combined effort between myself and Valentin, I'll tag the person responsible in the list below.**

- Cloning functions originally installed during Tripal Chado module install are not added to a temporary schema as needed.  (Valentin)
    - This ensures that the functionality is available even if you choose to install Drupal in a separate database than Chado. 
    - It also ensures we do not clutter the public schema with functions we may never use and 
    - removes the assumption that Drupal is stored in the public schema.
- Updates all automated tests to use the `stark` theme instead of the `stable` testing theme.  (Lacey)
    - Stable testing theme removed in Drupal 10. Choices are now stark or Olivia (for testing expecting HTML classes)
- Drupal 10 moved the PostgreSQL database connection and schema classes into a different namespace. This PR adopts the new namespace.  (Valentin)
    - Was \Drupal\Core\Database\Driver\pgsql\Connection
    - Now Drupal\pgsql\Driver\Database\pgsql\Connection
- Updated Jobs view page to use the new RouteObjectInterface as \Symfony\Cmf\Component\Routing\RouteObjectInterface was removed in Drupal 10.  (Lacey)
- Updated Regex for Schema names to allow matching within a string (removed `^` and `$`).   (Valentin)
- Also added a Table names regex to make it more clear what we are matching and provide support for different regex in the future as needed.  (Valentin)
- Updated TripalDbx->getDrupalSchemaName() to remove assumption that Drupal was installed in a schema named public and to be less brittle in the testing environment when checking if the database is postgresql.  (Valentin + Lacey)
- Combined TripalDbxConnections schemaName and extraSchemas into a single usedSchemas array.  (Valentin)
- Fix bug in TripalDbxConnection constructor which was making incorrect changes to the settings.yml connection options and caused errors in Drupal 10.  (Lacey + Valentin)
- Updated getSchemaName() and getQuotedSchemaName() to match expectations if no schema was specified.  (Lacey)
- Remove setPrefix() method from TripalDbxConnection which is no longer needed.  (Valentin)
- Complete rewrite of prefixTables() in TripalDbxConnection for better handling of many cases and support for changes made in Drupal 10.  (Valentin + Lacey)
- Update automated tests to match PHPUnit 10 best practices for mock objects.  (Lacey)
- Updated a number of tests which were out of sync with the codebase and thus failing to match current expectations.  (Lacey)
- Fixed bug where the Default schema was not being set automatically. Now the first chado installed becomes the default schema. This can still be changed in the Chado management tools.  (Lacey)
- Update cloning Task to use the new temporary cloning function.  (Lacey)

### Automated Testing

Automated testing should pass for all workflows testing Drupal 9.4.x, 9.5.x and 10.0.x. Support is dropped for 9.3.x and 9.2.x so those workflows are expected to fail.

### Docker for this branch

```
git clone https://github.com/tripal/tripal.git tripal-1517-d10
cd tripal-1517-d10
git checkout tv4g2-issue-1378-tripaldbx-d10-compatibility
docker build --tag=tripaldocker:testD10 --build-arg drupalversion="10.0.x-dev" --build-arg chadoschema=testchado --file tripaldocker/Dockerfile-php8.1-pgsql13 ./
docker run --publish=80:80 --name=testD10 -tid --volume=`pwd`:/var/www/drupal9/web/modules/contrib/tripal tripaldocker:testD10
docker exec testD10 service postgresql restart
```

For more reasons on why the above commands check out @dsenalik documentation here: https://tripaldoc.readthedocs.io/en/latest/contributing/docker-for-testing.html#testing-an-unmerged-pull-request

### Manual testing

Confirm that you can 
- install a new Tripal site (also confirmed by docker build),
- Create Tripal content types
- Create Tripal Content
- Anything else that tickles your fancy that you were able to do in Tripal 4 before should still work.

NOTE: Data importers are not quite working in Drupal 10 just yet. This will be fixed in a future PR.

### CODE REVIEW

**Comment by laceysanderson** [comment]
NOTE: Do not try the importers just yet. They seem to have a few incompatibilities in them although the tests are passing. These will be fixed in a future PR.

**Comment by dsenalik** [comment]
Creating content works perfectly.
However, I happened to go to this page "Tripal Content Terms"
/admin/tripal/config/terms
and see this error

The website encountered an unexpected error. Please try again later.

_Symfony\Component\Routing\Exception\MissingMandatoryParametersException_: Some mandatory parameters are missing ("config") to generate a URL for route "entity.tripal_content_terms.devel_load". in _Drupal\Core\Routing\UrlGenerator->doGenerate()_ (line _181_ of _core/lib/Drupal/Core/Routing/UrlGenerator.php_). 
```
Drupal\Core\Routing\UrlGenerator->getInternalPathFromRoute('entity.tripal_content_terms.devel_load', Object, Array, Array) (Line: 291)
Drupal\Core\Routing\UrlGenerator->generateFromRoute('entity.tripal_content_terms.devel_load', Array, Array, 1) (Line: 105)
Drupal\Core\Render\MetadataBubblingUrlGenerator->generateFromRoute('entity.tripal_content_terms.devel_load', Array, Array, 1) (Line: 765)
Drupal\Core\Url->toString(1) (Line: 182)
Drupal\Core\Utility\LinkGenerator->generate(Object, Object) (Line: 95)
Drupal\Core\Render\Element\Link::preRenderLink(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 788)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 374)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 204)
Drupal\Core\Render\Renderer->render(Array) (Line: 477)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 77)
__TwigTemplate_34946472be35ccd4518fe76ed610006d->doDisplay(Array, Array) (Line: 394)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 367)
Twig\Template->display(Array) (Line: 379)
Twig\Template->render(Array, Array) (Line: 40)
Twig\TemplateWrapper->render(Array) (Line: 53)
twig_render_template('core/modules/system/templates/links.html.twig', Array) (Line: 372)
Drupal\Core\Theme\ThemeManager->render('links__dropbutton', Array) (Line: 433)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 204)
Drupal\Core\Render\Renderer->render(Array) (Line: 477)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 179)
__TwigTemplate_b7b6763693d63c9e8dbc6b54b96b0a08->doDisplay(Array, Array) (Line: 394)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 367)
Twig\Template->display(Array) (Line: 379)
Twig\Template->render(Array, Array) (Line: 40)
Twig\TemplateWrapper->render(Array) (Line: 53)
twig_render_template('core/themes/claro/templates/classy/dataset/table.html.twig', Array) (Line: 372)
Drupal\Core\Theme\ThemeManager->render('table', Array) (Line: 433)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 446)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 204)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 238)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 580)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 239)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 128)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 168)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 74)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 686)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by dsenalik** [comment]
Oh, this is not specific to this branch, I just tried on another docker. Probably this will need to be a new issue...

### Issue #1518

**Review by dsenalik — APPROVED** [review]
I looked at the code changes and 😵‍💫, but functional tests good so far!

**Comment by laceysanderson** [comment]
Awesome, Thanks for the manual testing! I'm going to merge and we can fix the importers and anything else that pops up in future PRs.

**Pull request merged**
