### PR TITLE
Drupal 9 End of Life

### LINKED ISSUE #1673: Drupal 9 End of Life
### Task Description

Today was the [official Drupal 9 End Of Life](https://www.drupal.org/psa-2023-11-01). 

> Drupal 9 relies on several other software projects, including Symfony, CKEditor, and Twig. With Symfony 4's end of life, CKEditor 4's end of life, and Twig 2's end of life all coming up soon, Drupal 9 went end of life on November 1st, 2023. There will be no further releases of Drupal 9.
> 
> Two changes for Drupal contributed projects will occur before the end of January 2024. One is that the automated testing platform DrupalCI support for Drupal 9 will stop. The other is that release branches of contributed projects that only support Drupal 9 will be marked unsupported (see the [tracking issue for details](https://www.drupal.org/project/drupalorg/issues/3398253)).
> 
> Thanks to everyone who helped create and maintain Drupal 9.

As such we will want to drop support ourselves for Drupal 9.4 and 9.5. This means they need to be removed from the README, automated testing workflows and anywhere else they may occur in the documentation.

Additionally, we should update tripaldocker to no longer use `drupal9` in the path.

Luckily none of this is a concern as we have full support for Drupal 10.0.x and 10.1.x which are now the preferred versions of Drupal.

### Branch Name

`tv4g0-issue1673-remove-drupal-9`

### PR DESCRIPTION
**Pull request by dsenalik**
# Tripal 4 Core Dev Task

## Description
This removes all of the Drupal 9 automated tests and configurations, as well as PHP 8.0 which was only used for Drupal 9.

## Testing?
Let's build a docker and see if it works. Looks good
pr1681

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
Thanks for taking a stab at this @dsenalik -very thorough ❤️ 

Let's not put drupal10 in the directory structure though... like `\var\www\drupal\web`... and maybe out of the password as well.

**Comment by dsenalik** [comment]
I wondered about that, I just went for the least disruptive change.
I'll see what I can do...

**Comment by laceysanderson** [comment]
These changes all look good but we can't merge them until the tripal test action is updated. See https://github.com/tripal/test-tripal-action/pull/2

**Review by laceysanderson — APPROVED** [review]
This should now be ready to merge assuming all the automated testing passes 🤞

**Comment by dsenalik** [comment]
Commit https://github.com/tripal/tripal/pull/1681/commits/2f2c50444864083cf2f4c35f5f67aaec4f93a4fa adds a symlink /var/www/drupal9 that points to /var/www/drupal in the docker images to minimize any disruption for anyone who may be using the old version of the path for modules or testing.

**Comment by laceysanderson** [comment]
Ok, merging! Thanks for your work on this @dsenalik!

**Pull request merged**
