### PR TITLE
Support Drupal 11.0.x + 11.1.x

### LINKED ISSUE #1898: Add support for Drupal 11.0
### Task Description

Drupal 11.0 will be released the week of July 29, 2024
https://www.drupal.org/about/core/policies/core-release-cycles/schedule

Once rc1 is released in early July, we can start adding to automated testing and see what mysteries await us

### Branch Name

tv4g9-issue1898-drupal-11-0

### PR #1953

### PR DESCRIPTION
**Pull request by dsenalik**
# New Feature

## Description
Changes to support Drupal 11.0.x-dev and 11.1.x-dev.

~~The docker has been updated to not attempt to install tripal_layout on Drupal 11 since we are waiting on https://www.drupal.org/project/field_group_table/issues/3430507. We are no longer trying to get Tripal Layout D11 compatible in this PR as that issue has been RTBC for months 😒 Instead we are focusing on the other Tripal Core modules so we don't get further behind 🙈~~

Field Group Table has finally been made D11 compliant! This PR thus intends to bring all Tripal modules to be compatible with D11 :-)

Status: All automated tests are passing, warnings have been dealt with and deprecation notices have been addressed. However, a thorough testing of a D11 site through the UI has not yet been done.
Basic testing for D11 was done in comment https://github.com/tripal/tripal/pull/1953#issuecomment-2479180184

## Testing?
1. Build a docker on this branch, e.g. 
```
docker build \
  --tag=tripaldocker:testing-1953 \
  --build-arg drupalversion="11.0.x-dev" \
  --build-arg postgresqlversion="16" \
  --build-arg chadoschema="chado" \
  --progress=plain \
  ./
git='where you have this checked out'
docker run \
  --publish=8080:80 -tid \
  --name=1898 \
  --volume=$git:/var/www/drupal9/web/modules/contrib/tripal \
  tripaldocker:testing-1953
```
2. Go to your site and start doing stuff and find out what is broken,
    e.g. it looks like autocomplete is not working for infraspecific type.

3. Make sure the javascript fix from commit https://github.com/tripal/tripal/pull/1953/commits/3ad8feb7897052fb5672f3bdf47331f6e54e5555 
  works on both Drupal 11.0 and 10.x, you just need to go to the GFF3 importer
  and upload a file, you don't need to actually run the importer.

## Tasks
- [x] **Fix autocomplete**
`Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[22025]: Invalid escape sequence: 7 ERROR: invalid escape string HINT: Escape string must be empty or one character.: SELECT "CVT"."name" AS "name", "CVT"."definition" AS "definition", "CVT"."cvterm_id" AS "cvterm_id", "DBX"."accession" AS "accession", "CV"."name" AS "CV_name" FROM chado.cvterm "CVT" INNER JOIN chado.cv "CV" ON "CV".cv_id = "CVT".cv_id INNER JOIN chado.dbxref "DBX" ON "DBX".dbxref_id = "CVT".dbxref_id INNER JOIN chado.db "DB" ON "DB".db_id = "DBX".db_id WHERE ("DB"."name" = :db_condition_placeholder_0) AND ("CVT"."name"::text LIKE :db_condition_placeholder_1 ESCAPE '\\'); Array ( [:db_condition_placeholder_0] => CO_010 [:db_condition_placeholder_1] => subspecies% ) in Drupal\tripal_chado\Plugin\TripalIdSpace\ChadoIdSpace->getTerms() (line 426 of /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalIdSpace/ChadoIdSpace.php).`
Reference for postfix `\\\\` https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Database%21Query%21Condition.php/property/Condition%3A%3AconditionOperatorMap/8.9.x
Reference for escapeLike() https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Database%21Connection.php/function/Connection%3A%3AescapeLike/8.9.x

- [x] "Upload file" button on importer not working
  An error inside `tripal/js/TripalUploader.js` 
  This line `var func_name = ($.isFunction($.fn.live)) ? 'live' : 'on';`
  causes this error
2024-08-20_js-1
See commit https://github.com/tripal/tripal/pull/1953/commits/3ad8feb7897052fb5672f3bdf47331f6e54e5555 for a fix

- [x] Fix test ChadoVariablesAPITest::testChadoGenerateVariables

```
Drupal\Tests\tripal_chado\Functional\api\ChadoVariablesAPITest
  ❌ testChadoGenerateVariables 72923 ms
     ┐ 
     ├ The residues should be missing by default.
     ├ Failed asserting that true is false.
     │ 
     │ /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/api/ChadoVariablesAPITest.php:119
     ┴ 
```

- [x] Fix test GFF3ImporterTest::testGFFImporterSimpleTest

```
Drupal\Tests\tripal_chado\Functional\GFF3ImporterTest
  ❌ testGFFImporterSimpleTest 2910 ms
     ┐ 
     ├ This test printed output: 
     ├ Warning: Undefined array key "is_target" in /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/GFF3Importer.php on line 3216
     ├ 
     ├ Warning: Placeholders must begin with one of the following "@", ":" or "%", invalid placeholder (!landmark) with string: "Landmark/seqid !landmark contains invalid
     ├         characters. Only characters included in this regular expression are
     ├         allowed [a-zA-Z0-9.:^*$@!+_?-|]" in /var/www/drupal/web/core/lib/Drupal/Component/Render/FormattableMarkup.php on line 217
     │ 
     ┴ 
```

### CODE REVIEW

**Comment by dsenalik** [comment]
Field group table merge request https://www.drupal.org/project/field_group_table/issues/3430507#comment-15783226 was reviewed!

**Comment by dsenalik** [comment]
Creating a new branch today Sept 24 I see:

GitHub found 1 vulnerability on tripal/tripal's default branch (1 moderate). To find out more, visit:
https://github.com/tripal/tripal/security/dependabot/9

`core/authorize.php` in Drupal 11.x-dev allows Full Path Disclosure (even when error logging is None) if the value of `hash_salt` is `file_get_contents` of a file that does not exist.

*Update: `The alert you requested (#9) has been withdrawn and is no longer available. `

**Comment by laceysanderson** [comment]
We are still waiting on the field_group_table module despite the fact there is a patch to update it to D11 that has been "Reviewed by the community" for months now.

As such, the most recent commits allow building Tripaldocker on D11 but do not enable the tripal_layout module or attempt to download/enable the field_group_table module.

**Comment by laceysanderson** [comment]
Current failing tests:

#### ChadoVariablesAPITest::testChadoGenerateVariables

```
Drupal\Tests\tripal_chado\Functional\api\ChadoVariablesAPITest
  ❌ testChadoGenerateVariables 72923 ms
     ┐ 
     ├ The residues should be missing by default.
     ├ Failed asserting that true is false.
     │ 
     │ /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/api/ChadoVariablesAPITest.php:119
     ┴ 
```

#### GFF3ImporterTest::testGFFImporterSimpleTest

```
Drupal\Tests\tripal_chado\Functional\GFF3ImporterTest
  ❌ testGFFImporterSimpleTest 2910 ms
     ┐ 
     ├ This test printed output: 
     ├ Warning: Undefined array key "is_target" in /var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/GFF3Importer.php on line 3216
     ├ 
     ├ Warning: Placeholders must begin with one of the following "@", ":" or "%", invalid placeholder (!landmark) with string: "Landmark/seqid !landmark contains invalid
     ├         characters. Only characters included in this regular expression are
     ├         allowed [a-zA-Z0-9.:^*$@!+_?-|]" in /var/www/drupal/web/core/lib/Drupal/Component/Render/FormattableMarkup.php on line 217
     │ 
     ┴ 
```

Additionally there are a lot of deprecations. 🙈

**Comment by dsenalik** [comment]
@Lacey saw that the field group table merge request https://www.drupal.org/project/field_group_table/issues/3430507#comment-15783226 was merged!

**Comment by dsenalik** [comment]
The drupal 11 tests are failing, first with 
```
1) Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testExclusiveLockBasics
Failed asserting that exception of type "PHPUnit\Framework\Error\Warning" is thrown.
```
I tried to run this same test on a drupal 10 docker but I can't get the test to run, e.g.
`docker exec --workdir=/var/www/drupal9/web/modules/contrib/tripal $n phpunit --testdox --filter PersistentDatabaseSharedLockBackendTest`
`No tests executed!`

It looks like this change needs to be made to run on 10.x (have we NEVER been running these tests????)
in `phpunit.xml` add
```
    <testsuite name="tripal_biodb">
      <directory>tripal_biodb/tests</directory>
    </testsuite>
```

**Comment by laceysanderson** [comment]
> The drupal 11 tests are failing, first with
> ```
>     1. Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testExclusiveLockBasics
>        Failed asserting that exception of type "PHPUnit\Framework\Error\Warning" is thrown.
> 
> 
> ```
> I tried to run this same test on a drupal 10 docker but I can't get the test to run, e.g.
> `docker exec --workdir=/var/www/drupal9/web/modules/contrib/tripal $n phpunit --testdox --filter PersistentDatabaseSharedLockBackendTest`
> `No tests executed!`
> 
> It looks like this change needs to be made to run on 10.x (have we NEVER been running these tests????)
> in `phpunit.xml` add
> ```
> 
> ```
> <testsuite name="tripal_biodb">
>   <directory>tripal_biodb/tests</directory>
> </testsuite>
> ```

The test suite is updated for both Drupal 10 + 11 in this branch. Did you build the docker on this branch for Drupal 10.4.x and confirm that now it is being run? The dockerfile now copies the `tripaldocker/phpunit.9.6.xml` to override `phpunit.xml` when the Drupal version is less that 10.6. This gets overridden if you mount your directory though so you'll want to redo that copy as the xml schema has changed.

**Comment by dsenalik** [comment]
Okay that was on a different branch, and I see you have fixed the error in dbx already 😻

**Comment by dsenalik** [comment]
I reviewed "your" changes and only noted one thing, the removal of the prefix_length section left some code that didn't do anything now, so I simplified that and restored initializing `$tables = []` - so I did that in commit https://github.com/tripal/tripal/pull/1953/commits/820c68913aa0a2eca8e8545271a8ddf7bf25d0c0

One question, should we change the `^10.2` version requirements now to `^10.3` since that's what we claim to support? i.e. `core_version_requirement: ^10.2 || ^11.0` becomes `core_version_requirement: ^10.3 || ^11.0` in `tripal/tripal.info.yml` and elsewhere?

_Drupal 10.2 Security support ends in 3 weeks and 6 days (09 Dec 2024)_

**Comment by dsenalik** [comment]
I tried installing locally to see what's up
`/var/www/tripal4$ composer require drush/drush drupal/field_group drupal/field_group_table`
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drupal/field_group_table ^1.1 -> satisfiable by drupal/field_group_table[1.1.0].
    - drupal/field_group_table 1.1.0 requires drupal/core ^8 || ^9 || ^10 -> found drupal/core[8.0.0, ..., 8.9.20, 9.0.0, ..., 9.5.11, 10.0.0, ..., 10.3.8] but the package is fixed to 11.0.7 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require drush/drush:*" to figure out if any version is installable, or "composer require drush/drush:^2.1" if you know which you need.

**Comment by laceysanderson** [comment]
> I tried installing locally to see what's up `/var/www/tripal4$ composer require drush/drush drupal/field_group drupal/field_group_table` ... Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1 - Root composer.json requires drupal/field_group_table ^1.1 -> satisfiable by drupal/field_group_table[1.1.0]. - drupal/field_group_table 1.1.0 requires drupal/core ^8 || ^9 || ^10 -> found drupal/core[8.0.0, ..., 8.9.20, 9.0.0, ..., 9.5.11, 10.0.0, ..., 10.3.8] but the package is fixed to 11.0.7 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions. You can also try re-running composer require with an explicit version constraint, e.g. "composer require drush/drush:*" to figure out if any version is installable, or "composer require drush/drush:^2.1" if you know which you need.

This is caused by the Drupal docker change in this branch not being available on docker hub. Until this PR is merged, we can test this by using the manual workflow dispatch on this branch for the Drupal docker build. Unfortunately, that gets redone on 4.x each night so we have to redo it each day 🙈  I submitted the job just now here: https://github.com/tripal/tripal/actions/runs/11821254750. 
Screenshot 2024-11-13 at 10 12 54 AM

**Comment by dsenalik** [comment]
@laceysanderson there is still a bug, every drupal 10.x docker seems to be using the newer `phpunit.10.5.xml` instead of `phpunit.9.6.xml`
The test looks right `if $(dpkg --compare-versions "${drupalversion}" "lt" "10.6");` but even building locally it is getting the wrong version
```
 Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 20:
  - Element 'phpunit', attribute 'displayDetailsOnTestsThatTriggerErrors': The attribute 'displayDetailsOnTestsThatTriggerErrors' is not allowed.
  - Element 'phpunit', attribute 'displayDetailsOnTestsThatTriggerWarnings': The attribute 'displayDetailsOnTestsThatTriggerWarnings' is not allowed.
  - Element 'phpunit', attribute 'displayDetailsOnTestsThatTriggerDeprecations': The attribute 'displayDetailsOnTestsThatTriggerDeprecations' is not allowed.
  - Element 'phpunit', attribute 'cacheDirectory': The attribute 'cacheDirectory' is not allowed.

  Line 61:
  - Element 'bootstrap': This element is not expected. Expected is ( extension ).

  Line 103:
  - Element 'source': This element is not expected.

  Test results may not be as expected.
```

The correct file is there until the very end of the docker build process. I stuck a `ls` in right at the very end and the file is the correct 9.6 one (size 6161), but once the image is run it is the newer 10.5 version (size 6908)
```
  ...
  && service apache2 stop \
  && ls -l /var/www/drupal/web/modules/contrib/tripal/ \
  && service postgresql stop
```

Aha, it is because of the fact that we mount the tripal volume here in `ALL-phpunit.yml` (and similarly in my local build)
```
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal/web/modules/contrib/tripal \
            tripaldocker:localdocker
```

**Comment by dsenalik** [comment]
So I made commit https://github.com/tripal/tripal/pull/1953/commits/2d0e0724d365188deb3f257450a131b01a86a0ff which adds a small helper bash script to determine which is the correct `phpunit.xml` file to use based on the Drupal version. Then commit https://github.com/tripal/tripal/pull/1953/commits/1900541fe055806164df8f1897979084928f2d15 uses this helper script when running the unit tests.

This still does not apply if a developer runs unit tests locally on 10.x, they will have to copy the correct file or add the `--configuration` parameter

The other approach I considered was adding code to the `init.sh` script to copy the appropriate phpunit.xml version based on the drupal version. This worked, but I disliked the fact that it modified your mounted tripal repo. The advantage is that this approach should work for both github tests and local tests.
Note that neither method would be automatic for a 10.x traditional install.

**Comment by dsenalik** [comment]
So that I have a record of the deprecations fixed in commit https://github.com/tripal/tripal/pull/1953/commits/42499275f0264806f1ecf09f211ddfaa208bf837
```
  140x: \Drupal\Core\Database\Driver\pgsql\Connection is deprecated in drupal:9.4.0 and is removed from drupal:11.0.0. The PostgreSQL database driver has been moved to the pgsql module. See https://www.drupal.org/node/3129492
    12x in BasicDataTypeChadoFieldTest::testCreateViaCombinedAddFieldForm from Drupal\Tests\tripal_chado\Functional\Plugin\Fields\CreateEditFieldForms
    5x in ChadoInstallerTest::testPerformTaskInstallerParameters from Drupal\Tests\tripal_chado\Kernel\Task
    3x in ChadoStorageLinkerFieldTest::testLinkerTableField from Drupal\Tests\tripal_chado\Kernel\Plugin\ChadoStorage
    2x in NewickImporterTest::testNewickImporterSimpleTest from Drupal\Tests\tripal_chado\Functional
    2x in ChadoStorageActions_StorePkeyTest::testStorePKeyAction from Drupal\Tests\tripal_chado\Kernel\Plugin\ChadoStorage
    ...

  8x: Installing the table sequences with the method KernelTestBase::installSchema() is deprecated in drupal:10.2.0 and is removed from drupal:12.0.0. See https://www.drupal.org/node/3349345
    4x in TripalFieldTypeCRUDTest::testCreateEntityWithField from Drupal\Tests\tripal\Kernel\TripalField
    4x in TripalFieldTypeSettingsTest::testStorageSettingsFormBuild from Drupal\Tests\tripal\Kernel\TripalField

  1x: \Drupal\Core\Database\Driver\mysql\Connection is deprecated in drupal:9.4.0 and is removed from drupal:11.0.0. The MySQL database driver has been moved to the mysql module. See https://www.drupal.org/node/3129492
    1x in ConnectionTest::testConnectionConstructorTestSchemaInvalidDatabase from Drupal\Tests\tripal\Kernel\TripalDBX
```

**Review by laceysanderson — COMMENTED** [review]
@dsenalik I looked through all your changes and it looks good to me 👍 

Note: regarding the phpunit.xml situation: I'll see if I can configure our devcontainer setup to use your script to set the right phpunit.xml

For next steps on this issue. Do we want to do a good testing through the UI each and then call it good? We can fix additional deprecation in another issue/PR and that way all these goodies make it into 4.x sooner and we don't add anymore to the 57 files changed count 🙈

**Comment by dsenalik** [comment]
I was wondering why testing takes twice as long on 11.x.
On 11.x we run **479** unit tests.
```
...........................I...................................  63 / 479 ( 13%)
............................................................... 126 / 479 ( 26%)
.......................III..................I...............III 189 / 479 ( 39%)
I.............................................................. 252 / 479 ( 52%)
...I............................III..................I......... 315 / 479 ( 65%)
......IIII................I.................................... 378 / 479 ( 78%)
............................................................... 441 / 479 ( 92%)
...............................I......                          479 / 479 (100%)

Time: 01:04:34.170, Memory: 199.41 MB

OK, but there were issues!
Tests: 479, Assertions: 34636, Incomplete: 20.
```

On 10.x only **262** tests are run
```
Testing 
...........................I...................................  63 / 262 ( 24%)
............................................................... 126 / 262 ( 48%)
.......................III..................I...............III 189 / 262 ( 72%)
I.............................................................. 252 / 262 ( 96%)
...I......                                                      262 / 262 (100%)

Time: 30:52.946, Memory: 42.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 262, Assertions: 17395, Incomplete: 10.
```
I am running some tests locally with `--testdox` to see exactly which tests are being run, what is test 262 and 263???

Last test run on 10.4
 ✔ List builder with data set "basic_form"

Duh, I can just use `--list-tests`
```
    3 Available test(s):
    4  - Drupal\Tests\tripal\Functional\Entity\EntityAccessTest::testTripalAccessOwnContentCheck
    5  - Drupal\Tests\tripal\Functional\Entity\EntityAccessTest::testTripalEntityAccessControlHandler
...
    263  - Drupal\Tests\tripal_layout\Kernel\Entity\TripalLayoutEntityFormTest::testDeleteForm"basic_form"
    264  - Drupal\Tests\tripal_layout\Kernel\Entity\TripalLayoutEntityListTest::testListBuilder"basic_view"
    265  - Drupal\Tests\tripal_layout\Kernel\Entity\TripalLayoutEntityListTest::testListBuilder"basic_form"
Drupal 10.x ends here ^, Drupal 11.x continues
    266  - Drupal\Tests\tripal\Functional\Entity\EntityAccessTest::testTripalAccessOwnContentCheck
    267  - Drupal\Tests\tripal\Functional\Entity\EntityAccessTest::testTripalEntityAccessControlHandler
...
    481  - Drupal\Tests\tripal_layout\Kernel\Entity\TripalLayoutEntityListTest::testListBuilder"basic_view"
    482  - Drupal\Tests\tripal_layout\Kernel\Entity\TripalLayoutEntityListTest::testListBuilder"basic_form"
...
```
so it is looking like most tests are being run twice (better than not at all?)

**Comment by dsenalik** [comment]
I built both drupal 10.5 and 11.1 dockers and went through some common steps:
Create organism, contact, & analysis through UI
Import gff and ncbi taxonomy and run both jobs together
Import all type collections and publish gene and mRNA
For gene detect new fields and add them
Edit gene and add sequence residues and save

No new issues with anything

\* Update, I am doing a more thorough test, a Tripal 3 migration into a Drupal 11.1 site. Some issues (#2033), but nothing related to this PR.

**Comment by dsenalik** [comment]
I remembered that the duplicated test count was not exactly double. It turns out that we are not running the following tests on 11.x
```
$ diff <(sort /tmp/104tests) <(sort /tmp/111tests)
5,19d4
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testAcquireSharedDetails
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testAcquireSharedExistingExclusiveLock
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testAcquireSharedExistingMainLock
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testAcquireSharedExtendTimeout
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testAcquireSharedNoMainLock
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testAcquireSharedWithoutState
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testAcquireWithoutState
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testExclusiveLockBasics
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testGetCurrentExpirationDelay
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testNoReleaseOnShared
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testNoReleaseOther
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testNoReleaseSharedOnExclusive
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testNotAcquireWhenShared
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testReleaseAllOwn
<  - Drupal\Tests\tripal_biodb\Unit\Lock\PersistentDatabaseSharedLockBackendTest::testSharedLockBasics
235,265c220
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testGetDrupalSchemaNameDefault
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testGetDrupalSchemaNameFailure
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testGetDrupalSchemaNameOtherAndCache
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#0
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#1
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#10
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#11
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#12
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#13
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#14
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#15
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#16
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#17
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#18
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#19
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#2
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#20
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#21
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#22
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#3
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#4
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#5
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#6
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#7
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#8
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testIsInvalidSchemaName#9
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testParseTableDdl
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testReservedSchemaPattern
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testSchemaExistsInvalid
<  - Drupal\Tests\tripal\Unit\TripalDBX\TripalDbxUnitTest::testSchemaExistsValid
< PHPUnit 9.6.21 by Sebastian Bergmann and contributors.
---
> PHPUnit 10.5.38 by Sebastian Bergmann and contributors.
```

**Review by laceysanderson — APPROVED** [review]
Manual check:

- Created/Edited Tripal Content: organism, project, contact including relationships + properties
- Tested publishing
- Importing content type collections/fields
- editing custom tables
- viewing manage chado form
- OBO data importer

All of it looks good to me!
Once we can get the test coverage to pass I think this is ready to merge.

**Pull request merged**
