### PR TITLE
Install and configure gin admin theme.

### LINKED ISSUE #2004: Content Editing Usability improvements + Admin Theme
#### Content Editing Usability improvements

The create/edit content forms drive me crazy. They feel very unpolished and inconsistent. 

Specifically, for this issue, I would like to resolve the difference in display for single-value form fields versus multi-value form elements. You can see in the following screenshot that the "Title", "Algorithm" and "Description" form element labels are VERY different from the "Database Reference Annotations" form element label.
image

This is very jarring to me and makes it hard to fill these forms out. It also just feels messy.

#### Admin Theme

My first thought with this was: maybe it's just that the default admin theme is really bad. As such, I did a bunch of searching for alternatives but it turns out there is really only one contender: https://www.drupal.org/project/gin and it doesn't fix the content editing issue I mentioned above.

Screenshot 2024-10-17 at 2 33 58 PM

This admin theme also would relieve another huge usability concern for me: lack of dark theme for the default admin theme.

It is a radically different toolbar though... but there is a lot of configuration for this theme which does include a legacy toolbar option:
image

### Proposed Changes

1. I would like to update TripalDocker to use the Gin admin theme + Toolbar. I would set the defaults to
   - Appearance: Auto (shows light or dark based on your OS/browser settings)
   - Accent color: Yellow
   - Focus color: Neutral
   - Navigation: New Drupal Navigation, Test Integration
   - Show Secondary Toolbar in Frontend: Yes
   - Layout density: Narrow
   - Users can override Gin settings: Yes
2. Add a theme alter hook to the core Tripal module that forces single + multivalue labels to be displayed consistently. This might be seen as a bit of an overstep for an extension module but the Tripal community cannot maintain a full theme and I cannot see a better solution.
3. Add configuration to allow sites to turn off the functionality in change 2 above.

### Branch Name

tv4g0-issue2004-dockerThemeUpdates

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task 

## Description

Refer to the issue for justification and background. 

This PR aims to:

- [x] I would like to update TripalDocker to use the Gin admin theme + Toolbar. I would set the defaults to
   - Appearance: Auto (shows light or dark based on your OS/browser settings)
   - Accent color: Neutral
   - Focus color: Neutral
   - Navigation: New Drupal Navigation, Test Integration
   - Show Secondary Toolbar in Frontend: Yes
   - Layout density: Narrow
   - Users can override Gin settings: Yes
- [x] Update the Tripal Content Type listing to be polished in both light/dark and gin/claro
- [x] Update the Add Tripal Content listing to match other administrative listings
- [x] Update the Add Tripal Content listing to match colour coding in the Tripal Content Type listing
- [x] Add css to Tripal Content forms that forces single + multivalue labels to be displayed consistently. This might be seen as a bit of an overstep for an extension module but the Tripal community cannot maintain a full theme and I cannot see a better solution.
- [x] Add css to the database references widget so it takes up less space
- [x] Fix Tripal icon in toolbar

## Testing?

1. Create a new DRUPAL docker build on this branch
```
docker build --tag=tripalproject/tripaldocker-drupal:drupal10.4.x-dev-php8.3-pgsql16 --file=tripaldocker/drupal.Dockerfile ./
```
2. Create a new TRIPAL docker build that uses the drupal one. If you passed in build-args to the command in step 1 then make sure you pass in the same ones here.
```
docker build --tag=tripalproject/tripaldocker:drupal10.4.x-dev-php8.3-pgsql16 ./
```
3. Create a container
```
docker run --publish=80:80 -tid --name=admintheme tripalproject/tripaldocker:drupal10.4.x-dev-php8.3-pgsql16
```
4. Now go to localhost, log in and confirm that you see the new expanded toolbar.

| GIN Light | GIN Dark |
|---|---|
| home-light | home-dark |

5. Then go to the admin pages and confirm you see the new theme there. Explore and let me know what you think.

| GIN Light | GIN Dark |
|---|---|
| admin-light | admin-dark |

6. Go to the Tripal Content Types listing and confirm it looks good/readable on your monitor.

| GIN Light | GIN Dark |
|---|---|
| types-light | types-dark | 

7. Go to the Add Tripal Content page and confirm it looks good/readable on your monitor.

| GIN Light | GIN Dark |
|---|---|
| add-light | add-dark |

8. Go to the Add Analysis page and confirm that the form looks consistent (i.e. there is no large coloured header for multi-value fields) and that the dbxref field is all on one line now.

| GIN Light | GIN Dark |
|---|---|
| analysis-light | analysis-dark |

**NOTE: This will not work through VSCode until this PR is merged since devcontainers pulls the drupal images pre-built rather then building them at that time off the existing branch.**

## Original / 4.x

This section provides screenshots for the above steps as the show up in Claro on 4.x and now. Note: to see Claro now, you go to admin > themes and select claro under the "Admin Theme".

### Core pages with no change in Claro

| Home | Admin |
|---|---|
| home-claro | admin-claro |

### Tripal Content Type listing

| 4.x | Claro Now |
|---|---|
| types-4x | types-now |

### Add Tripal Content listing

| 4.x | Claro Now |
|---|---|
| add-4x | add-claro |

### Add Analysis page

| 4.x | Claro Now |
|---|---|
| analysis-4x | analysis-claro |

### CODE REVIEW

**Comment by dsenalik** [comment]
I do not dislike this new theme. And I only say it that way because change is always difficult, I get used to things 😼.

**Review by dsenalik — APPROVED** [review]
Everything is showing up for me as you described - I also played with light vs. dark theme. Given some time to adapt I think I would like this theme better 😁

**Comment by Ferrisx4** [comment]
I tested this out and am really digging the new theme. Everything just feels a bit nicer and the color-coding for the Tripal content types is a nice touch and the chosen colors work well in both the light and dark themes. Being able to change the accent color and other elements is nice but the defaults are satisfactory.
I'm on board and will probably use this theme in other places. 

Edit: I'll run through some of our accessibility tests and report back.

**Comment by Ferrisx4** [comment]
# Accessibility update
Tool used - [WAVE (Web Accessibility Evaluation Tool)](https://wave.webaim.org/extension/)

# Summary
Most of the pages perform well against the WAVE tool. There were a few errors here and there that were either not part of the new theme or part of Tripal that were being triggered, but fall out of the scope of this PR.

The most common issue is text contrast and some empty table headers, (see below).

# Contrast
On the "Add Tripal Content" page (/bio_data/add), low contrast alerts were triggered for various category font colors in both dark and light themes.

Content Type Category | Light Theme | Dark Theme |
|---------------------|-------------|------------|
| General   | Low Contrast | OK |
| Germplasm | OK | Low Contrast |
| Genomic   | OK | Low Contrast |
| Genetic   | OK | Low Contrast |
| Expression | Low Contrast | OK |

Using the [Contrast Finder](https://app.contrast-finder.org/result.html?foreground=rgb%2858%2C+136%2C+89%29&background=%231F2022&ratio=4.5&isBackgroundTested=false&algo=Rgb&lang=en) tool, I am currently looking for alternatives that are similar to the originals, however some were a little farther away because they had to satisfy both light and dark theme. In `tripal/css/tripal_entity_type.variables.css`, there are color codes for both light and dark:`

```css
  --tripalcontent-category1-solid: #5C8925;
  --tripalcontent-category1-solid-dark: #80AC49;
  ```
however the dark one is never utilized, regardless of the chosen light/dark theme.

Content Type Category | CSS | Light Theme | Dark Theme |
|---------------------|-----|-------------|------------|
| General    | --tripalcontent-category1-solid | | |
| Germplasm  | --tripalcontent-category2-solid | | |
| Genomic    | --tripalcontent-category3-solid | | |
| Genetic    | --tripalcontent-category4-solid | | |
| Expression | --tripalcontent-category5-solid | | |

 *I am still working on this*

 # Empty Table Header
 On the "Add Analysis" page, and other pages with this particular field type, certain fields have empty headers, as seen in the screenshot. I'm not sure that we have control over this, but the recommendation for empty table cells is to use `<td>` and not `<th>`, even if it is a header.
empty table header

**Comment by laceysanderson** [comment]
Thanks for the detailed accessibility check @Ferrisx4!

## Empty Table Header

Yes, this is Drupal's decision and not easily changed by us unfortunately. Perhaps a search of the Drupal issue queue would be worth it to see if they are aware of this?

## Contrast

> The most common issue is text contrast and some empty table headers, (see below).

I wondered about this 🙈 

> In tripal/css/tripal_entity_type.variables.css, there are color codes for both light and dark:
>
> ```
>  --tripalcontent-category1-solid: #5C8925;
>  --tripalcontent-category1-solid-dark: #80AC49;
>```
>
> however the dark one is never utilized, regardless of the chosen light/dark theme.

I checked and the "Add Tripal Content" page should be using both light and dark colours for gin based on these rules:

```
#tripal-entity-add-content #category-General .admin-item .admin-item__title {
  color: var(--tripalcontent-category1-solid);
}
html.gin--dark-mode #tripal-entity-add-content #category-General .admin-item .admin-item__title {
  color: var(--tripalcontent-category1-solid-dark);
}
```
https://github.com/tripal/tripal/pull/2005/files#diff-e2f85fb4009ff5dadf0f1c9efdad4ab46ea84016125c892df277facb4d8fbddaR12-R17

Is that not what you are seeing in your docker?

Another potential place to look is that currently the colour for the overlay is the same on both and dark but could be computed to use the light and dark colour codes to increase contrast.

**Comment by laceysanderson** [comment]
Marking this back as draft while I fix the contrast issues with the Germplasm, Genomic and Genetic categories and also fix the missing Tripal icon.

**Comment by laceysanderson** [comment]
I have fixed the contrast of the colours for both the light and dark version of gin to pass the accessibility standards of the WAVE extension and confirmed there are no additional accessibility issues related to the changes in this PR.
image
image

I also made the fix to the tripal icon not appearing in the gin menu.
Screenshot 2024-11-01 at 1 21 35 PM
Screenshot 2024-11-01 at 1 22 08 PM

To my knowledge this is now ready for a super quick double check :-)

**Comment by dsenalik** [comment]
I built a new docker and went through some of the various screens, all looks good to me at this point. 
The tripal icon is back, so I checked your box 😁

**Pull request merged**
