### PR TITLE
Property Field supports multiple property types on the same page

### LINKED ISSUE #1398: Tripal 4 property field can't handle two properties at the same time
### System information

* Tripal Version: tv4α docker container

### Issue description
I'm trying to understand fields, but playing with an existing field is not behaving like I would expect. One property is leaking over into another.

#### Steps to reproduce
1. Create a project to play with
2. Go to ```/admin/structure/bio_data``` and for Project select "Manage Fields"
3. +Add Field
4. Select field type "Chado Property" and label it "Library", "Save and continue"
5. Base table select project
6. Number of values set to Unlimited, "Save field settings"
7. Controlled Vocabulary Term select ```Library (local:library)```, "save settings"
8. Repeat steps 2 through 7, this time use a DIFFERENT cv term, I used "Book" CV term ```Book (TPUB:0000004)```
9. Go to the entity page for the project, and click "Edit"
10. Under "Library" enter "National Ag Library", and Save
11. Now click "Edit" again
12. Under "Book" enter "Harry Potter and the Tripal Daemon", and hit save
13. This is the result. The second property did not save into chado.
tv4
14. Edit again and add a second "Book"
tv4-2

15. Edit again, fix the Book names, and add a second "Library", and save
tv4-3
```
sitedb=> select * from projectprop;
 projectprop_id | project_id | type_id |        value        | rank 
----------------+------------+---------+---------------------+------
              4 |          2 |    2938 | Harry Potter 2      |    1
              5 |          2 |     113 | National Ag Library |    0
              6 |          2 |     113 | Library of Congress |    1
(3 rows)
```

### PR DESCRIPTION
**Pull request by laceysanderson**
# Bug Fix

## Description

Previously when there were two property fields on the same page, they would swap data. This is a huge bug as there will almost always be multiple property fields on the same page as each one represents a type of metadata!

This was happening because ChadoStorage was keeping track of chado records to be managed by chado table and not taking into account that we don't always want to merge all fields working on a single table into a single record! It was a hard bug to solve as the assumption went really deep in the chado storage class and we did need to support both cases: 

1. Multiple fields work together to describe a single chado record (e.g. organism genus, species, infraspecific type and infraspecific name fields all work together to describe a single organism record).
2. Multiple fields access the same table but do not want to have their values combined into a single record (e.g. two property fields where each one has all the information for a single record in the organismprop table).

## Solution

Allow fields to define table alias'. 
By default, the table alias is the same as the table name which makes this fix backwards compatible and ensures case A above still works.
Fields who want to keep their records separate can now indicate a table alias on a per StoragePropertyType basis.

Only data from StoragePropertyTypes referencing the same table alias will combine data to form a single chado record. 

## Additional Fixes

While adding automated testing around the ChadoStorage actions to ensure this works as designed and that no actions were broken by these changes, I also fixed the following smaller bugs:

 - Throws an error if store_id actions are used on a non-base table.
 - Throws an error if developers try to use table alias' with the store_id action since base tables do not support alias'
 - Read_value (join) actions were only working if there were other fields on the base table. This assumption has been removed.
 - Ensure that the read_value table alias' was handled differently for joins and base tables as it needed to be.

## Testing?

All the existing automated testing still passes showing this change is 100% backwards compatible.

I also added full automated testing of the various actions to ensure this addition of table alias' didn't break any of the actions and weed out incorrect assumptions that may have been made.

### Manually test content types in general

Manually test each of the content types ensuring that the default fields still work as expected. For example, create an organism without adding any new fields and ensure that the page saves and updates the data for each form element.

### Test the property field

1. Choose a content type supporting properties (e.g. Organism, Gene, Germplasm Accession, etc)
2. Navigate to Tripal > Page Structure > CONTENT TYPE > Manage Fields.
3. Add multiple chado property fields by repeating the following steps at least twice with different terms each time.
    a. Click on "Create new field"
    b. Select "Chado Property" under "Add a new field"
    c. Then enter a label (e.g. TestProp1) and click "Save and continue"
    d. Next choose the chado base table (e.g. if your using the gene content type then choose feature) and change the "Allowed number of values" to "unlimited". Then click "Save field settings"
    e. Finally set the term by scrolling to the bottom of the next form and entering something in the "Set the Term" form element. Examples include "Kingdom", "Phylum", "comment", "Subgroup". Really choose anything you like here. It just needs to be different for each property field.
4. Once you have multiple property fields added to the same content type, then go ahead and create content for that content type! (i.e. Admin > Tripal > Content > Add Tripal Content > CONTENT TYPE). Make sure to test multiple combinations of filling in fields, changing them, deleting them, etc and ensure the resulting page reflects those changes/values. Specifically, ensure that a value entered for one property fields is always associated with that field and never any of the others!

The following screenshots are showing one of my manual tests on the genetic marker content type with three properties (TestProp1, TestProp2 and TestPropSingle) where the last one is set to limited values and the first two are unlimited.
 - [Genetic Marker Insert Form](https://github.com/tripal/tripal/assets/1566301/09b637a2-24ec-4e81-8747-a67fb497a934)
 - [Page after submitting above form](https://github.com/tripal/tripal/assets/1566301/84b8dd8e-8348-4114-9fb1-ac3616b11d97)
 - [Update form with changes](https://github.com/tripal/tripal/assets/1566301/fc0da423-1b3d-4ee2-890c-bb6e7398d761)
 - [Page after submitting the updates](https://github.com/tripal/tripal/assets/1566301/bcaa1d01-0534-4227-a384-db39ee197a2b)

### CODE REVIEW

**Review by dsenalik — CHANGES_REQUESTED** [review]
Manual testing on the content type "Germplasm Variety" with Drupal 10.1, PHP 8.2

1. While creating the first property, base table "stock", I see this warning
`Warning: Undefined array key "version" in Drupal\tripal_chado\Database\ChadoSchema->getSchemaDef() (line 23 of modules/contrib/tripal/tripal_chado/src/Database/ChadoSchema.php). `
I have a fix for `tripal_chado/src/Database/ChadoSchema.php` in PR #1431 that can be included here too
https://github.com/tripal/tripal/pull/1431/files#diff-050d077829bb18bdea3555b57fd394984ce685802f2741678e93958af1874637

2. However, even with that fixed (it was just a warning), I cannot add the first property, I see this
`Status message
Attempt to update field Property_One failed: Cannot create a StorageProperty object without a properly formatted term: .`

Now, this is working okay for organism (base table "organism"), so something is wrong somewhere...

Very curious, if I select the wrong base table (I used "assay" instead of the correct "stock") then I can continue to the next step and even save the field.

I will post this much, and update if I figure out more.

**First update**
In `tripal_chado/src/Plugin/Field/FieldType/ChadoLinkerPropertyDefault.php`
For the stock table content types, these variables have these values:
`$prop_table` = `stockprop`
`$prop_fk_col` = `stock_id`
but this line returns null:
`$link_term = $mapping->getColumnTermId($prop_table, $prop_fk_col);`

Code to paste into the devel module php window to reproduce
```
$chado = \Drupal::service('tripal_chado.database');
$schema = $chado->schema();

$storage = \Drupal::entityTypeManager()->getStorage('chado_term_mapping');
$mapping = $storage->load('core_mapping');

$base_table = "stock";
$prop_table = "stockprop";
$prop_schema_def = $schema->getTableDef($prop_table, ['format' => 'Drupal']);
$prop_fk_col = array_keys($prop_schema_def['foreign keys'][$base_table]['columns'])[0];
var_dump($prop_fk_col);  // prints string(8) "stock_id"

$link_term = $mapping->getColumnTermId($prop_table, $prop_fk_col);
var_dump($link_term);  // prints string(0) ""
```

**Second update**
These are the content types that are missing terms for foreign keys in `tripal_chado/config/install/tripal_chado.chado_term_mapping.core_mapping.yml `. In addition to stock, arraydesign is missing the definitions.

| Label  | Machine name  | Term | ForeignKeyHasTermDefined? |
| --- | --- | --- | --- |
| Analysis  | analysis  | Analysis (operation:2945) | okay analysisprop analysis_id |
| Contact  | contact  | contact (local:contact) | okay contactprop contact_id |
| Organism  | organism  | organism (OBI:0100026) | okay organismprop organism_id |
| Project  | project  | Project (NCIT:C47885) | okay projectprop project_id |
| Protocol  | protocol  | protocol (sep:00101) | okay nd_protocolprop protocol_id |
| Publication  | pub  | Publication (TPUB:0000002) | okay pubprop pub_id |
| Study  | study  | study (SIO:001066) | okay studyprop study_id |
| Breeding Cross  | breeding_cross  | generated germplasm (CO_010:0000255) | MISSING stockprop stock_id |
| Germplasm Accession  | germplasm  | accession (CO_010:0000044) | MISSING stockprop stock_id |
| Germplasm Variety  | germplasm_variety  | cultivar (CO_010:0000029) | MISSING stockprop stock_id |
| Recombinant Inbred Line  | RIL  | 414 inbred line (CO_010:0000162) | MISSING stockprop stock_id |
| DNA Library  | dna_library  | DNA Library (NCIT:C16223) | okay libraryprop library_id |
| Gene  | gene  | gene (SO:0000704) | okay featureprop feature_id |
| Genome Annotation  | genome_annotation  | Genome annotation (operation:0362) | okay analysisprop analysis_id |
| Genome Assembly  | genome_assembly  | genome assembly (operation:0525) | okay analysisprop analysis_id |
| Genome Project  | genome_project  | Genome Project (local:Genome Project) | okay analysisprop analysis_id |
| mRNA  | mRNA  | mRNA (SO:0000234) | okay featureprop feature_id |
| Phylogenetic Tree  | phylotree  | Phylogenetic tree (data:0872) | okay phylotreeprop phylotree_id |
| Physical Map  | physical_map  | Physical map (data:1280) | okay featuremapprop featuremap_id |
| Genetic Map  | genetic_map  | Genetic map (data:1278) | okay featuremapprop featuremap_id |
| Genetic Marker  | genetic_marker  | genetic_marker (SO:0001645) | okay featureprop feature_id |
| Heritable Phenotypic Marker  | phenotypic_marker  | heritable_phenotypic_marker (SO:0001500) | okay featureprop feature_id |
| QTL  | QTL  | QTL (SO:0000771) | okay featureprop feature_id |
| Sequence Variant  | sequence_variant  | sequence_variant (SO:0001060) | okay featureprop feature_id |
| Array Design  | array_design  | array design (EFO:0000269) | MISSING arraydesignprop arraydesign_id |
| Assay  | assay  | assay (OBI:0000070) | okay assayprop assay_id |
| Biological Sample  | biosample  | biological sample (sep:00195) | okay biomaterialprop biomaterial_id |

**Comment by laceysanderson** [comment]
Thank you @dsenalik! Nice to hear from you! I've added in a term for stock and arraydesign and checked and now adding properties to stock-based content types works!

**Review by dsenalik — APPROVED** [review]

**Comment by dsenalik** [comment]
Testing on the Array Design content type works perfectly, but I found a bug in another field on that content type (not affecting this PR) = #1669

**Comment by laceysanderson** [comment]
Thanks for the careful testing and review @dsenalik! And welcome back ❤️ I'm going to merge this PR 🎉 and I'll take a look at the other issue today.

**Pull request merged**
