### PR TITLE
Better Debugging of ChadoStorage for Field Development

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task

Issue #1594 

## Description

As we have been developing more fields, it's becomming apparent that ChadoStorage is too much of a black box at this point. For example, in cases where you've defined the properties as expected based on documentation but they still don't work --you just don't get your data... There is no way for you to see the queries created by chadostorage, get an idea of how chadostorage is processing your properties, etc. This basically means there is no way to debug your properties without adding debugging statements into chado storage yourself.

This PR adds a checkbox to the field settings form to enable debugging information for a field. This allows developers who are working on fields to target a specific field instance (i.e. their field attached to a specific content type with a specific set of settings) and receive the following debugging information to give them insight into how chado storage is interpreting the properties they gave them. This will help with detecting bugs both in fields being developed and in chadostorage itself!

Debugging information made available:

- The status of chado storage at the beginning of the process including the following information for each attached field instance:
  - field name, type and definition
  - field settings
  - the number of properties
  - an array with the following information for each property type:
    - the class name with namespace
    - the term attached
    - the storage settings set in the field
- The property values at the beginning of the process
- An array describing the records to be created. This is the result of buildChadoRecords and is used directly by chadostorage not generated for debugging. This is aggregated across all fields.
- The primary key values of the so-called base records as understood by chado storage. This is aggregated across all fields.
- The actual queries being executed by chado storage. There will be the record key and delta in the label. Unfortunately the placeholder values are not included due to Drupal bugs documented in the code.
- The values after the process is complete. These will be the values made available to the widget and formatter classes.

screenshot

## Notes

- This debugging information is posted for load, insert, update, validate (+ delete/find once implemented)... 
  - Inserting results in both a load and insert
  - update though is particularly long with multiple loads and the update. This is how Drupal works for some reason 🤷‍♀️ 
  - there can be a lot of information which could be overwhelming
- Since multiple fields make up a single chado record, if you enable debugging for a single field you actually see information for all fields on that content type. I felt this was needed to truely debug
- The content listing page might time out if there are too many entries with debugging turned on as that triggers a full load for every entity on the page.
- The field debugger uses dpm so devel is required to use it 🤷‍♂️ we can't use html in drupal_set_message and I felt formatting was necessary for this to be usable at all.

## Testing?

1. Create a docker image and container on this branch. [See these instructions for how to do that.](https://tripaldoc.readthedocs.io/en/latest/contributing/docker-for-testing.html#testing-an-unmerged-pull-request)
2. Choose a content type and field to debug (e.g. gene, organism field)
3. Go to Tripal > Page Structure > Gene > Manage Fields
4. Click on edit beside the field you want to debug
5. Select the "Enable debugging" checkbox and save the field settings
6. Create a gene page by going to Tripal > Content > Add Tripal Content > Gene and filling out the form
7. When you click save you would expect to see debugging information.
8. You can then refresh the page and confirm you see debugging information for the load.
9. Then edit the page and confirm you see debugging information for the load multiple times and the update.

### CODE REVIEW

**Comment by pdtouch** [comment]
This works as described perfectly well. It is very very helpful in a way that makes development and debugging of Tripal fields much easier. It exposes the underlying web Drupal/Tripal GUI elements, databases, tables, columns and values involved in the field before and after entering content through the GUI which have pretty much been black boxes, making debugging very very difficult.

Tested 3 modified fields simultaneously using the Debug Field(s) option : 
Sequence Residues, Sequence Length and Sequence Checksum for a new Gene content.

```
Debugging has been enabled for field_sequence_checksum field.
Debugging has been enabled for field_sequence_length field.
Debugging has been enabled for field_sequence_residues field.
``` 

The field variables, arrays including the database/storage operations are visible in the Debug area for all the 3 fields helping better in the debugging process. 

Thank you very much @laceysanderson !

**Comment by dsenalik** [comment]
Some debug output is "leaking through" without debugging activated, _e.g._ going to `/admin/content/bio_data` (I have an organism and two genes)


and debugging is not yet turned on


Or adding a new gene


Ah, the `printHeader()` function doesn't check whether it should print or not, can we just add this?
```
  if ($this->has_fields2debug === FALSE) {
     return;
   }
```

**Review by dsenalik — APPROVED** [review]
This is beautiful 🥰
Code looks good and debugging output will be super duper helpful for field development.

My only suggestion is to make the variable name|array key `debug` a bit more descriptive, how about `field_debug` to correspond to the `field_debugger` naming? That way it is more clear in the code what it is for. Just a thought

**Comment by spficklin** [comment]
Thnks @dsenalik and @pdtouch for the reviews!

**Pull request merged**
