### PR TITLE
Request for gold badge status for tripal galaxy module

### PR DESCRIPTION
**Pull request by shawnawsu**
# Documentation

Issue N/A

## Description

This is a pull request submission for a gold badge for the Tripal Galaxy module. [Here is the repository](https://github.com/tripal/tripal_galaxy).

I've copied the checkbox list from Bradford's ticket requesting the badge certification. But used the suggested style from Stephen.

## Bronze
| Requirement           | Status |
|------------------- |---------------------|
| Has a public release. | <ul><li>[x] Yes </li></ul>|
| Should install on a Tripal site appropriate for the versions it supports. |  <ul><li> [x] Yes </li></ul>|
| Defines any custom tables or materialized views in the install file (if applicable). |  <ul><li>[x] Yes </li><li>[ ] Not Applicable</li> </ul>|
| Adds any needed controlled vocabulary terms in the install file (Tripal3). |  <ul><li>[ ] Yes </li><li>[x] Not Applicable</li> </ul>|
| Provides Installation and admin instructions README.md (or RTD). |  <ul><li>[x] Yes </li></ul>|
| Has a license (distributed with module). |  <ul><li>[x] Yes </li></ul>|

## Silver
| Requirement           | Status |
|------------------- |---------------------|
| Follows basic Drupal Coding standards; specifically, code format and API documentation. | <ul><li>[x] Yes </li></ul>|
| Uses Tripal API functions. Specifically, it should use the Chado Query API for querying chado (if using chado as the storage system). |  <ul><li>[ ] Yes </li><li>[x] Not Applicable</li> </ul>|
| Tripal Jobs API for long running processes. | <ul><li>[x] Yes </li><li>[ ] Not Applicable</li> </ul>|
| TripalField class to add data to pages (Tripal3). |  <ul><li>[ ] Yes </li><li>[x] Not Applicable</li> </ul>|
| Provides ways to customize the module (e.g. drush options, field/formatter settings, admin UI). |  <ul><li>[x] Yes </li></ul>|
| Latest releases should follow Drupal naming best practices. e.g. first release for Drupal 7 should be: 7.x-1.x. |  <ul><li>[x] Yes </li></ul>|

## Gold
| Requirement  | Status |
|-------------|---------|
| Extensive documentation for the module (similar to Tripal User’s Guide). | <ul><li>[x] Yes </li></ul>|
| Unit testing is implemented using PHPUnit with the TripalTestSuite or something similar. |  <ul><li>[x] Yes </li> </ul>|
| Continuous integration is setup (e.g. such as with TravisCI). | <ul><li>[x] Yes </li></ul>|
| Imports data via Tripal’s importer class (Tripal3). |  <ul><li>[ ] Yes </li><li>[x] Not Applicable</li> </ul>|
| Tripal 3 fields are Fully compatible with web services. | <ul><li>[ ] Yes </li><li>[x] Not Applicable</li> </ul>|
| The elementInfo function is fully implemented. | <ul><li>[ ] Yes </li><li>[x] Not Applicable</li> </ul>|
| The query and queryOrder functions fully implemented. | <ul><li>[ ] Yes </li><li>[x] Not Applicable</li> </ul>|
| Web Services uses Tripal’s Web Service Classes (Tripal3). | <ul><li>[ ] Yes </li><li>[x] Not Applicable</li> </ul>|
|  Code sniffing and testing coverage reports (optional but encouraged). | <ul><li>[x] Yes </li><li>[ ] No</li> </ul>|
| Drupal.org vetted release (optional but encouraged). | <ul><li>[x] Yes </li><li>[ ] No</li> </ul>|

### CODE REVIEW

**Comment by spficklin** [comment]
Since this module comes from my program I will refrain from reviewing....

**Comment by almasaeed2010** [comment]
Everything looks good to me. One thing about testing that I don't think the guidelines mention is the percentage of coverage to consider that a module is well tested. This module only tests one class. Otherwise, looks like it checks every box 👍

**Comment by bradfordcondon** [comment]
this is an intentional omission.  We dont want to dictate a minimum test coverage, and test writing that executes code but doesnt make smart assertions for the sake of coverage.

That said I think we do want to encourage adequate testing.  At the extreme end is a single empty test class for example...

**Comment by spficklin** [comment]
I think implementation of testing without any tests doesn't qualify. I think to qualify for Gold there must be some effort (even if minimal) to create unit tests.

**Comment by laceysanderson** [comment]
1. Check Repository for:
  - [x] License (BRONZE)
  - [x] Public Release (BRONZE)
  - [x] Latest releases should follow 7.x-version format (SILVER)
  - [no fields] an includes/TripalFields directory (SILVER)
  - [doesn't import data] an includes/TripalImporter directory (GOLD)
  - [x] a tests directory (GOLD)
2. Check the README/docs for:
  - [x] Installation Instructions (BRONZE)
  - [x] Admin/Usage Instructions (BRONZE) 
  - [x] Link to Extensive Documentation (GOLD)
  - [x] Continuous integration badges (GOLD)
3. Check the install file for:
  - [x] use drupal schema api
  - [no use of chado] chado_create_custom_table() (BRONZE)
  - [no mviews?] chado_add_mview() (BRONZE)
  - [no fields] tripal_add_cvterm() or equivalent (BRONZE)
4. Check random file for Drupal coding standards. Specifically, (SILVER)
  - [x] docblock headers for functions
  - [x] general style (if/else blocks, array definitions)
  - [x] in-line commenting
5. Search code-base for
  - [doesn't query chado] `chado_query`, `chado_select_record`, `chado_update_record` (SILVER)
  - [x] `tripal_add_job` (SILVER)
  - [x] `tripal_report_error` (SILVER)
6. Check a random TripalField for:
  - [no fields] elementInfo (GOLD)
  - [no fields] query and queryOrder (GOLD)
7. Check for signs of an admin UI
  - [x] files with *admin* or *config* in the name
  - [no fields] settings in TripalFields
  - [no drush integration] drush options

Although a lot of criteria don't apply, this module does check all boxes that do apply. Therefore, I approve 👍

**Comment by bradfordcondon** [comment]
we've addressed the coverage issue so i think we're all happy with this.  Way to go!

**Pull request merged**
