### PR TITLE
try adding protocol query methods

### PR DESCRIPTION
**Pull request by bradfordcondon**
protocol field as discussed in #210 .  

It's a really minimal field.  The query etc looks correct to me but **please** just double check me because its still a little confusing.

### CODE REVIEW

**Comment by spficklin** [comment]
@bradfordcondon I'm not sure how to test this field. I have no data that uses the protocol field. I am happy to add some and test it but can you give me some sample data?

**Comment by bradfordcondon** [comment]
I also have no data that uses this field :(  I'd have to fabricate some.  It touches the MAGE Chado module and therefore the analysis expression module, but the analysis expression module just uses null dummy protocols and assays so it hasnt come up.
That said [the protocol table](https://laceysanderson.github.io/chado-docs/tables/protocol.html) just consists of linker keys and text.

**Comment by bradfordcondon** [comment]
oh im sorry you asked how to test. 

* Create content type for chado.protocol
* Create content type  chado.assay
* Create a protocol
* Try to create an assay that links to that protocol.

**Comment by spficklin** [comment]
I want to try the expression module.  I'll install it and use that.

**Comment by spficklin** [comment]
@bradfordcondon what CV terms are you using for protocol and assay?

**Comment by bradfordcondon** [comment]
protocol:

```
  tripal_insert_cvterm([
    'id' => 'sep:00101',
    'name' => 'protocol',
    'cv_name' => 'sep',
    'definition' => 'A protocol is a process which is a parameterizable description of a process.',
  ]);
```

Assay... i dont know.  looking at it now i like [SIO:001007](https://www.ebi.ac.uk/ols/ontologies/sio/terms?iri=http%3A%2F%2Fsemanticscience.org%2Fresource%2FSIO_001007).  It looks to me like the analysis_expression protocol module didnt get that far.

**Comment by spficklin** [comment]
So, it's taking me quite a bit of time to test this because I need to create a protocol, assay and arraydesign content types and many of those table columns don't have OBO terms associated with them.  So, I'm going through those tables and assigning them.

**Comment by spficklin** [comment]
Hey @bradfordcondon.  Thanks for submitting this PR!  It forced me to go through a bunch of fields for new tables that were not previously supported (protocol, assay, arraydesign) and helped me find some bugs in some of the current fields, provide some fixes for your protocol field, and fully support these tables.   So, because this sent me down a rabbit hole, I think for this PR, now that I've added additional code to it, you should probably re-review it yourself.  Here's what has changed:

1) I fixed the tripal_get_term_lookup_form() function.  That's the form that does the autocomplete for finding a term and then shows you the list of matched terms. It was not working properly when two fields used it on the same content type which was the case for the arraydesign table (substratetype_id and platformtype_id).  I also fixed it so it would find synonyms too.
2) In the process of resolving the issue just described  I fixed the same synonym problem when creating content types.
3) I fixed the local__contact field to support the arraydesign.manufacturer_id field.
4)  I fixed the schema__additional_type field so that it could be used the with arraydesign.substratetype_id and arraydesign.platformtype_id.  Previously it was hardcoded to expect a column name of 'type_id'.
5) I fixed the schema__publication field so that it would support a pub_id field (e.g. protocol.pub_id). Previously it only supported displaying of publications if they were linked through a linking table rather than a pub_id field in the base table.
6) I fixed the sep__protocol field in the following ways:
6a) There was a typo in the tripal_chado.fields.inc file  `if ($table_name != 'protocol' and`. It should have been `==`.
6b) When setting the field value the field for specifying the Chado field value was not set properly.
6c) The keys of the 'value' array where not correct.  They should have the CV terms (e.g. schema:name). I validated that with this fix the field shows up properly in web services>
6d) I removed the comments above the functions as it was copied from the original classes and isn't needed.
6e) I fixed the widget and formatter appropriately for the fix in the 'values' array.
7) I added code so that field for array, protocol and arraydesign work using existing fields.

That's a lot to test.  But it should be easy to test on a brand new Tripal site and creating content types for: Protocol, Assay and Array Design.  Then creating new pages for each of those and testing the fields to make sure they work.

**Comment by spficklin** [comment]
First, perform a ```drush updatedb```

So, here are some instructions for testing:
1) To test Item 1.  
1a) Create a new Protocol Content Type (term: "protocol").   There is a new Protocol Type field that is an autocomplete field named Protocol Type that should let you find a term. Just pick anything for the test, as it doesn't matter.  Save the page, and the protocol type should show up.  Editing the page and re-saving should allow you to change the protocol type.
1b) Create a new Array Design content type (term: "array content") and add a new array content content page.  You should have new fields for Substrate Type and Platform Type. You can use the protocol you just created for the Protocol field. You should be able to enter any cvterm in both, and the AJAX on both should function just fine.  Saving the protocol should result in both being saved and displayed. You should be able to edit and re-save both.
2)  For testing item 2.  On that Protocol content page, edit it and in either (or both) the Substrate Type and Platform Type use the autocomplete to find any term with spaces or other characters (those are typically synonyms).  Then click the "Lookup Term" button. It should show you the actual term name with the synonym you entered as a synonym.  You can also test the same functionality on the Create Tripal Content type admin page.
3).  To test item 3.  Create a new Content type called (term: "company"), link it to the contact table and contact.type_id field.  Add a new Company page (e.g. 'Affymetrix').  Next, Create a new Array Design content type (term: "array design").  Add a new Array Design page. You should see a field for the Manufacturer which is an auto complete field.  Enter the name of the Company you added. Save the page.  The manufacturer should show up. Edit the page and change the contact (if you have another). It should work.
4) To test item 4.  (This was also tested with test 2 above).
5) To test item 5.  Edit the new Protocol page you made and add a publication to it.  If you don't have a publication you can add one using drush (`drush trp-import-pubs --dbxref=PMID:29220446 --username=administrator`). It should save and appear,  This tests that the schema__publication field works with the pub is associated via a pub_id column in the base table. You can confirm it still works with a linker table by editing any feature and adding pubs.
6) Make sure your field works as intended.  It still needs query(), elementInfo(), queryOrder() funtions but we can add those with a differnet PR.
7) To test item 7.  Make create a content types for Assay (term: assay).  With all three types you've created (Protocol, Assay, Array Design), make sure that all the fields are appropriate (e.g. cardinality is correct, the label and description make sense, etc.).

**Review by spficklin — APPROVED** [review]

**Comment by bradfordcondon** [comment]
I'm able to create an assay bundle but not a protocol bundle.

```
Notice: Undefined index: field_name in tripal_create_bundle_fields() (line 666 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal/api/tripal.entities.api.inc).
Failed to create content type: Attempt to create an unnamed field
```

**Comment by bradfordcondon** [comment]
> [for Protocol] You should have new fields for Substrate Type and Platform Type. 

for those trying to test, these actually appear for `arraydesign`.

**Review by bradfordcondon — COMMENTED** [review]
oops, protocol type isnt nullable sorry

**Review by bradfordcondon — COMMENTED** [review]
When ccreating an assay I have an Array Design text field and the Operator is a text field.

screen shot 2018-06-06 at 10 08 49 am

**Comment by bradfordcondon** [comment]
### verified
- [x] protocol

- [x] publication on protocol

(minor issue noted: the matching terms doesnt have the previously selected term checked.  so if you edit the protocol, the edit will fail if you dont re-check the box).

- [x] array_design

### unverified
- [ ] assay

Assay has text boxes for Array_design and Operator (see above image).

**Comment by spficklin** [comment]
Thanks @bradfordcondon for reviewing. I fixed the branch so that now when you create the assay contnet type it sets a default title appropriately, and the operator_id is now working.  The arrraydesign field is still numeric but we don't have a field for that yet, so I had to leave it as it was.

**Comment by bradfordcondon** [comment]
OK Im not positive what the checks needed are for this PR but I approve it

**Comment by spficklin** [comment]
@bradfordcondon I think in this case the checks needed are just that the content types for protocol, assay and array design work and all fields (other than arraydesign on the assay content type) work as expected.  This includes your protocl field which got the whole thing rolling.   I'm going to add the Reviewer 1 approved tag since you indicated your approval.

**Comment by shawnawsu** [comment]
I've tried testing per Stephen's outline from about 3 days ago but I stumbled on step 1. After pulling down the branch and running the db update I created the protocol content type:
screen shot 2018-06-08 at 5 56 58 am
Then I checked the content type for the fields 'Substrate Type and Platform Type' but they weren't there so I clicked 'Check for new fields' and they still didn't show up:
screen shot 2018-06-08 at 5 59 22 am

I'm probably doing something wrong but I tested it on 2 different sites, one was a totally fresh build.

The sites are all chado 1.3 and tripal 3.

Thoughts?

**Comment by bradfordcondon** [comment]
I had confusion about the exact same thing!


@shawnawsu check out my comment right after:

>>[for Protocol] You should have new fields for Substrate Type and Platform Type.

>for those trying to test, these actually appear for arraydesign.

the MAGE module is kind of confusing.  Stephen's implementation was correct just the writeup had that mixup.  hope that helps.

**Comment by spficklin** [comment]
Ah! @shawnawsu sorry about that.  The Subtrate Type and Platform Type fields appear on the Array Design content type.  I'll fix the testing instructions above.

**Comment by shawnawsu** [comment]
The instructions are still confusing but I did my best. 

To test Item 1.
1a) Create a new Protocol Content Type (term: "protocol"). There is a new Protocol Type field that is an autocomplete field named Protocol Type that should let you find a term. Just pick anything for the test, as it doesn't matter. Save the page, and the protocol type should show up. Editing the page and re-saving should allow you to change the protocol type. **-- This works but the instructions are confusing, where should the protocol type show up? The node is published but I don't know if I should be looking for this some place within the site or if it's just the published node I am looking for.**

1b) Create a new Array Design content type (term: "array content") and add a new array content content page. You should have new fields for Substrate Type and Platform Type. You can use the protocol you just created for the Protocol field. You should be able to enter any cvterm in both, and the AJAX on both should function just fine. Saving the protocol should result in both being saved and displayed. You should be able to edit and re-save both. -- **The ajax autocomplete works for the two field specified however the instructions are confusing. The term is 'Array Design' not array content. The second to last sentence, I don't understand, why am I saving the protocol when I am in the array design content type node, should I be editing both at the same time? And you can't save and edit an array design content type node without a manufactuer because it's a required field.**

For testing item 2. On that Protocol content page, edit it and in either (or both) the Substrate Type and Platform Type use the autocomplete to find any term with spaces or other characters (those are typically synonyms). Then click the "Lookup Term" button. It should show you the actual term name with the synonym you entered as a synonym. You can also test the same functionality on the Create Tripal Content type admin page. **-- I could not complete this testing because the Substrate Type and Platform Type did not show up in my 'Protocol content page'**

3). To test item 3. Create a new Content type called (term: "company"), link it to the contact table and contact.type_id field. Add a new Company page (e.g. 'Affymetrix'). Next, Create a new Array Design content type (term: "array design"). Add a new Array Design page. You should see a field for the Manufacturer which is an auto complete field. Enter the name of the Company you added. Save the page. The manufacturer should show up. Edit the page and change the contact (if you have another). It should work. **-- Successful**

To test item 4. (This was also tested with test 2 above).

To test item 5. Edit the new Protocol page you made and add a publication to it. If you don't have a publication you can add one using drush (drush trp-import-pubs --dbxref=PMID:29220446 --username=administrator). It should save and appear, This tests that the schema__publication field works with the pub is associated via a pub_id column in the base table. You can confirm it still works with a linker table by editing any feature and adding pubs. **-- Successful**
Make sure your field works as intended. It still needs query(), elementInfo(), queryOrder() funtions but we can add those with a different PR.

To test item 7. Make create a content types for Assay (term: assay). With all three types you've created (Protocol, Assay, Array Design), make sure that all the fields are appropriate (e.g. cardinality is correct, the label and description make sense, etc.).  **-- Should the Array Design field within the Assay node be an autocomplete? I'm not sure what is intended by the second sentence but the assay content type  was created successfully and had protocol and array design fields.** 


In addition to the instruction confusion when you lookup a term in the Protocol content type node in the "Protocol Type" area you get these notifications in the watchdog log: 
```
Notice: Undefined index: terms_list in tripal_get_term_lookup_form_result() (line 772 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).

Notice: Undefined variable: fkey in schema__publication_widget->validate() (line 154 of /var/www/html/tripal20/sites/all/modules/tripal/tripal_chado/includes/TripalFields/schema__publication/schema__publication_widget.inc).

Notice: Undefined index: value in schema__additional_type_widget->form() (line 36 of /var/www/html/tripal20/sites/all/modules/tripal/tripal_chado/includes/TripalFields/schema__additional_type/schema__additional_type_widget.inc).

Notice: Undefined index: term_name in tripal_get_term_lookup_form() (line 596 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).
```

In the Array Design content type node in the "Platform Type" field when you click 'lookup term' after filling in the autocomplete field you get these notifications in the watchdog log:
```
Notice: Undefined index: terms_list in tripal_get_term_lookup_form_result() (line 772 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).

Notice: Undefined index: terms_list in tripal_get_term_lookup_form_result() (line 772 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).

Notice: Undefined index: term_name in tripal_get_term_lookup_form() (line 596 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).

Notice: Undefined index: value in schema__additional_type_widget->form() (line 36 of /var/www/html/tripal20/sites/all/modules/tripal/tripal_chado/includes/TripalFields/schema__additional_type/schema__additional_type_widget.inc).

Notice: Undefined index: term_name in tripal_get_term_lookup_form() (line 596 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).

```
In the Array Design content type node in the "Substrate Type" field when you click 'lookup term' after filling in the autocomplete field you get these notifications/errors (the error arises when searching terms with spaces in them, like large subunit rRNA) in the watchdog log:
```
Notice: Undefined index: terms_list in tripal_get_term_lookup_form_result() (line 772 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).

Notice: Undefined index: value in schema__additional_type_widget->form() (line 36 of /var/www/html/tripal20/sites/all/modules/tripal/tripal_chado/includes/TripalFields/schema__additional_type/schema__additional_type_widget.inc).

Notice: Undefined index: term_name in tripal_get_term_lookup_form() (line 596 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).


error: Cannot pass non array as argument, $object, to chado_expand_var function.

Notice: Undefined index: term_name in tripal_get_term_lookup_form() (line 596 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).
```

When trying to save a new Assay I get this error (could just be the random info I plopped in): 
`PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR: insert or update on table "assay" violates foreign key constraint "assay_arraydesign_id_fkey" DETAIL: Key (arraydesign_id)=(1) is not present in table "arraydesign". in TripalEntityController->save() (line 413 of /var/www/html/tripal20/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).`

**Comment by shawnawsu** [comment]
Approved

I spoke with Stephen and he explained the vague or confusing language in the testing instruction and all my issues are now resolved. Plus I separated out the notices and error into another issue.

**Pull request merged**
