### PR TITLE
Merged data collections with the file management

### PR DESCRIPTION
**Pull request by spficklin**
Issue #555

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

Files created via data collections were not integrated with the file management system and therefore not subject to quotas.  This fixes that problem.  It also forced a number of changes:

1)  The "Data Collections" tab no longer exists on the user's profile page. Instead collections are now dealt with via the 'Files' tab.  See the screen shot.  
2) This updated Files tab provides a table that lists data collections that are "pending" (i.e. files haven't been generated yet). It also provides an interactive file browser.
3) I fixed a bug in that data collections always reported only having 1 record. 
4) Data collection files are now stored in a 'data_collections' directory which makes them easier to spot in the interactive file browser.

## Testing?

1.  Pull this branch
2.  clear your cache (drush cc all)
2.  Create a new data collection using Views.
3.  Go to the files page on your user profile page.  You should see your data collection in the 'Pending Data Collections' table.
4.  Click the 'Create Files' link to generate the files, and run the job.
5. Reload the Files tab. You should now find the files for the data collection in the 'data_collections' folder in the interactive file browser.  
6.  Perform any additional actions: e.g. download the file, renew the expiration date, delete a single file, delete an entire collection, etc.

## Screenshots (if appropriate):
image

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by spficklin** [comment]
Note: the new 'Files' tab is a bit long now. It probably could benefit from vertical tabs or something, but time is short and function trumps form at this point.

**Comment by bradfordcondon** [comment]
hi @spficklin i added clearing cache to your instructions, failing to do so will be very unfortunate :P

The file browser is awesome!  But clicking on it and changing files is a little confusing.... seems like the highlighted file doesnt change?  Note mismatch below.

screen shot 2018-08-26 at 12 34 28 pm


I created a collection, I'll report back that the file changed (from 645.37MB for my own tracking) when the file is created.

Overall looks great 👍

**Comment by bradfordcondon** [comment]
looks good to me!  approved.
 
screen shot 2018-08-26 at 5 10 36 pm

**Review by bradfordcondon — APPROVED** [review]

**Comment by spficklin** [comment]
Thanks for the test @bradfordcondon.  Adding a highlight for the selected file was easy enough.  I'e just committed a fix. Here's a screenshot:

image

**Comment by spficklin** [comment]
I just noticed @bradfordcondon in your screenshot the banding colors are off.  It should color each row differently.  Can you confirm is screwed up on your end?

**Comment by bradfordcondon** [comment]
yes it is.  Could it be our HWG theme?

**Comment by almasaeed2010** [comment]
Hello @spficklin 

The branch works as expected. Deleting single files, deleting collections, renewing and creating new collections work nicely.

The browser looks nice and feels easy to get familiar with!

Thanks

**Review by almasaeed2010 — APPROVED** [review]

**Comment by bradfordcondon** [comment]
@spficklin im going to merge this.  If we want to fix the CSS I think thats a minor enough issue that could go in a single reveiwer PR, and certainly not a release blocker.

**Comment by spficklin** [comment]
Thanks @almasaeed2010 and @bradfordcondon !

**Pull request merged**
