### PR TITLE
Fixed loadOntology function in the GFF3 importer to not return if it …

### PR DESCRIPTION
**Pull request by spficklin**
# Bug Fix

Issue #926 

## Description

As reported by @mpoelchau, the GFF importer would not import all of the Ontology terms if one of them did not already exist in the database.  The importer would just stop trying once it found a problem.  The example is if there are InterPro terms in a GFF3 file mixed with GO terms.  If GO is loaded by the IPR terms are not then the first IPR term encountered would cause import of ontology terms to stop.    For example:

```
QKKF02000028.1	Genbank	mRNA	3267	4896	.	+	.	locus_tag=LSTR_LSTR016833;ID=LSTR016833-RA;Parent=LSTR016833;Ontology_term=KEGG:K05096,InterPro:IPR002290,InterPro:IPR020635,GO:0004672,GO:0004713,InterPro:IPR001245,GO:0006468,InterPro:IPR000719,GO:0005524;
```

The simple fix was to not return from the load ontology function and just continue trying to process the other terms in the list.  I did make a few other changes that are very minor:  1) I just adjusted some commenting that was incorrectly formated.  2) I just happen to notice that some of the update functions weren't wrapped in a try catch statement, so I added that.

## Testing?

1) On a test Tripal site, create a new test organism and analysis.
2) Make sure you have the Gene Ontology loaded.
3) Import the test.fasta sequence below.  (I couldn't upload a file with a .fasta extension so I had to add an extra .txt on the end.  You'll want to remove that.)
4) Import the test.gff file below
5) Publish the `mRNA` content type.
6) Check the mRNA page to make sure that all of the GO terms are loaded.  The IPR terms should be missing.  You should have these terms: GO:0004672, GO:0004713, GO:0006468, GO:0005524

Here are test files:

[test.fasta.txt](https://github.com/tripal/tripal/files/3117565/test.fasta.txt)
[test.gff.txt](https://github.com/tripal/tripal/files/3117566/test.gff.txt)

## Screenshots (if appropriate):
PRsc

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Unfortunately, this didn't work for me. I am not sure what could be causing the issue though. Here is what I did:

- Create an organism
- Create an analysis to associate the features with (fasta)
- Load the fasta file using mRNA as sequence type
- Create an analysis for the GFF
- Load GFF and specify the organism and analysis (no other fields were changed in the loader form).

 Output from GFF loader:

```
Running 'Chado GFF3 File Loader' importer
NOTE: Loading of file is performed using a database transaction. 
If it fails or is terminated prematurely then all insertions and 
updates are rolled back and will not be found in the database

Opening /home/www/sites/default/files/tripal/users/1/test.gff
Accession, IPR002290 is missing for reference: InterPro:IPR002290.
Accession, IPR020635 is missing for reference: InterPro:IPR020635.
CV Term is missing for reference: InterPro:IPR001245.
CV Term is missing for reference: InterPro:IPR000719.
Setting ranks of children...Memory: 54,333,056 bytes.

Done.

Remapping Chado Controlled vocabularies to Tripal Terms...
Done.
```

When running `select * from chado.feature_cvterm where feature_id = 7165544;` I get nothing.

Screen Shot 2019-04-26 at 12 24 34 PM

Am I missing anything?

Thanks!

**Comment by almasaeed2010** [comment]
I also verified that we have GO loaded:

Screen Shot 2019-04-26 at 12 25 45 PM

**Comment by spficklin** [comment]
Hmmm....  a few things to check:

1) Can you check that you have the terms listed:
```sql
SELECT * 
FROM dbxref DBX
  INNER JOIN db DB on DB.db_id = DBX.db_id
WHERE DBX.accession in ('0004672', '0004713', '0006468', '0005524') and
 DB.name = 'GO'
```
2) Did you click the 'Reload' tab on the mRNA page to make sure results weren't just being cached from a previous view?
3) Dumb question... you're certain you have the right branch checked-out?

That's all I can think of.  

My output from the job looks a bit different from yours here's what I see:

```
Running 'Chado GFF3 File Loader' importer
NOTE: Loading of file is performed using a database transaction. 
If it fails or is terminated prematurely then all insertions and 
updates are rolled back and will not be found in the database

Opening /var/www/html/sites/default/files/tripal/users/1/test.gff
Accession, K05096 is missing for reference: KEGG:K05096.
Accession, IPR002290 is missing for reference: InterPro:IPR002290.
Accession, IPR020635 is missing for reference: InterPro:IPR020635.
Accession, IPR001245 is missing for reference: InterPro:IPR001245.
Accession, IPR000719 is missing for reference: InterPro:IPR000719.
Setting ranks of children...Memory: 39,364,536 bytes.

Done.
```
Do you have some IPR terms loaded? It's interesting you are getting `CV Term is missing for reference`. You get that message if you have the accession in the `dbxref` table but no matching term for it in the `cvterm` table.

**Comment by bradfordcondon** [comment]
adding a nonfunctional approval. changes make sense and code looks reasonable.

**Comment by spficklin** [comment]
Thanks @bradfordcondon

**Comment by almasaeed2010** [comment]
Hello @spficklin 

Sorry it took me a while to get back to this!

1.
```sql
SELECT * 
FROM chado.dbxref DBX
  INNER JOIN chado.db DB on DB.db_id = DBX.db_id
WHERE DBX.accession in ('0004672', '0004713', '0006468', '0005524') and
 DB.name = 'GO'
```

 |dbxref_id |db_id|accession|version|description|db_id|name|description|urlprefix|url|               
-----------|------|----------|-------|-----------|----|-------|------|-------------|---|
119377 |   109 | 0004672   |         |             |   109 | GO   |             | http://amigo.geneontology.org/amigo/term/{db}:{accession} | http://amigo.geneontology.org/amigo
120844 |   109 | 0004713   |         |             |   109 | GO   |             | http://amigo.geneontology.org/amigo/term/{db}:{accession} | http://amigo.geneontology.org/amigo
126565 |   109 | 0005524   |         |             |   109 | GO   |             | http://amigo.geneontology.org/amigo/term/{db}:{accession} | http://amigo.geneontology.org/amigo
106553 |   109 | 0006468   |         |             |   109 | GO   |             | http://amigo.geneontology.org/amigo/term/{db}:{accession} | http://amigo.geneontology.org/amigo
(4 rows)

2. I cleared cache using the reload button and using the drush cc all command

3. I am on the correct branch.

It looks like our interpro `db.name` is `INTERPRO` not `InterPro`:

```sql
select * from chado.db where db_id = 61;
```
|db_id|name|description|
|-----|------|-----------|
|61|	INTERPRO | InterPro provides functional analysis of proteins by classifying them into families and predicting domains and important sites. It combines protein signatures from a number of member databases into a single searchable resource. | http://www.ebi.ac.uk/interpro/entry/{accession}	http://www.ebi.ac.uk/interpro/

It looks like we also have InterPro as a db name but it doesn't have the same accessions associated with.

```sql
select count(*) from chado.dbxref inner 
   join chado.db on db.db_id = dbxref.db_id 
   where db.name = 'InterPro';
3716


select count(*) from chado.dbxref 
   inner join chado.db on db.db_id = dbxref.db_id 
   where db.name = 'INTERPRO';
9693
```

With that in mind, I think this is mainly an HWG issue. I can try to do this again on a fresh site to see if the issue persists.

**Comment by almasaeed2010** [comment]
I re-ran the tests on a fresh Tripal site but unfortunately I still can't get the annotations to show up.

Screen Shot 2019-05-03 at 9 06 19 AM

```js
2019-05-03 09:05:49: Calling: tripal_run_importer(10)

Running 'Chado GFF3 File Loader' importer
NOTE: Loading of file is performed using a database transaction. 
If it fails or is terminated prematurely then all insertions and 
updates are rolled back and will not be found in the database

Opening /var/www/Tripal/sites/default/files/tripal/users/1/test.gff
Accession, K05096 is missing for reference: KEGG:K05096.
Accession, IPR002290 is missing for reference: InterPro:IPR002290.
Accession, IPR020635 is missing for reference: InterPro:IPR020635.
Accession, IPR001245 is missing for reference: InterPro:IPR001245.
Accession, IPR000719 is missing for reference: InterPro:IPR000719.
Setting ranks of children...Memory: 34,416,880 bytes.

Done.

Remapping Chado Controlled vocabularies to Tripal Terms...
Done.
```

GO terms exist (but interpro and kegg are missing):
```sql
=> SELECT * 
FROM chado.dbxref DBX
  INNER JOIN chado.db DB on DB.db_id = DBX.db_id
WHERE DBX.accession in ('0004672', '0004713', '0006468', '0005524') and
 DB.name = 'GO';

13187	46	0004672			46	GO			
13836	46	0004713			46	GO			
16299	46	0005524			46	GO			
6524	46	0006468			46	GO
```

I am not sure if I am doing something wrong or if there are missing records in my setup. Perhaps someone else can run the tests to verify?

Thanks!

**Comment by spficklin** [comment]
Do you have the GO entries added in the `feature_cvterm` table?

**Comment by almasaeed2010** [comment]
My `feature_cvterm` table is empty.

**Review by laceysanderson — APPROVED** [review]
I just ran this on a fresh Tripal site and got the desired result:
Screen Shot 2019-05-10 at 1 11 51 PM

I still feel concerned by it not working for @almasaeed2010 though...

**Comment by almasaeed2010** [comment]
We don’t normally use GFFs for annotations in our site so I am not very familiar with the loader. It’s very likely that I am doing something wrong or missing a step.

**Pull request merged**
